#!/usr/bin/env python3
# serenitymojo/training/parity/block_composed_torch_oracle.py
#
# PyTorch f64 autograd oracle + GENERATOR for block_composed_parity.mojo.
#
# Builds the SAME transformer-ish DiT block the Mojo file hand-chains, runs
# torch autograd for the reference gradients, then WRITES the full
# block_composed_parity.mojo (template + embedded f64 data block) so the data
# is never hand-transcribed. Mirrors the "THIS FILE IS GENERATED" pattern of
# composed_chain_parity.mojo.
#
# BLOCK (tiny dims; M=4 tokens, D=8 model dim, H=2 heads, Dh=4 head_dim, F=16):
#   h1   = rms_norm(x, g1)                      RMSNorm over last dim D
#   q = h1@Wq^T   k = h1@Wk^T   v = h1@Wv^T     each [M,D]
#   multi-head sdpa over [1,M,H,Dh] BSHD (row-major [M,D] == [1,M,H,Dh]):
#     per head h, attn_h = softmax(q_h k_h^T * scale) v_h   (scale = 1/sqrt(Dh))
#   attn = concat_heads -> [M,D]
#   ao   = attn @ Wo^T                          output projection [M,D]
#   r1   = x + ao                               RESIDUAL #1  (x branches!)
#   h2   = rms_norm(r1, g2)
#   gate = h2 @ Wg^T   up = h2 @ Wu^T           SwiGLU MLP, hidden F
#   act  = silu(gate) * up                      [M,F]
#   mlp  = act @ Wd^T                            down proj -> [M,D]
#   y    = r1 + mlp                             RESIDUAL #2  (r1 branches!)
#   L    = mean((y - target)^2)
#
# The torch per-head split q[:, h*Dh:(h+1)*Dh] and the Mojo full-BSHD sdpa over
# [1,M,H,Dh] are bit-equivalent: in row-major [M, H*Dh], element (s,h,d) sits at
# flat s*D + (h*Dh+d) -- exactly column (h*Dh+d) of row s, which is the (s,h,d)
# slot of BSHD [1,M,H,Dh]. So one sdpa_nomask call == torch's concat-of-heads.
#
# Composition subtlety the gate exists to catch: x feeds BOTH rms_norm(h1) AND
# the residual r1=x+ao, so d_x = (grad via norm/attn path) + (grad via residual).
# Likewise r1 feeds BOTH rms_norm(h2) AND y=r1+mlp. The hand-chained Mojo
# backward MUST SUM these branch contributions. A dropped branch -> wrong d_x.
#
# Run (regenerates the .mojo):
#   /home/alex/serenityflow-v2/.venv/bin/python \
#       serenitymojo/training/parity/block_composed_torch_oracle.py

import os
import torch

torch.manual_seed(1234)
DT = torch.float64

M, D, H, Dh, F = 4, 8, 2, 4, 16
assert H * Dh == D
SCALE = 1.0 / (Dh ** 0.5)
EPS = 1e-6


def randn(*shape):
    return torch.randn(*shape, dtype=DT)


def lit(t):
    flat = t.detach().reshape(-1).tolist()
    return "[" + ", ".join(repr(float(v)) for v in flat) + "]"


# ---- inputs / params ----
x = randn(M, D).requires_grad_(True)
g1 = randn(D).requires_grad_(True)
g2 = randn(D).requires_grad_(True)
Wq = randn(D, D).requires_grad_(True)
Wk = randn(D, D).requires_grad_(True)
Wv = randn(D, D).requires_grad_(True)
Wo = randn(D, D).requires_grad_(True)
Wg = randn(F, D).requires_grad_(True)
Wu = randn(F, D).requires_grad_(True)
Wd = randn(D, F).requires_grad_(True)
target = randn(M, D)


def rms_norm(t, g):
    ms = t.pow(2).mean(dim=-1, keepdim=True)
    return t / torch.sqrt(ms + EPS) * g


def linear(t, W):
    return t @ W.t()


def sdpa_sh(q, k, v, scale):
    attn = torch.softmax((q @ k.t()) * scale, dim=-1)
    return attn @ v


# ---- forward (identical structure to the Mojo hand-chain) ----
h1 = rms_norm(x, g1)
q = linear(h1, Wq)
k = linear(h1, Wk)
v = linear(h1, Wv)
heads = []
for hh in range(H):
    sl = slice(hh * Dh, (hh + 1) * Dh)
    heads.append(sdpa_sh(q[:, sl], k[:, sl], v[:, sl], SCALE))
attn = torch.cat(heads, dim=-1)
ao = linear(attn, Wo)
r1 = x + ao  # RESIDUAL #1
h2 = rms_norm(r1, g2)
gate = linear(h2, Wg)
up = linear(h2, Wu)
act = torch.nn.functional.silu(gate) * up
mlp = linear(act, Wd)
y = r1 + mlp  # RESIDUAL #2
L = ((y - target) ** 2).mean()

dx, dWq, dWo, dWg, dWd, dg1, dg2 = torch.autograd.grad(
    L, [x, Wq, Wo, Wg, Wd, g1, g2]
)
LOSS = float(L.item())

DATA = {
    "X_h": x, "G1_h": g1, "G2_h": g2,
    "WQ_h": Wq, "WK_h": Wk, "WV_h": Wv, "WO_h": Wo,
    "WG_h": Wg, "WU_h": Wu, "WD_h": Wd,
    "TARGET_h": target,
    "REF_DX": dx, "REF_DWQ": dWq, "REF_DWO": dWo,
    "REF_DWG": dWg, "REF_DWD": dWd, "REF_DG1": dg1, "REF_DG2": dg2,
}

data_lines = []
for name, t in DATA.items():
    data_lines.append(f"    var {name}: List[Float32] = {lit(t)}")
DATA_BLOCK = "\n".join(data_lines)

# ---------------------------------------------------------------------------
# Emit the full block_composed_parity.mojo
# ---------------------------------------------------------------------------
MOJO = f'''# serenitymojo/training/parity/block_composed_parity.mojo
#
# FULL TRANSFORMER-BLOCK composed-backward gate (NO tape / NO autograd.mojo).
# THIS FILE IS GENERATED by block_composed_torch_oracle.py -- do not hand-edit
# the embedded f64 data block; regenerate it from the oracle instead.
#
# PURPOSE: the deepest klein-class composition test. Every per-op backward
# kernel is individually parity-clean, yet hand-CHAINING them through a real
# DiT block -- with TWO residual branch points where a tensor's grad is the SUM
# of two paths -- is exactly where flame-core's klein runaway lived (a composed
# backward that is wrong while every block is clean; see EriDiffusion memory
# project_klein_runaway_composition_backward_2026-05-29). This gates the Mojo
# hand-chained block backward vs PyTorch autograd AND vs in-Mojo finite-diff.
#
# BLOCK (M={M} tokens, D={D} model dim, H={H} heads, Dh={Dh} head_dim, F={F} mlp hidden):
#   h1   = rms_norm(x, g1)
#   q,k,v= linear(h1,Wq/Wk/Wv)             each [M,D]
#   attn = sdpa over [1,M,H,Dh] BSHD       scale = 1/sqrt(Dh)  (multi-head)
#   ao   = linear(attn, Wo)
#   r1   = x + ao                          <-- RESIDUAL #1  (x branches)
#   h2   = rms_norm(r1, g2)
#   gate = linear(h2, Wg)  up = linear(h2, Wu)   [M,F]
#   act  = swiglu(gate, up) = silu(gate)*up      [M,F]
#   mlp  = linear(act, Wd)                       [M,D]
#   y    = r1 + mlp                         <-- RESIDUAL #2  (r1 branches)
#   L    = mse(y, target)
#
# (row-major [M,D] is exactly [1,M,H,Dh] BSHD with D=H*Dh, so a single
#  sdpa_nomask / sdpa_backward call reproduces torch's per-head concat exactly.)
#
# MANUAL BACKWARD (reverse, grads threaded BY HAND, real per-op kernels):
#   dy            = 2*(y-target)/numel
#   d_r1  = dy ; d_mlp = dy                       (residual #2 split: BOTH paths)
#   (d_act,dWd)   = linear_backward(d_mlp, act, Wd)
#   (d_gate,d_up) = swiglu_backward(d_act, gate, up)
#   (d_h2_g,dWg)  = linear_backward(d_gate, h2, Wg)
#   (d_h2_u,dWu)  = linear_backward(d_up,   h2, Wu)
#   d_h2  = d_h2_g + d_h2_u                       (h2 feeds BOTH gate & up linears)
#   (d_r1_norm,dg2)= rms_norm_backward(d_h2, r1, g2)
#   d_r1 += d_r1_norm                             (RESIDUAL #1 accumulate into r1)
#   (d_attn,dWo)  = linear_backward(d_r1, attn, Wo)
#   (d_q,d_k,d_v) = sdpa_backward(d_attn, q,k,v)  (one call, BSHD [1,M,H,Dh])
#   (d_h1_q,dWq)  = linear_backward(d_q, h1, Wq)
#   (d_h1_k,dWk)  = linear_backward(d_k, h1, Wk)
#   (d_h1_v,dWv)  = linear_backward(d_v, h1, Wv)
#   d_h1  = d_h1_q + d_h1_k + d_h1_v             (h1 feeds q,k,v -- SUM 3 paths)
#   (d_x_norm,dg1)= rms_norm_backward(d_h1, x, g1)
#   d_x   = d_x_norm + d_r1                       (RESIDUAL #1: x's OTHER branch)
#
# The d_x = d_x_norm + d_r1 line and the d_h1 = q+k+v sum are the make-or-break
# composition steps. If a branch is dropped, d_x disagrees with both oracles.
#
# GATE: chained vs torch cos>=0.999 ; chained vs finite-diff cos>=0.99.
#
# Run:
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \\
#     pixi run mojo run -I . serenitymojo/training/parity/block_composed_parity.mojo

from std.gpu.host import DeviceContext
from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.ops.linear import linear
from serenitymojo.ops.norm import rms_norm
from serenitymojo.ops.activations import swiglu
from serenitymojo.ops.attention import sdpa_nomask
from serenitymojo.ops.loss_swiglu_backward import swiglu_backward
from serenitymojo.ops.linalg_backward import linear_backward
from serenitymojo.ops.norm_backward import rms_norm_backward
from serenitymojo.ops.attention_backward import sdpa_backward, SdpaGrads
from serenitymojo.parity import ParityHarness
from std.collections import List, Optional


comptime M = {M}
comptime D = {D}
comptime H = {H}
comptime Dh = {Dh}
comptime FF = {F}
comptime EPS = Float32({EPS})
comptime SCALE = Float32({SCALE!r})


# ── host helpers (the by-hand grad threading lives here; there is NO tape) ──
def add_lists(a: List[Float32], b: List[Float32]) -> List[Float32]:
    var o = List[Float32]()
    for i in range(len(a)):
        o.append(a[i] + b[i])
    return o^


# SdpaGrads is Movable-only (no Copyable); reading .d_q/.d_k/.d_v individually
# via sb.d_q.to_host(...) while still needing the other two fails the borrow
# checker ("value has no attribute 'd_q'"). Consume the struct once here,
# moving each field out in turn, into a Copyable carrier of host lists.
struct SdpaHostGrads(Copyable, Movable):
    var d_q: List[Float32]
    var d_k: List[Float32]
    var d_v: List[Float32]

    def __init__(
        out self,
        var d_q: List[Float32],
        var d_k: List[Float32],
        var d_v: List[Float32],
    ):
        self.d_q = d_q^
        self.d_k = d_k^
        self.d_v = d_v^


def sdpa_grads_to_host(
    var sb: SdpaGrads, ctx: DeviceContext
) raises -> SdpaHostGrads:
    var dq = sb.d_q^.to_host(ctx)
    var dk = sb.d_k^.to_host(ctx)
    var dv = sb.d_v^.to_host(ctx)
    return SdpaHostGrads(dq^, dk^, dv^)


def linear_fwd(
    x_h: List[Float32], w_h: List[Float32],
    rows: Int, kin: Int, nout: Int, ctx: DeviceContext,
) raises -> List[Float32]:
    var no_bias = Optional[Tensor](None)
    return linear(
        Tensor.from_host(x_h, [rows, kin], STDtype.F32, ctx),
        Tensor.from_host(w_h, [nout, kin], STDtype.F32, ctx),
        no_bias^, ctx,
    ).to_host(ctx)


def rms_fwd(
    x_h: List[Float32], g_h: List[Float32], ctx: DeviceContext,
) raises -> List[Float32]:
    return rms_norm(
        Tensor.from_host(x_h, [M, D], STDtype.F32, ctx),
        Tensor.from_host(g_h, [D], STDtype.F32, ctx),
        EPS, ctx,
    ).to_host(ctx)


# multi-head sdpa over the [M,D] activation, viewed as BSHD [1,M,H,Dh].
# B/S/H/Dh are compile-time params on sdpa_nomask -> pass via [..] brackets.
def sdpa_fwd(
    q_h: List[Float32], k_h: List[Float32], v_h: List[Float32],
    ctx: DeviceContext,
) raises -> List[Float32]:
    return sdpa_nomask[1, M, H, Dh](
        Tensor.from_host(q_h, [1, M, H, Dh], STDtype.F32, ctx),
        Tensor.from_host(k_h, [1, M, H, Dh], STDtype.F32, ctx),
        Tensor.from_host(v_h, [1, M, H, Dh], STDtype.F32, ctx),
        SCALE, ctx,
    ).to_host(ctx)


# Full block forward over fresh tensors -> scalar loss (used for main + finite-diff).
def forward_loss(
    x_h: List[Float32], g1_h: List[Float32], g2_h: List[Float32],
    wq_h: List[Float32], wk_h: List[Float32], wv_h: List[Float32],
    wo_h: List[Float32], wg_h: List[Float32], wu_h: List[Float32],
    wd_h: List[Float32], tgt_h: List[Float32], ctx: DeviceContext,
) raises -> Float32:
    var h1 = rms_fwd(x_h, g1_h, ctx)                       # [M,D]
    var q = linear_fwd(h1, wq_h, M, D, D, ctx)            # [M,D]
    var kk = linear_fwd(h1, wk_h, M, D, D, ctx)
    var vv = linear_fwd(h1, wv_h, M, D, D, ctx)
    var attn = sdpa_fwd(q, kk, vv, ctx)                    # [M,D] (== [1,M,H,Dh])
    var ao = linear_fwd(attn, wo_h, M, D, D, ctx)         # [M,D]
    var r1 = add_lists(x_h, ao)                            # residual #1
    var h2 = rms_fwd(r1, g2_h, ctx)
    var gate = linear_fwd(h2, wg_h, M, D, FF, ctx)        # [M,F]
    var up = linear_fwd(h2, wu_h, M, D, FF, ctx)
    var act = swiglu(
        Tensor.from_host(gate, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(up, [M, FF], STDtype.F32, ctx),
        ctx,
    ).to_host(ctx)                                         # [M,F]
    var mlp = linear_fwd(act, wd_h, M, FF, D, ctx)        # [M,D]
    var y = add_lists(r1, mlp)                             # residual #2
    var acc: Float32 = 0.0
    for i in range(len(y)):
        var dff = y[i] - tgt_h[i]
        acc += dff * dff
    return acc / Float32(len(y))


def main() raises:
    var ctx = DeviceContext()
    print("==== block_composed_parity (FULL DiT block, NO tape) ====")
    print("block: rms->attn(+res)->rms->swiglu-mlp(+res)->mse  hand-chained bwd")
    print("M=", M, " D=", D, " H=", H, " Dh=", Dh, " F=", FF)

{DATA_BLOCK}

    var loss = forward_loss(
        X_h, G1_h, G2_h, WQ_h, WK_h, WV_h, WO_h, WG_h, WU_h, WD_h, TARGET_h, ctx
    )
    print("forward loss =", loss, " (torch oracle =", Float32({LOSS!r}), ")")

    # ── FORWARD, saving every intermediate the backward needs (NO tape) ──
    var h1 = rms_fwd(X_h, G1_h, ctx)                       # [M,D]
    var q = linear_fwd(h1, WQ_h, M, D, D, ctx)
    var kk = linear_fwd(h1, WK_h, M, D, D, ctx)
    var vv = linear_fwd(h1, WV_h, M, D, D, ctx)
    var attn = sdpa_fwd(q, kk, vv, ctx)                    # [M,D]
    var ao = linear_fwd(attn, WO_h, M, D, D, ctx)
    var r1 = add_lists(X_h, ao)
    var h2 = rms_fwd(r1, G2_h, ctx)
    var gate = linear_fwd(h2, WG_h, M, D, FF, ctx)
    var up = linear_fwd(h2, WU_h, M, D, FF, ctx)
    var act = swiglu(
        Tensor.from_host(gate, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(up, [M, FF], STDtype.F32, ctx),
        ctx,
    ).to_host(ctx)
    var mlp = linear_fwd(act, WD_h, M, FF, D, ctx)
    var y = add_lists(r1, mlp)

    # ── MANUAL BACKWARD CHAIN (reverse; grads threaded BY HAND) ──
    # dy = d(mse)/dy = 2*(y-target)/numel
    var dy = List[Float32]()
    for i in range(len(y)):
        dy.append(2.0 * (y[i] - TARGET_h[i]) / Float32(len(y)))

    # residual #2 split: y = r1 + mlp  ->  d_r1 (partial) = dy ; d_mlp = dy
    var d_r1 = dy.copy()          # r1's FIRST branch contribution (the residual)
    var d_mlp = dy.copy()

    # mlp = linear(act, Wd):  (d_act, dWd) = linear_backward(d_mlp, act, Wd)
    var lb_d = linear_backward(
        Tensor.from_host(d_mlp, [M, D], STDtype.F32, ctx),
        Tensor.from_host(act, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(WD_h, [D, FF], STDtype.F32, ctx),
        M, FF, D, ctx,
    )
    var d_act = lb_d.d_x.to_host(ctx)        # [M,F]
    var dWd = lb_d.d_w.to_host(ctx)          # [D,F]

    # act = swiglu(gate, up):  (d_gate, d_up) = swiglu_backward(d_act, gate, up)
    var sgb = swiglu_backward(
        Tensor.from_host(d_act, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(gate, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(up, [M, FF], STDtype.F32, ctx),
        ctx,
    )
    var d_gate = sgb.d_gate.to_host(ctx)     # [M,F]
    var d_up = sgb.d_up.to_host(ctx)         # [M,F]

    # gate = linear(h2, Wg) ; up = linear(h2, Wu).  h2 feeds BOTH -> sum d_h2.
    var lb_g = linear_backward(
        Tensor.from_host(d_gate, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(h2, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WG_h, [FF, D], STDtype.F32, ctx),
        M, D, FF, ctx,
    )
    var d_h2_g = lb_g.d_x.to_host(ctx)
    var dWg = lb_g.d_w.to_host(ctx)
    var lb_u = linear_backward(
        Tensor.from_host(d_up, [M, FF], STDtype.F32, ctx),
        Tensor.from_host(h2, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WU_h, [FF, D], STDtype.F32, ctx),
        M, D, FF, ctx,
    )
    var d_h2_u = lb_u.d_x.to_host(ctx)
    var d_h2 = add_lists(d_h2_g, d_h2_u)     # COMPOSITION: h2 -> gate + up

    # h2 = rms_norm(r1, g2):  (d_r1_norm, dg2) = rms_norm_backward(d_h2, r1, g2)
    var nb2 = rms_norm_backward(
        Tensor.from_host(d_h2, [M, D], STDtype.F32, ctx),
        Tensor.from_host(r1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(G2_h, [D], STDtype.F32, ctx),
        EPS, ctx,
    )
    var d_r1_norm = nb2.d_x.to_host(ctx)
    var dg2 = nb2.d_g.to_host(ctx)
    # RESIDUAL #1 accumulate: r1 feeds BOTH y (already in d_r1) AND rms_norm(h2).
    d_r1 = add_lists(d_r1, d_r1_norm)        # COMPOSITION: r1's two branches

    # ao = linear(attn, Wo):  (d_attn, dWo) = linear_backward(d_r1, attn, Wo)
    var lb_o = linear_backward(
        Tensor.from_host(d_r1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(attn, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WO_h, [D, D], STDtype.F32, ctx),
        M, D, D, ctx,
    )
    var d_attn = lb_o.d_x.to_host(ctx)       # [M,D]
    var dWo = lb_o.d_w.to_host(ctx)

    # attn = sdpa(q,k,v): one BSHD [1,M,H,Dh] backward -> d_q,d_k,d_v each [M,D].
    # sdpa_backward signature is [B,S,H,Dh](q, k, v, d_out, scale, ctx).
    var sb = sdpa_backward[1, M, H, Dh](
        Tensor.from_host(q, [1, M, H, Dh], STDtype.F32, ctx),
        Tensor.from_host(kk, [1, M, H, Dh], STDtype.F32, ctx),
        Tensor.from_host(vv, [1, M, H, Dh], STDtype.F32, ctx),
        Tensor.from_host(d_attn, [1, M, H, Dh], STDtype.F32, ctx),
        SCALE, ctx,
    )
    var sdpa_g = sdpa_grads_to_host(sb^, ctx)      # carrier of d_q,d_k,d_v [M,D]
    var d_q = sdpa_g.d_q.copy()
    var d_k = sdpa_g.d_k.copy()
    var d_v = sdpa_g.d_v.copy()

    # q,k,v = linear(h1, Wq/Wk/Wv).  h1 feeds ALL THREE -> sum the d_h1 paths.
    var lb_q = linear_backward(
        Tensor.from_host(d_q, [M, D], STDtype.F32, ctx),
        Tensor.from_host(h1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WQ_h, [D, D], STDtype.F32, ctx),
        M, D, D, ctx,
    )
    var d_h1_q = lb_q.d_x.to_host(ctx)
    var dWq = lb_q.d_w.to_host(ctx)
    var lb_k = linear_backward(
        Tensor.from_host(d_k, [M, D], STDtype.F32, ctx),
        Tensor.from_host(h1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WK_h, [D, D], STDtype.F32, ctx),
        M, D, D, ctx,
    )
    var d_h1_k = lb_k.d_x.to_host(ctx)
    var lb_v = linear_backward(
        Tensor.from_host(d_v, [M, D], STDtype.F32, ctx),
        Tensor.from_host(h1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(WV_h, [D, D], STDtype.F32, ctx),
        M, D, D, ctx,
    )
    var d_h1_v = lb_v.d_x.to_host(ctx)
    var d_h1 = add_lists(add_lists(d_h1_q, d_h1_k), d_h1_v)  # COMPOSITION q+k+v

    # h1 = rms_norm(x, g1):  (d_x_norm, dg1) = rms_norm_backward(d_h1, x, g1)
    var nb1 = rms_norm_backward(
        Tensor.from_host(d_h1, [M, D], STDtype.F32, ctx),
        Tensor.from_host(X_h, [M, D], STDtype.F32, ctx),
        Tensor.from_host(G1_h, [D], STDtype.F32, ctx),
        EPS, ctx,
    )
    var d_x_norm = nb1.d_x.to_host(ctx)
    var dg1 = nb1.d_g.to_host(ctx)
    # RESIDUAL #1, x's OTHER branch: d_x = (norm path) + (residual path d_r1).
    var dx_h = add_lists(d_x_norm, d_r1)     # THE make-or-break accumulation

    # ── ORACLE (b): central finite-difference on the Mojo forward ──
    var eps: Float32 = 1e-3
    var fd_dx = List[Float32]()
    for i in range(M * D):
        var xp = X_h.copy()
        var xm = X_h.copy()
        xp[i] = X_h[i] + eps
        xm[i] = X_h[i] - eps
        var lp = forward_loss(xp, G1_h, G2_h, WQ_h, WK_h, WV_h, WO_h, WG_h, WU_h, WD_h, TARGET_h, ctx)
        var lm = forward_loss(xm, G1_h, G2_h, WQ_h, WK_h, WV_h, WO_h, WG_h, WU_h, WD_h, TARGET_h, ctx)
        fd_dx.append((lp - lm) / (2.0 * eps))
    var fd_dWo = List[Float32]()
    for i in range(D * D):
        var wp = WO_h.copy()
        var wm = WO_h.copy()
        wp[i] = WO_h[i] + eps
        wm[i] = WO_h[i] - eps
        var lp = forward_loss(X_h, G1_h, G2_h, WQ_h, WK_h, WV_h, wp, WG_h, WU_h, WD_h, TARGET_h, ctx)
        var lm = forward_loss(X_h, G1_h, G2_h, WQ_h, WK_h, WV_h, wm, WG_h, WU_h, WD_h, TARGET_h, ctx)
        fd_dWo.append((lp - lm) / (2.0 * eps))

    # ── GATES ──
    var harness = ParityHarness()
    var cos_dx_torch = harness.compare_host(dx_h, REF_DX).cos
    var cos_dx_fd = harness.compare_host(dx_h, fd_dx).cos
    var cos_dWq = harness.compare_host(dWq, REF_DWQ).cos
    var cos_dWo_torch = harness.compare_host(dWo, REF_DWO).cos
    var cos_dWo_fd = harness.compare_host(dWo, fd_dWo).cos
    var cos_dWg = harness.compare_host(dWg, REF_DWG).cos
    var cos_dWd = harness.compare_host(dWd, REF_DWD).cos
    var cos_dg1 = harness.compare_host(dg1, REF_DG1).cos
    var cos_dg2 = harness.compare_host(dg2, REF_DG2).cos
    var cos_fd_torch_dx = harness.compare_host(fd_dx, REF_DX).cos

    print("")
    print("---- d_x (input grad; SUM of norm-path + residual-path) ----")
    print("  cos(chained, torch)       =", cos_dx_torch)
    print("  cos(chained, finite-diff) =", cos_dx_fd)
    print("---- weight grads vs torch ----")
    print("  dWq (deepest, behind sdpa+norm) =", cos_dWq)
    print("  dWo (behind residual #1)        =", cos_dWo_torch, " fd:", cos_dWo_fd)
    print("  dWg (mlp gate, behind swiglu)   =", cos_dWg)
    print("  dWd (mlp down)                  =", cos_dWd)
    print("---- gain grads vs torch ----")
    print("  dg1 =", cos_dg1, "  dg2 =", cos_dg2)
    print("---- oracle cross-check (finite-diff vs torch, d_x) ----")
    print("  dx:", cos_fd_torch_dx)

    print("")
    var pass_dx = (cos_dx_torch >= 0.999) and (cos_dx_fd >= 0.99)
    var pass_w = (
        (cos_dWq >= 0.999) and (cos_dWo_torch >= 0.999)
        and (cos_dWg >= 0.999) and (cos_dWd >= 0.999)
        and (cos_dg1 >= 0.999) and (cos_dg2 >= 0.999)
    )
    if pass_dx and pass_w:
        print("VERDICT: BLOCK COMPOSITION SOUND")
        print("  (both residual accumulations + q/k/v branch-sum + every grad-handoff correct)")
    else:
        print("VERDICT: BLOCK COMPOSITION BUG")
        if not pass_dx:
            print("  -> d_x disagrees (torch", cos_dx_torch, " fd", cos_dx_fd, ")")
            print("     d_x = d_x_norm + d_r1; a residual-accum drop shows up HERE first")
        if cos_dWq < 0.999:
            print("  -> dWq wrong: defect at/under sdpa_backward or h1 q/k/v branch-sum")
        if cos_dWo_torch < 0.999:
            print("  -> dWo wrong: defect at/under residual#1 accumulation into d_r1")
        if cos_dWg < 0.999:
            print("  -> dWg wrong: defect at/under swiglu_backward or h2 gate/up branch-sum")
        if cos_dWd < 0.999:
            print("  -> dWd wrong: defect at mlp-down linear_backward or mse/residual#2 split")
        if cos_dg1 < 0.999 or cos_dg2 < 0.999:
            print("  -> rms_norm_backward gain-grad handoff wrong (dg1/dg2)")
'''

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "block_composed_parity.mojo")
with open(OUT, "w") as f:
    f.write(MOJO)
print("# wrote " + OUT)
print(f"# forward loss (torch f64) = {LOSS!r}")
print("# REF_DX[:4] =", [round(float(v), 6) for v in dx.reshape(-1)[:4].tolist()])
