# sdpa_math_parity.mojo — GPU verification of the math-mode SDPA path.
#
# Three gates (cos >= 0.999):
#   1. math == flash at Dh=64  — same q/k/v/zero-mask through BOTH paths
#      (_sdpa_math vs _sdpa_flash). Proves math-mode is correct where flash also
#      compiles & works on this GPU.
#   2. math @ Dh=128 (encoder shape B1,S8,H32,Dh128) vs numpy softmax-attn ref.
#   3. math @ Dh=512 (VAE mid-attn B1,S64,H1,Dh512) vs numpy ref.
#
# Inputs are generated by the SAME deterministic formula the numpy oracle uses
# (sdpa_math_oracle.py gen_qkv); only the reference OUTPUT is read from
# sdpa_math_ref.txt. Run the oracle first, then:
#   pixi run mojo run -I . serenitymojo/ops/parity/sdpa_math_parity.mojo

from std.math import sqrt
from std.gpu.host import DeviceContext
from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.parity import ParityHarness, ParityResult
from serenitymojo.ops.attention import sdpa, _sdpa_math, _sdpa_flash
from serenitymojo.io.ffi import sys_open, sys_close, sys_pread, file_size, O_RDONLY
from std.memory import alloc


comptime REF_PATH = (
    "/home/alex/mojodiffusion/serenitymojo/ops/parity/sdpa_math_ref.txt"
)


# Deterministic BSHD q/k/v fills — MUST match sdpa_math_oracle.py gen_qkv.
def _fill_q(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for i in range(n):
        out.append((Float32((i * 7) % 13) - 6.0) * 0.05)
    return out^


def _fill_k(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for i in range(n):
        out.append((Float32((i * 5) % 11) - 5.0) * 0.05)
    return out^


def _fill_v(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for i in range(n):
        out.append((Float32((i * 3) % 9) - 4.0) * 0.05)
    return out^


def _zeros(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for _ in range(n):
        out.append(Float32(0.0))
    return out^


def _bshd(B: Int, S: Int, H: Int, Dh: Int) -> List[Int]:
    var s = List[Int]()
    s.append(B); s.append(S); s.append(H); s.append(Dh)
    return s^


def _mask_shape(B: Int, H: Int, S: Int) -> List[Int]:
    var s = List[Int]()
    s.append(B); s.append(H); s.append(S); s.append(S)
    return s^


# ── read one tagged space-separated float line from the ref file ─────────────
def _read_ref(tag: String) raises -> List[Float32]:
    var fd = sys_open(String(REF_PATH), O_RDONLY)
    if fd < 0:
        raise Error(String("cannot open ref: ") + String(REF_PATH))
    var n = file_size(fd)
    if n <= 0:
        _ = sys_close(fd)
        raise Error("empty ref file")
    var buf = alloc[UInt8](n)
    var done = 0
    while done < n:
        var got = sys_pread(fd, buf + done, n - done, done)
        if got <= 0:
            break
        done += got
    _ = sys_close(fd)

    # Scan lines; find the one starting with "<tag> ".
    var prefix = tag + " "
    var pl = prefix.byte_length()
    var out = List[Float32]()
    var i = 0
    while i < done:
        var le = i
        while le < done and Int(buf[le]) != 0x0A:  # newline
            le += 1
        # does this line start with prefix?
        var is_match = (le - i) > pl
        if is_match:
            for j in range(pl):
                if Int(buf[i + j]) != ord(prefix[byte=j]):
                    is_match = False
                    break
        if is_match:
            # parse space-separated floats after the prefix
            var p = i + pl
            while p < le:
                var c = Int(buf[p])
                if c == 0x20:  # space
                    p += 1
                    continue
                var ne = p
                while ne < le and Int(buf[ne]) != 0x20:
                    ne += 1
                var chars = List[UInt8]()
                for q in range(p, ne):
                    chars.append(buf[q])
                var s = String(from_utf8=chars)
                out.append(Float32(atof(s)))
                p = ne + 1
            buf.free()
            return out^
        i = le + 1
    buf.free()
    raise Error(String("ref tag not found: ") + tag)


def main() raises:
    var ctx = DeviceContext()
    var h = ParityHarness()
    var all_pass = True

    # ── Gate 1: math == flash at Dh=64 ───────────────────────────────────────
    comptime B1 = 1
    comptime S1 = 8
    comptime H1 = 8
    comptime Dh1 = 64
    var n1 = B1 * S1 * H1 * Dh1
    var mn1 = B1 * H1 * S1 * S1
    var scale1 = Float32(1.0) / sqrt(Float32(Dh1))

    var flash_out = _sdpa_flash[B1, S1, H1, Dh1](
        Tensor.from_host(_fill_q(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_fill_k(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_fill_v(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_zeros(mn1), _mask_shape(B1, H1, S1), STDtype.F32, ctx),
        scale1, ctx,
    )
    var math_out = _sdpa_math[B1, S1, H1, Dh1](
        Tensor.from_host(_fill_q(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_fill_k(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_fill_v(n1), _bshd(B1, S1, H1, Dh1), STDtype.F32, ctx),
        Tensor.from_host(_zeros(mn1), _mask_shape(B1, H1, S1), STDtype.F32, ctx),
        scale1, ctx,
    )
    var flash_h = flash_out.to_host(ctx)
    var math_h = math_out.to_host(ctx)
    var r1 = h.compare_host(math_h, flash_h)
    print("1) math vs flash @Dh=64 :", r1)
    all_pass = all_pass and r1.passed

    # ── Gate 2: math @ Dh=128 vs numpy ───────────────────────────────────────
    comptime B2 = 1
    comptime S2 = 8
    comptime H2 = 32
    comptime Dh2 = 128
    var n2 = B2 * S2 * H2 * Dh2
    var mn2 = B2 * H2 * S2 * S2
    var scale2 = Float32(1.0) / sqrt(Float32(Dh2))
    var out2 = sdpa[B2, S2, H2, Dh2](
        Tensor.from_host(_fill_q(n2), _bshd(B2, S2, H2, Dh2), STDtype.F32, ctx),
        Tensor.from_host(_fill_k(n2), _bshd(B2, S2, H2, Dh2), STDtype.F32, ctx),
        Tensor.from_host(_fill_v(n2), _bshd(B2, S2, H2, Dh2), STDtype.F32, ctx),
        Tensor.from_host(_zeros(mn2), _mask_shape(B2, H2, S2), STDtype.F32, ctx),
        scale2, ctx,
    )
    var ref2 = _read_ref(String("dh128"))
    var r2 = h.compare(out2, ref2, ctx)
    print("2) math @Dh=128 vs numpy:", r2)
    all_pass = all_pass and r2.passed

    # ── Gate 3: math @ Dh=512 vs numpy ───────────────────────────────────────
    comptime B3 = 1
    comptime S3 = 64
    comptime H3 = 1
    comptime Dh3 = 512
    var n3 = B3 * S3 * H3 * Dh3
    var mn3 = B3 * H3 * S3 * S3
    var scale3 = Float32(1.0) / sqrt(Float32(Dh3))
    var out3 = sdpa[B3, S3, H3, Dh3](
        Tensor.from_host(_fill_q(n3), _bshd(B3, S3, H3, Dh3), STDtype.F32, ctx),
        Tensor.from_host(_fill_k(n3), _bshd(B3, S3, H3, Dh3), STDtype.F32, ctx),
        Tensor.from_host(_fill_v(n3), _bshd(B3, S3, H3, Dh3), STDtype.F32, ctx),
        Tensor.from_host(_zeros(mn3), _mask_shape(B3, H3, S3), STDtype.F32, ctx),
        scale3, ctx,
    )
    var ref3 = _read_ref(String("dh512"))
    var r3 = h.compare(out3, ref3, ctx)
    print("3) math @Dh=512 vs numpy:", r3)
    all_pass = all_pass and r3.passed

    print("")
    if all_pass:
        print("ALL SDPA MATH-MODE GATES PASSED (cos >= 0.999)")
    else:
        print("SDPA MATH-MODE PARITY FAILURE")
        raise Error("sdpa_math_parity gate failed")
