#!/usr/bin/env python3
# sdpa_math_oracle.py — numpy softmax-attention reference for the math-mode SDPA
# verification (Dh=128 encoder shape + Dh=512 VAE mid-attn shape).
#
# Inputs are generated by a DETERMINISTIC closed formula (NOT random) so the
# Mojo driver can reproduce the exact same q/k/v on-device without reading an
# input file — only the reference OUTPUT is read back. The formulas below MUST
# match serenitymojo/ops/parity/sdpa_math_parity.mojo verbatim.
#
# Layout: BSHD [B,S,H,Dh] for q/k/v, mask [B,H,S,S] (here all zeros = full attn).
# Reference math (PyTorch "math" backend, full non-causal):
#   scores[b,h,i,j] = scale * (Q[b,i,h,:] . K[b,j,h,:]) + mask[b,h,i,j]
#   P = softmax_j(scores);  out[b,i,h,:] = sum_j P[b,h,i,j] * V[b,j,h,:]
#
# Emits one line per case: "<tag> <v0> <v1> ... <vN-1>" (flat row-major BSHD out).
# Run: pixi run python serenitymojo/ops/parity/sdpa_math_oracle.py

import numpy as np
import os

OUT = os.path.join(os.path.dirname(__file__), "sdpa_math_ref.txt")


def gen_qkv(B, S, H, Dh):
    """Deterministic BSHD q/k/v. Must match the Mojo driver's _fill()."""
    n = B * S * H * Dh
    q = np.empty(n, np.float64)
    k = np.empty(n, np.float64)
    v = np.empty(n, np.float64)
    for i in range(n):
        q[i] = (float((i * 7) % 13) - 6.0) * 0.05
        k[i] = (float((i * 5) % 11) - 5.0) * 0.05
        v[i] = (float((i * 3) % 9) - 4.0) * 0.05
    return (q.reshape(B, S, H, Dh),
            k.reshape(B, S, H, Dh),
            v.reshape(B, S, H, Dh))


def sdpa_ref(B, S, H, Dh, scale):
    q, k, v = gen_qkv(B, S, H, Dh)
    out = np.empty((B, S, H, Dh), np.float64)
    for b in range(B):
        for h in range(H):
            Q = q[b, :, h, :]          # [S, Dh]
            K = k[b, :, h, :]          # [S, Dh]
            V = v[b, :, h, :]          # [S, Dh]
            scores = scale * (Q @ K.T)  # [S, S] (mask = 0)
            scores -= scores.max(axis=1, keepdims=True)
            p = np.exp(scores)
            p /= p.sum(axis=1, keepdims=True)
            out[b, :, h, :] = p @ V    # [S, Dh]
    return out.reshape(-1)


def main():
    lines = []

    # Dh=128 encoder shape (GQA already expanded -> H=32 heads).
    B, S, H, Dh = 1, 8, 32, 128
    scale = 1.0 / np.sqrt(Dh)
    o = sdpa_ref(B, S, H, Dh, scale)
    lines.append("dh128 " + " ".join(f"{x:.8f}" for x in o.tolist()))

    # Dh=512 VAE mid-attn shape (single head).
    B, S, H, Dh = 1, 64, 1, 512
    scale = 1.0 / np.sqrt(Dh)
    o = sdpa_ref(B, S, H, Dh, scale)
    lines.append("dh512 " + " ".join(f"{x:.8f}" for x in o.tolist()))

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT)
    print("dh128 numel =", 1 * 8 * 32 * 128)
    print("dh512 numel =", 1 * 64 * 1 * 512)


if __name__ == "__main__":
    main()
