# serenitymojo/training/train_ernie_real.mojo
#
# ERNIE-Image REAL LoRA training loop (pure Mojo). TRANSLATION of the working
# Rust trainer:
#   EriDiffusion-v2/crates/eridiffusion-cli/src/bin/train_ernie.rs
#
# Pipeline per step (mirrors train_ernie.rs:853-1130 + BaseErnieSetup.py predict):
#   1. Load a cached sample produced by prepare_ernie.rs:
#        latent          [1,128,32,32]  (read back as BF16 runtime carrier)
#        text_embedding  [1,512,3072]   (read back as BF16 runtime carrier)
#        text_real_len   [1]                (real token count, pre-pad)
#   2. latent -> img_tokens [N_IMG,128]  (NCHW->NHWC pack; N_IMG = 32*32 = 1024)
#      text   -> txt_tokens [N_TXT,3072] (fixed comptime trim to N_TXT rows of the cache)
#   3. Sample sigma per LOGIT_NORMAL(bias=0,scale=1); shift=1 -> identity (train_ernie.rs:904).
#        sigma_idx = floor(logit_normal * 1000) in [0,999];  sigma = (idx+1)/1000.
#        noisy  = noise*sigma + latent*(1-sigma)             (flow-match; rectified flow)
#        target = noise - latent                             (train_ernie.rs:949)
#   4. timestep fed to the DiT = sigma_idx (INTEGER-valued; train_ernie.rs:956 — NOT /1000).
#   5. Build the shared-AdaLN source ONCE from the resident base weights + the timestep
#        (the deferred E2/E5 link): c = time_embed(sigma_idx);
#        mv = chunk6(silu(c)@adaLN_modulation.1 + bias);
#        [f_scale,f_shift] = chunk2(c@final_norm.linear + bias).
#   6. ernie_stack_lora_forward_resident_device -> pred [N_IMG,128]  (BF16 block-resident path).
#   7. loss = mean MSE(pred, target) in F32;  d_loss = (2/N)*(pred - target).
#   8. ernie_stack_lora_backward_resident_device -> LoRA d_A/d_B for all 7*36 adapters.
#   9. host global-L2-norm clip (max_norm = 1.0; train_ernie.rs:1072) -> ernie_lora_adamw_step.
#  10. save_ernie_lora at the end (PEFT/ai-toolkit keys, inference-loadable).
#
# Per-step line (stdout):
#   [Ernie-lora] step k/total | epoch e/E | loss ... | grad_norm ... | ...s/step | elapsed ... | ETA ...
#
# WHY BF16-RESIDENT: 36 F32 blocks ~= 31 GB > 24 GB 3090, but ERNIE's released
# block matrices are BF16 on disk. Keeping large block matrices BF16 and only
# norm vectors F32 fits the local 3090 target and removes per-step block reloads.
#
# The train loop consumes the existing BoxJana ERNIE cache, but validation prompt
# sidecars are generated by the pure-Mojo Mistral3B encoder:
#   pipeline/ernie_precache_sample_prompts.mojo
#
# Run (SEPARATE command, after build):
#   cd /home/alex/mojodiffusion
#   rm -f serenitymojo.mojopkg
#   pixi run mojo build -I . -Xlinker -lm \
#       serenitymojo/training/train_ernie_real.mojo -o /tmp/train_ernie_real
#   /tmp/train_ernie_real

from std.sys import argv
from max.gpu.host import DeviceContext
from std.collections import List, Optional
from std.math import sqrt, log as flog, exp as fexp, isfinite, sin as fsin, cos as fcos
from std.memory import ArcPointer
from std.time import perf_counter

from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.io.safetensors import SafeTensors
from serenitymojo.io.ffi import sys_system
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.training.klein_dataset import (
    load_cache_tensor, list_sorted_safetensors, cache_has_key, cache_tensor_dims,
)
from serenitymojo.ops.linear import linear
from serenitymojo.ops.activations import silu
from serenitymojo.ops.embeddings import timestep_embedding_sin_first

from serenitymojo.models.dit.ernie_image import build_ernie_rope_tables
from serenitymojo.models.ernie.weights import (
    ErnieBlockWeights, ErnieStackBase,
    load_ernie_stack_base, load_ernie_all_blocks_bf16_normf32,
)
from serenitymojo.models.ernie.block import ErnieModVecs
from serenitymojo.models.ernie.lora_block import ERNIE_SLOTS
from serenitymojo.models.ernie.ernie_stack_lora import (
    ErnieLoraSet, ErnieLoraGrads, build_ernie_lora_set,
    ernie_lora_set_to_device,
    ernie_stack_lora_forward_resident_device, ernie_stack_lora_backward_resident_device,
    ErnieStackForwardB2,
    ernie_stack_lora_forward_resident_device_b2,
    ernie_stack_lora_backward_resident_device_b2,
    ernie_stack_direct_dora_forward_resident_device,
    ernie_stack_direct_dora_backward_resident_device,
    ernie_stack_direct_oft_forward_resident_device,
    ernie_stack_direct_oft_backward_resident_device,
    ernie_lora_adamw_step, save_ernie_lora,
    ernie_lora_adamw_state_init, ernie_lora_adamw_step_resident,
    save_ernie_lora_state, load_ernie_lora_state,
)
from serenitymojo.models.ernie.ernie_lycoris_stack import (
    ERNIE_LYCORIS_TGT_ATTN,
    ErnieLoKrSet, empty_ernie_lokr_set, build_ernie_lokr_set,
    ernie_lokr_carrier_set, ernie_lokr_carrier_total_bytes,
    ernie_lokr_chain_all, ernie_lokr_adamw_step, ernie_lokr_grad_norm,
    ernie_lokr_clip_grads, ernie_lokr_zero_leg_l1, save_ernie_lokr,
    ErnieLoHaSet, empty_ernie_loha_set, build_ernie_loha_set,
    ernie_loha_carrier_set, ernie_loha_carrier_total_bytes,
    ernie_loha_chain_all, ernie_loha_adamw_step, ernie_loha_grad_norm,
    ernie_loha_clip_grads, ernie_loha_zero_leg_l1, save_ernie_loha,
    ernie_full_delta_carrier_bytes_estimate, ernie_full_delta_preflight,
    ErnieDoRASet, empty_ernie_dora_set, build_ernie_dora_set_from_checkpoint,
    ernie_dora_carrier_set, ernie_dora_carrier_total_bytes, ernie_dora_preflight,
    ernie_dora_chain_all, ernie_dora_adamw_step, ernie_dora_grad_norm,
    ernie_dora_clip_grads, ernie_dora_zero_leg_l1, save_ernie_dora,
    ErnieOFTSet, empty_ernie_oft_set, build_ernie_oft_set_from_checkpoint,
    ernie_oft_carrier_set, ernie_oft_carrier_total_bytes, ernie_oft_preflight,
    ernie_oft_chain_all, ernie_oft_adamw_step, ernie_oft_grad_norm,
    ernie_oft_clip_grads, ernie_oft_vec_l1, save_ernie_oft,
    empty_ernie_direct_dora_set, empty_ernie_direct_oft_set,
    ernie_direct_dense_carrier_bytes,
    ernie_direct_dora_preflight, ernie_direct_oft_preflight,
    build_ernie_direct_dora_set_from_blocks, build_ernie_direct_oft_set,
    ernie_direct_dora_trainable_bytes, ernie_direct_oft_trainable_bytes,
    save_ernie_direct_dora, save_ernie_direct_oft,
)
from serenitymojo.io.train_config_reader import read_model_config
from serenitymojo.training.train_config import (
    TrainConfig,
    TRAIN_ADAPTER_ALGO_LORA, TRAIN_ADAPTER_ALGO_FULL,
    TRAIN_ADAPTER_ALGO_LOCON, TRAIN_ADAPTER_ALGO_LOHA,
    TRAIN_ADAPTER_ALGO_DORA, TRAIN_ADAPTER_ALGO_LOKR,
    TRAIN_ADAPTER_ALGO_OFT, TRAIN_ADAPTER_ALGO_BOFT,
)
from serenitymojo.training.adapter_algo_policy import adapter_algo_name
from serenitymojo.training.lokr_stack import LOKR_CARRIER_MAX_DEVICE_BYTES
from serenitymojo.training.flat_direct_lycoris_stack import (
    FlatDirectDoRASet, FlatDirectOFTSet,
    flat_direct_dora_grad_norm, flat_direct_dora_clip_grads,
    flat_direct_dora_adamw_step, flat_direct_dora_zero_leg_l1,
    flat_direct_oft_grad_norm, flat_direct_oft_clip_grads,
    flat_direct_oft_adamw_step, flat_direct_oft_vec_l1,
)
from serenitymojo.training.serenity_trainer_cache_preflight import (
    create_serenity_trainer_cache_preflight_plan,
    validate_serenity_trainer_cache_preflight_plan,
)
from serenitymojo.training.sample_prompt_config import (
    SamplePrompt, SamplePromptConfig, SampleCadence,
    read_sample_prompt_config, read_sample_cadence_config,
    validate_step_sample_cadence, should_sample_completed_step,
    sample_time_unit_name,
    SAMPLE_UNIT_STEP, SAMPLE_UNIT_NEVER,
)
from serenitymojo.training.serenity_trainer_train_loop_policy import (
    SERENITY_GRAD_POLICY_ON_OR_OFF,
    serenity_cache_dir_from_train_config,
    serenity_fixed_output_lora_path_from_train_config,
    serenity_lr_for_optimizer_step,
    serenity_sample_cadence_from_train_config,
    serenity_sampling_enabled_checked,
    serenity_should_save_before_sample,
    serenity_should_save_checkpoint,
    serenity_state_path_for_lora,
    serenity_step_lora_path,
    validate_serenity_gradient_checkpointing_policy,
    validate_serenity_train_math_policy,
)
from serenitymojo.training.lora_adamw_plain_fused import (
    fused_lora_adamw_plain_step, LoraAdamWPlainDeviceState,
)
from serenitymojo.training.progress_display import print_trainer_progress
from serenitymojo.training.lora_ema import (
    LoraEmaState, lora_ema_track, ema_update,
    lora_ema_adapters, ema_path_for_lora,
)
from serenitymojo.training.trainer_core import (
    GradAccumWindow, trainer_prune_target_step, trainer_prune_step_checkpoint,
)
from serenitymojo.training.ernie_validation_sampler import (
    generate_ernie_lora_shift_pair, load_ernie_sample_text_tokens,
)

comptime TArc = ArcPointer[Tensor]

# ── REAL ERNIE dims (TRAINING_PLAN_ernie.md / ernie_contract.mojo) ────────────
comptime H = 32
comptime Dh = 128
comptime D = H * Dh            # 4096
comptime F = 12288             # REAL FFN hidden
comptime IN_CH = 128           # REAL latent channels
comptime TEXT_IN = 3072        # REAL Mistral hidden (text_in_dim)
comptime OUT_CH = 128          # REAL out channels
comptime NUM_LAYERS = 36       # REAL depth
comptime EPS = Float32(1e-06)
comptime ERNIE_OFT_BLOCK_SIZE = 4
comptime ERNIE_CARRIER_RUNTIME_RESERVE_BYTES = 2 * 1024 * 1024 * 1024

# GPU fused plain-AdamW for the flat LoRA adapter list (TRAINING_SPEED_AUDIT
# 2026-07-01): route the SAME host d_a/d_b grad lists through ONE
# fused_lora_adamw_plain_step launch over all 7*NUM_LAYERS adapters instead of
# the per-adapter host scalar loop (ernie_lora_adamw_step -> _lora_adamw ->
# _adamw_host_list). Identical per-element math (F32 moments, plain RNE bf16
# param writeback); host-vs-device differs only at the documented FMA
# ulp class (training/lora_adamw_plain_fused_parity.mojo bars; smoke:
# smoke/ernie_gpu_adamw_update_parity_smoke.mojo in serenity-trainer).
# False = old host loop, retained unchanged.
comptime ERNIE_GPU_ADAMW = True

# ── cache geometry: latent [1,128,32,32] -> 32x32 = 1024 image tokens ─────────
comptime IMG_H = 32
comptime IMG_W = 32
comptime N_IMG = IMG_H * IMG_W     # 1024
# Fixed comptime text trim. The cache pads text to 512 with PAD-embedding rows
# (the model was trained to see real-tokens + the trim). The observed real_len
# in this cache is <= ~256, so a 256-row trim keeps every real token plus a
# little pad — and bounds the per-block SDPA scores [H, S, S] on the 3090.
comptime N_TXT = 256
comptime S = N_IMG + N_TXT         # 1280

# ── runtime paths; recipe/cadence scalars come from CONFIG_PATH ───────────────
comptime CACHE_DIR = "/home/alex/EriDiffusion/EriDiffusion-v2/cache/boxjana_ernie_512_FIXED"
comptime NUM_TRAIN_TIMESTEPS = 1000
comptime SEED = UInt64(42)         # train_ernie.rs SEED
comptime SAVE_PATH = "/home/alex/mojodiffusion/serenitymojo/output/ernie_lora_real.safetensors"
comptime CONFIG_PATH = "/home/alex/mojodiffusion/serenitymojo/configs/ernie_image.json"
comptime SAMPLE_OUT_DIR = "/home/alex/mojodiffusion/serenitymojo/output"


# ─────────────────────────────────────────────────────────────────────────────
# cache reading: the per-sample single-tensor read, the sorted file list, and the
# header-only dims/has checks are the SHARED klein_dataset primitives
# (load_cache_tensor / list_sorted_safetensors / cache_tensor_dims / cache_has_key
# imported above). ERNIE's cache is BF16 latent + BF16 text_embedding + optional
# text_real_len; the ERNIE-specific token packing/trim stays below.
# ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
# latent [1,128,H,W] (NCHW) -> img_tokens [N_IMG, IN_CH] (NHWC, row=token, col=channel)
# Mirrors the Rust patch_embed reshape: [B,C,H,W] -> reshape [B,C,H*W] -> permute
# [B,H*W,C]. With B=1: token t (= r*W + c), channel ch -> latent[ch*H*W + t].
# ─────────────────────────────────────────────────────────────────────────────
def _latent_to_img_tokens(latent: List[BFloat16]) -> List[Float32]:
    var out = List[Float32]()
    var hw = IMG_H * IMG_W
    for t in range(hw):
        for ch in range(IN_CH):
            out.append(latent[ch * hw + t].cast[DType.float32]())
    return out^


# ── trim/pad cached text [1, T, 3072] -> [N_TXT, 3072] rows ───────────────────
def _text_to_txt_tokens(text: List[BFloat16], t_cache: Int) -> List[Float32]:
    var out = List[Float32]()
    for r in range(N_TXT):
        if r < t_cache:
            for c in range(TEXT_IN):
                out.append(text[r * TEXT_IN + c].cast[DType.float32]())
        else:
            for _c in range(TEXT_IN):
                out.append(Float32(0.0))   # beyond cache rows (unreachable; cache T=512)
    return out^


# ─────────────────────────────────────────────────────────────────────────────
# host helpers
# ─────────────────────────────────────────────────────────────────────────────
def _zeros(n: Int) -> List[Float32]:
    var o = List[Float32]()
    for _ in range(n):
        o.append(0.0)
    return o^


def _l2(h: List[Float32]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = Float64(h[i])
        s += x * x
    return s


def _abs_sum(h: List[Float32]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = h[i]
        s += Float64(x) if x >= 0.0 else Float64(-x)
    return s


def _abs_sum(h: List[BFloat16]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = h[i].cast[DType.float32]()
        s += Float64(x) if x >= 0.0 else Float64(-x)
    return s


def _scale_inplace(mut h: List[Float32], s: Float32):
    for i in range(len(h)):
        h[i] = h[i] * s


def _count_nonfinite(v: List[Float32]) -> Int:
    var bad = 0
    for i in range(len(v)):
        if not isfinite(v[i]):
            bad += 1
    return bad


struct _LossGrad(Movable):
    var loss: Float32
    var d_out: List[Float32]

    def __init__(out self, loss: Float32, var d_out: List[Float32]):
        self.loss = loss
        self.d_out = d_out^


def _mse_loss_grad(pred: List[Float32], target: List[Float32]) raises -> _LossGrad:
    if len(pred) != len(target):
        raise Error("_mse_loss_grad: pred/target length mismatch")
    var sse = Float64(0.0)
    var d_out = List[Float32]()
    var inv_n = Float32(2.0) / Float32(len(pred))
    for i in range(len(pred)):
        var diff = pred[i] - target[i]
        sse += Float64(diff) * Float64(diff)
        d_out.append(diff * inv_n)
    return _LossGrad(Float32(sse / Float64(len(pred))), d_out^)


# 0.5-scaled MSE for the TRUE batch-2 joint 2N-mean loss (mirrors krea2
# _mse_half_loss). Each per-sample loss/grad is halved; loss_b2 = half0 + half1 =
# mean(loss0, loss1) and the 0.5 grad scale turns the batch backward's SUM over the
# two row halves into the MEAN = the grad-accum=2 oracle. loss/d_out ×2 recover the
# comparable B=1 values.
def _mse_half_loss_grad(pred: List[Float32], target: List[Float32]) raises -> _LossGrad:
    if len(pred) != len(target):
        raise Error("_mse_half_loss_grad: pred/target length mismatch")
    var sse = Float64(0.0)
    var d_out = List[Float32]()
    var inv_n = Float32(1.0) / Float32(len(pred))   # = 0.5 * (2/N)
    for i in range(len(pred)):
        var diff = pred[i] - target[i]
        sse += Float64(diff) * Float64(diff)
        d_out.append(diff * inv_n)
    return _LossGrad(Float32(0.5) * Float32(sse / Float64(len(pred))), d_out^)


# ── deterministic gaussian noise (Box-Muller on a PCG stream), F32 ────────────
def _host_noise(n: Int, seed: UInt64) -> List[Float32]:
    var out = List[Float32]()
    var state = seed
    var have = False
    var spare = Float32(0.0)
    for _ in range(n):
        if have:
            out.append(spare)
            have = False
            continue
        # two uniforms in (0,1]
        state = state * 6364136223846793005 + 1442695040888963407
        var u1 = (Float32(Int(state >> 40)) + 1.0) * Float32(1.0 / 16777217.0)
        state = state * 6364136223846793005 + 1442695040888963407
        var u2 = Float32(Int(state >> 40)) * Float32(1.0 / 16777216.0)
        var r = sqrt(Float32(-2.0) * flog(u1))
        var theta = Float32(6.283185307179586) * u2
        out.append(r * fcos(theta))
        spare = r * fsin(theta)
        have = True
    return out^


# ── logit-normal timestep sample (train_ernie.rs sample_timestep_logit_normal) ─
# z ~ Normal(0,1); ln = sigmoid(z); t = ln * 1000; shift=1 -> identity.
# Returns sigma_idx in [0, 999] plus the advanced RNG state.
def _sample_sigma_idx(state0: UInt64) -> Tuple[Int, UInt64]:
    # one Box-Muller normal sample
    var state = state0
    state = state * 6364136223846793005 + 1442695040888963407
    var u1 = (Float32(Int(state >> 40)) + 1.0) * Float32(1.0 / 16777217.0)
    state = state * 6364136223846793005 + 1442695040888963407
    var u2 = Float32(Int(state >> 40)) * Float32(1.0 / 16777216.0)
    var z = sqrt(Float32(-2.0) * flog(u1)) * fcos(Float32(6.283185307179586) * u2)
    var ln = Float32(1.0) / (Float32(1.0) + fexp(-z))
    var t = ln * Float32(NUM_TRAIN_TIMESTEPS)   # shift=1 -> identity
    var idx = Int(t)                            # floor
    if idx < 0:
        idx = 0
    if idx > NUM_TRAIN_TIMESTEPS - 1:
        idx = NUM_TRAIN_TIMESTEPS - 1
    return (idx, state)


# ─────────────────────────────────────────────────────────────────────────────
# shared-AdaLN SOURCE (the deferred E2/E5 link). Built from the RESIDENT base
# weights + sigma_idx. Mirrors ernie_image.mojo time_embed/shared_adaln + the
# final-norm chunk, and ernie_image.rs:519-552. Sinusoid math is F32, then
# cast to the resident time-weight dtype before the MLP.
#   c   = linear2(silu(linear1(timestep_embedding_sin_first(idx))))
#   mv  = chunk6(silu(c) @ adaln_w + adaln_b)
#   fs  = chunk2(c @ final_norm_w + final_norm_b)  -> [f_scale, f_shift]
# Returns (mv, f_scale, f_shift). NOTE the timestep fed = sigma_idx (integer),
# matching train_ernie.rs:956 (NOT sigma*1000).
# ─────────────────────────────────────────────────────────────────────────────
def _chunk(src: List[Float32], idx: Int, width: Int) -> List[Float32]:
    var o = List[Float32]()
    var off = idx * width
    for i in range(width):
        o.append(src[off + i])
    return o^


def _shared_adaln_source(
    base: ErnieStackBase, sigma_idx: Int, ctx: DeviceContext
) raises -> Tuple[ErnieModVecs, List[Float32], List[Float32]]:
    var ts = List[Float32]()
    ts.append(Float32(sigma_idx))
    var ts_t = Tensor.from_host(ts, [1], STDtype.F32, ctx)
    var emb_in = timestep_embedding_sin_first(
        ts_t, D, ctx, 10000.0, base.te_w1[].dtype()
    )
    var h1 = linear(emb_in, base.te_w1[], Optional[Tensor](base.te_b1[].clone(ctx)), ctx)
    h1 = silu(h1, ctx)
    var c = linear(h1, base.te_w2[], Optional[Tensor](base.te_b2[].clone(ctx)), ctx)  # [1,D]

    # shared adaLN: silu(c) @ adaln_w + adaln_b -> [1, 6D]
    var sc = silu(c, ctx)
    var adaln = linear(sc, base.adaln_w[], Optional[Tensor](base.adaln_b[].clone(ctx)), ctx)
    var adaln_h = adaln.to_host(ctx)   # [6D]

    # final-norm source: c @ final_norm_w + final_norm_b -> [1, 2D]
    var fmod = linear(c, base.final_norm_w[], Optional[Tensor](base.final_norm_b[].clone(ctx)), ctx)
    var fmod_h = fmod.to_host(ctx)     # [2D]

    # chunk6 the 6D modulation in order: shift_msa,scale_msa,gate_msa,shift_mlp,scale_mlp,gate_mlp
    var mv = ErnieModVecs(
        _chunk(adaln_h, 0, D), _chunk(adaln_h, 1, D), _chunk(adaln_h, 2, D),
        _chunk(adaln_h, 3, D), _chunk(adaln_h, 4, D), _chunk(adaln_h, 5, D),
    )
    var f_scale = _chunk(fmod_h, 0, D)
    var f_shift = _chunk(fmod_h, 1, D)
    return (mv^, f_scale^, f_shift^)


# ── global L2 norm over the flat LoRA grads (clip basis) ──────────────────────
def _grad_global_norm(grads: ErnieLoraGrads) -> Float64:
    var ss = Float64(0.0)
    for i in range(len(grads.d_a)):
        ss += _l2(grads.d_a[i])
        ss += _l2(grads.d_b[i])
    return sqrt(ss)


def _clip_grads(mut grads: ErnieLoraGrads, max_norm: Float32) -> Float64:
    var gn = _grad_global_norm(grads)
    if gn <= Float64(max_norm) or gn == 0.0:
        return gn
    var s = Float32(Float64(max_norm) / gn)
    for i in range(len(grads.d_a)):
        _scale_inplace(grads.d_a[i], s)
        _scale_inplace(grads.d_b[i], s)
    return gn


# ── LoRA-B absolute-sum (across all adapters): the "is it learning?" probe ────
def _lora_b_abs_sum(set: ErnieLoraSet) -> Float64:
    var s = Float64(0.0)
    for i in range(len(set.ad)):
        s += _abs_sum(set.ad[i].b)
    return s


def _lora_b_nonzero_slots(set: ErnieLoraSet) -> Int:
    var n = 0
    for i in range(len(set.ad)):
        if _abs_sum(set.ad[i].b) > 0.0:
            n += 1
    return n


def _parse_int(s: String) -> Int:
    var out = 0
    var bytes = s.as_bytes()
    for i in range(s.byte_length()):
        out = out * 10 + Int(bytes[i] - 0x30)
    return out


def _state_path_for_lora(lora_path: String) -> String:
    return serenity_state_path_for_lora(lora_path)


def _substr(s: String, start: Int, end: Int) -> String:
    var out = String("")
    var i = 0
    for ch in s.codepoint_slices():
        if i >= start and i < end:
            out += String(ch)
        i += 1
    return out^


def _dirname(path: String) -> String:
    var last = -1
    var i = 0
    for ch in path.codepoint_slices():
        if String(ch) == String("/"):
            last = i
        i += 1
    if last <= 0:
        return String(".")
    return _substr(path, 0, last)


def _mkdir_parent(path: String):
    _ = sys_system(String("mkdir -p ") + _dirname(path))


def _step_lora_path(save_path: String, step: Int) -> String:
    return serenity_step_lora_path(save_path, step)


# Rolling checkpoint retention (audit item #4), pruned AFTER a periodic save —
# krea2's discipline, thin wrapper over the shared trainer_core machinery. Reuses
# the shared keep-count decision (trainer_prune_target_step), but builds the
# pruned path with ernie's OWN step-path helper (reference-policy naming off `save_path`,
# not krea2's workspace/stem), then removes it + its `.state.safetensors` sidecar.
# keep_default/milestone=0 ⇒ NO prune until the webui sets save_max_keep, so
# keep-all stays byte-unchanged when it is unset.
def _ernie_prune_old_checkpoints(cfg: TrainConfig, save_path: String, saved_step: Int) raises:
    var old = trainer_prune_target_step(cfg, saved_step, 0, 0)
    if old > 0:
        trainer_prune_step_checkpoint(
            _step_lora_path(save_path, old), String(".state.safetensors")
        )


def validate_ernie_train_config(cfg: TrainConfig) raises:
    if cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOCON:
        print("[Ernie-locon] network_algorithm=locon: using the linear LoRA-compatible down/up path")
    elif cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOKR:
        print("[Ernie-lokr] network_algorithm=lokr: using carrier dispatch through the LoRA stack")
    elif cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOHA:
        print("[Ernie-loha] network_algorithm=loha: using carrier dispatch through the LoRA stack")
    elif cfg.adapter_algo == TRAIN_ADAPTER_ALGO_DORA or cfg.adapter_algo == TRAIN_ADAPTER_ALGO_OFT:
        var target_mode = ERNIE_LYCORIS_TGT_ATTN if cfg.lokr_targets == ERNIE_LYCORIS_TGT_ATTN else 2
        var dense_bytes = ernie_direct_dense_carrier_bytes(
            NUM_LAYERS, D, F, cfg.lokr_targets,
        )
        if cfg.adapter_algo == TRAIN_ADAPTER_ALGO_DORA:
            var direct_bytes = ernie_direct_dora_preflight(
                NUM_LAYERS, D, F, cfg.lora_rank, target_mode,
                LOKR_CARRIER_MAX_DEVICE_BYTES,
            )
            print(
                "[Ernie-dora] network_algorithm=dora: using direct W_eff substitution",
                " dense_carrier_bytes=", dense_bytes,
                " direct_trainable_bytes=", direct_bytes,
                " budget=", LOKR_CARRIER_MAX_DEVICE_BYTES,
            )
        else:
            var direct_bytes = ernie_direct_oft_preflight(
                NUM_LAYERS, D, F, ERNIE_OFT_BLOCK_SIZE, target_mode,
                LOKR_CARRIER_MAX_DEVICE_BYTES,
            )
            print(
                "[Ernie-oft] network_algorithm=oft: using direct W_eff substitution",
                " dense_carrier_bytes=", dense_bytes,
                " direct_trainable_bytes=", direct_bytes,
                " budget=", LOKR_CARRIER_MAX_DEVICE_BYTES,
            )
    elif cfg.adapter_algo == TRAIN_ADAPTER_ALGO_BOFT:
        raise Error("ERNIE trainer: BOFT is intentionally excluded; use lora, locon, loha, lokr, dora, or oft where wired")
    elif cfg.adapter_algo == TRAIN_ADAPTER_ALGO_FULL:
        raise Error("ERNIE trainer: full finetune is not wired; supported here: lora, locon, loha, lokr, dora, oft")
    elif cfg.adapter_algo != TRAIN_ADAPTER_ALGO_LORA:
        raise Error(
            String("ERNIE trainer: network_algorithm=")
            + adapter_algo_name(cfg.adapter_algo)
            + String(" is not wired; supported here: lora, locon, loha, lokr, dora, oft")
        )
    if cfg.name != String("ernie_image"):
        raise Error(String("ERNIE trainer config requires model_type=ernie_image, got ") + cfg.name)
    if cfg.checkpoint == String(""):
        raise Error("ERNIE trainer config must set checkpoint")
    if cfg.n_heads != H:
        raise Error(String("ERNIE config num_heads ") + String(cfg.n_heads) + String(" != H ") + String(H))
    if cfg.head_dim != Dh:
        raise Error(String("ERNIE config head_dim ") + String(cfg.head_dim) + String(" != Dh ") + String(Dh))
    if cfg.d_model != D:
        raise Error(String("ERNIE config inner_dim ") + String(cfg.d_model) + String(" != D ") + String(D))
    if cfg.in_channels != IN_CH:
        raise Error(String("ERNIE config in_channels ") + String(cfg.in_channels) + String(" != IN_CH ") + String(IN_CH))
    if cfg.joint_attention_dim != TEXT_IN:
        raise Error(
            String("ERNIE config joint_attention_dim ")
            + String(cfg.joint_attention_dim) + String(" != TEXT_IN ") + String(TEXT_IN)
        )
    if cfg.out_channels != OUT_CH:
        raise Error(String("ERNIE config out_channels ") + String(cfg.out_channels) + String(" != OUT_CH ") + String(OUT_CH))
    if cfg.num_double != 0 or cfg.num_single != NUM_LAYERS:
        raise Error(
            String("ERNIE trainer requires 0 double-stream blocks and ")
            + String(NUM_LAYERS) + String(" single blocks; got double=")
            + String(cfg.num_double) + String(" single=") + String(cfg.num_single)
        )
    if cfg.mlp_hidden != F:
        raise Error(String("ERNIE config mlp_hidden ") + String(cfg.mlp_hidden) + String(" != F ") + String(F))
    if cfg.timestep_dim != D:
        raise Error(String("ERNIE config timestep_dim ") + String(cfg.timestep_dim) + String(" != D ") + String(D))
    if cfg.timestep_shift != Float32(1.0):
        raise Error("ERNIE trainer currently implements timestep_shift=1.0 only")
    if cfg.lora_rank <= 0:
        raise Error("ERNIE trainer config requires lora_rank > 0")
    if cfg.lora_alpha <= Float32(0.0):
        raise Error("ERNIE trainer config requires lora_alpha > 0")
    if cfg.lr <= Float32(0.0):
        raise Error("ERNIE trainer config requires learning_rate > 0")
    if cfg.max_grad_norm <= Float32(0.0):
        raise Error("ERNIE trainer config requires max_grad_norm > 0")
    validate_serenity_train_math_policy(cfg, String("ERNIE trainer"))
    if cfg.max_steps <= 0:
        raise Error("ERNIE trainer config requires max_steps > 0")
    if cfg.save_every < 0:
        raise Error("ERNIE trainer config requires save_every >= 0")
    validate_serenity_gradient_checkpointing_policy(
        cfg, String("ERNIE trainer"), SERENITY_GRAD_POLICY_ON_OR_OFF
    )


def ernie_sample_cadence_from_train_config(
    cfg_path: String, cfg: TrainConfig,
) raises -> SampleCadence:
    return serenity_sample_cadence_from_train_config(cfg_path, cfg)


def ernie_sampling_enabled(cadence: SampleCadence) raises -> Bool:
    return serenity_sampling_enabled_checked(cadence)


def ernie_should_save_checkpoint(cfg: TrainConfig, completed_step: Int) -> Bool:
    return serenity_should_save_checkpoint(cfg, completed_step)


def ernie_should_save_before_sample(
    cadence: SampleCadence, completed_step: Int, saved_this_step: Bool,
) raises -> Bool:
    return serenity_should_save_before_sample(cadence, completed_step, saved_this_step)


def _sample_png_path(step: Int, label: String) -> String:
    return (
        String(SAMPLE_OUT_DIR) + String("/ernie_sample_step") + String(step)
        + String("_") + label + String(".png")
    )


def _validate_image_sample_prompt(p: SamplePrompt) raises:
    if p.frames != 1:
        raise Error(String("ERNIE image sampler expects frames=1 for ") + p.label)
    if p.width < 1024 or p.height < 1024:
        raise Error(
            String("ERNIE sample prompt ") + p.label
            + String(" is ") + String(p.width) + String("x") + String(p.height)
            + String("; image validation samples must be 1024x1024 or larger")
        )


def _save_lora_and_state(
    lora: ErnieLoraSet, lora_path: String, step: Int, ctx: DeviceContext
) raises:
    _mkdir_parent(lora_path)
    var npairs = save_ernie_lora(lora, lora_path, ctx)
    print("[Ernie-lora] save step=", step, " path=", lora_path, " pairs=", npairs)
    var state_path = _state_path_for_lora(lora_path)
    var nstate = save_ernie_lora_state(lora, state_path, ctx)
    print("[Ernie-lora] save_state step=", step, " path=", state_path, " pairs=", nstate)


# T1.B: save the EMA shadow set as the *_ema.safetensors sibling of a plain-LoRA
# checkpoint (SimpleTuner copy_to analog — lora_ema.mojo lora_ema_adapters
# returns bf16-rounded shadows over the LIVE set's shapes). Only reached when
# cfg.ema_enabled on the plain arm; flag-off / LyCORIS leaves this uncalled.
def _save_ernie_lora_ema(
    ema: LoraEmaState, lora: ErnieLoraSet, lora_path: String, ctx: DeviceContext
) raises:
    var ema_set = lora.copy()
    var shadow_ads = lora_ema_adapters(ema, lora.ad, 0, len(lora.ad), 0)
    for i in range(len(shadow_ads)):
        ema_set.ad[i] = shadow_ads[i].copy()
    var ema_path = ema_path_for_lora(lora_path)
    _ = save_ernie_lora(ema_set, ema_path, ctx)
    print("[Ernie-lora] save_ema path=", ema_path)


def _require_ernie_carrier_runtime_vram(
    label: String, carrier_bytes: Int, free_after_blocks: UInt,
) raises:
    var free_bytes = Int(free_after_blocks)
    var need = carrier_bytes + ERNIE_CARRIER_RUNTIME_RESERVE_BYTES
    if need > free_bytes:
        raise Error(
            String("ERNIE ") + label
            + String(": full-delta carrier needs ")
            + String(carrier_bytes)
            + String(" device bytes plus ")
            + String(ERNIE_CARRIER_RUNTIME_RESERVE_BYTES)
            + String(" bytes runtime reserve, but only ")
            + String(free_bytes)
            + String(" bytes were free after resident BF16 block load. This does not meet the 24 GB target; use LoKr/LoHa/LoRA or lower DoRA/OFT to a direct W_eff path.")
        )


def _save_adapter_for_algo(
    lora: ErnieLoraSet,
    lokr_masters: ErnieLoKrSet,
    loha_masters: ErnieLoHaSet,
    dora_masters: ErnieDoRASet,
    oft_masters: ErnieOFTSet,
    direct_dora: FlatDirectDoRASet,
    direct_oft: FlatDirectOFTSet,
    lokr_active: Bool,
    loha_active: Bool,
    dora_active: Bool,
    oft_active: Bool,
    lora_path: String,
    step: Int,
    ctx: DeviceContext,
) raises:
    _mkdir_parent(lora_path)
    if lokr_active:
        var npairs = save_ernie_lokr(lokr_masters, lora_path, ctx)
        print("[Ernie-lokr] save step=", step, " path=", lora_path, " modules=", npairs)
    elif loha_active:
        var npairs = save_ernie_loha(loha_masters, lora_path, ctx)
        print("[Ernie-loha] save step=", step, " path=", lora_path, " modules=", npairs)
    elif dora_active:
        var npairs = save_ernie_direct_dora(direct_dora, lora_path, ctx)
        print("[Ernie-dora-direct] save step=", step, " path=", lora_path, " modules=", npairs)
    elif oft_active:
        var npairs = save_ernie_direct_oft(direct_oft, lora_path, ctx)
        print("[Ernie-oft-direct] save step=", step, " path=", lora_path, " modules=", npairs)
    else:
        _save_lora_and_state(lora, lora_path, step, ctx)


def _sample_ernie_prompt(
    base: ErnieStackBase,
    blocks: List[ErnieBlockWeights],
    baseline_lora: ErnieLoraSet,
    live_lora: ErnieLoraSet,
    p: SamplePrompt,
    step: Int,
    ctx: DeviceContext,
) raises -> Float32:
    _validate_image_sample_prompt(p)
    var txt = load_ernie_sample_text_tokens(p.caps_pos, ctx)
    var out_png = _sample_png_path(step, p.label)
    var diff = generate_ernie_lora_shift_pair(
        base, blocks, baseline_lora, live_lora, txt^, out_png,
        p.width, p.height, p.steps, p.seed, ctx,
    )
    print(
        "[Ernie-lora] sample step=", step, " label=", p.label,
        " size=", p.width, "x", p.height, " path=", out_png,
        " pixel_l1=", diff,
    )
    return diff


def _sample_ernie_prompts(
    base: ErnieStackBase,
    blocks: List[ErnieBlockWeights],
    baseline_lora: ErnieLoraSet,
    live_lora: ErnieLoraSet,
    cfg: SamplePromptConfig,
    step: Int,
    ctx: DeviceContext,
) raises:
    for i in range(len(cfg.prompts)):
        _ = _sample_ernie_prompt(
            base, blocks, baseline_lora, live_lora, cfg.prompts[i].copy(), step, ctx
        )


def main() raises:
    var args = argv()
    var cfg_path = String(CONFIG_PATH)
    var arg_base = 1
    if len(args) >= 2:
        var first = String(args[1])
        if first.endswith(String(".json")):
            cfg_path = first.copy()
            arg_base = 2

    var run_steps = -1
    var mode = String("train")
    if len(args) > arg_base:
        var a1 = String(args[arg_base])
        if a1 == String("resume_smoke") or a1 == String("smoke_resume"):
            mode = String("resume_smoke")
            run_steps = 25
        else:
            run_steps = _parse_int(a1)

    var train_cfg = read_model_config(cfg_path)
    var save_path = serenity_fixed_output_lora_path_from_train_config(
        train_cfg, String(SAVE_PATH)
    )
    if len(args) > arg_base + 1:
        save_path = String(args[arg_base + 1])

    var cache_dir = serenity_cache_dir_from_train_config(train_cfg, String(CACHE_DIR))
    if len(args) > arg_base + 2:
        cache_dir = String(args[arg_base + 2])

    if len(args) > arg_base + 3:
        mode = String(args[arg_base + 3])

    validate_ernie_train_config(train_cfg)
    var cache_preflight = create_serenity_trainer_cache_preflight_plan(train_cfg)
    validate_serenity_trainer_cache_preflight_plan(cache_preflight)
    if run_steps < 0:
        run_steps = train_cfg.max_steps
    if mode == String("resume_smoke") and run_steps < 25:
        run_steps = 25
    if run_steps < 1:
        raise Error("run_steps must be >= 1")
    if (
        mode == String("resume_smoke")
        and (
            train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOKR
            or train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOHA
            or train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_DORA
            or train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_OFT
        )
    ):
        raise Error("ERNIE LyCORIS resume_smoke is not wired; carrier runs save adapter weights but no master optimizer-state sidecar")

    var sample_cadence = ernie_sample_cadence_from_train_config(cfg_path, train_cfg)
    var sample_enabled = ernie_sampling_enabled(sample_cadence)
    var sample_cfg = SamplePromptConfig()
    if train_cfg.only_cache:
        print("[Ernie-lora] only_cache requested; no train steps will run in this trainer")
        return
    if sample_enabled:
        if sample_cadence.sample_definition_file_name == String(""):
            raise Error("ERNIE trainer sampling requires validation_prompts_file or sample_definition_file_name")
        if (
            train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_DORA
            or train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_OFT
        ):
            raise Error("ERNIE direct DoRA/OFT sample-during-training is not wired; disable sample cadence for this runtime gate")
        sample_cfg = read_sample_prompt_config(sample_cadence.sample_definition_file_name)
        if len(sample_cfg.prompts) == 0:
            raise Error("ERNIE trainer requires at least one validation prompt when sampling is enabled")
        _ = sys_system(String("mkdir -p ") + String(SAMPLE_OUT_DIR))

    var ctx = DeviceContext()

    print("==== ERNIE REAL LoRA training loop (pure Mojo) ====")
    print("  D=", D, " H=", H, " Dh=", Dh, " F=", F, " NUM_LAYERS=", NUM_LAYERS)
    print("  N_IMG=", N_IMG, " N_TXT=", N_TXT, " S=", S, " IN_CH=", IN_CH,
          " TEXT_IN=", TEXT_IN, " OUT_CH=", OUT_CH)
    print("  cache=", cache_dir)
    print("  max_steps=", run_steps, " rank=", train_cfg.lora_rank,
          " alpha=", train_cfg.lora_alpha, " lr=", train_cfg.lr)
    print("  mode=", mode)
    print("  save_path=", save_path)
    print("  checkpoint=", train_cfg.checkpoint)
    print(
        "  cadence: save_every=", train_cfg.save_every,
        " sample_after=", sample_cadence.sample_after,
        " unit=", sample_time_unit_name(sample_cadence.sample_after_unit),
        " skip_first=", sample_cadence.sample_skip_first,
        " sample_file=", sample_cadence.sample_definition_file_name,
        " enabled=", sample_enabled,
    )
    if sample_enabled:
        print("  sample_prompts=", sample_cadence.sample_definition_file_name,
              " count=", len(sample_cfg.prompts))

    var mem0 = ctx.get_memory_info()
    print("  free VRAM at start (bytes):", mem0[0], " total:", mem0[1])

    # ── open the real sharded transformer checkpoint (streamed block source) ──
    var st = ShardedSafeTensors.open(train_cfg.checkpoint)
    print("  opened transformer: num_shards =", st.num_shards())
    var base = load_ernie_stack_base(st, D, IN_CH, ctx)
    print("  base weights resident (patch/text/time/adaLN/final).")
    var blocks = load_ernie_all_blocks_bf16_normf32(st, NUM_LAYERS, ctx)
    var mem_blocks = ctx.get_memory_info()
    print("  block weights resident BF16/norm-F32:", len(blocks),
          " free VRAM after block load (bytes):", mem_blocks[0])

    # ── build the LoRA set (B=0 init -> adapter identity at step 0) ──
    var lora = build_ernie_lora_set(NUM_LAYERS, D, F, train_cfg.lora_rank, train_cfg.lora_alpha)
    var baseline_lora = build_ernie_lora_set(NUM_LAYERS, D, F, train_cfg.lora_rank, train_cfg.lora_alpha)
    var n_adapters = NUM_LAYERS * ERNIE_SLOTS
    var lokr_active = train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOKR
    var loha_active = train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_LOHA
    var dora_active = train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_DORA
    var oft_active = train_cfg.adapter_algo == TRAIN_ADAPTER_ALGO_OFT
    var direct_active = dora_active or oft_active
    var carrier_active = lokr_active or loha_active

    # ── gradient accumulation (item 2h; SerenityTrainer sum-N-then-mean) ───────────
    # Each loop iteration is one MICRO-step. We SUM the plain LoRA host grad
    # groups (grads.d_a/d_b) across grad_accum_steps micro-steps, MEAN (÷N), then
    # run clip+AdamW once on accumulation boundaries. accum_steps=1 => every step
    # is a boundary, buffer holds one grad, mean=÷1 => byte-identical baseline.
    # The LyCORIS algos (lokr/loha carrier + dora/oft direct masters) route the
    # optimizer through separate chain/master paths; fail loud rather than
    # silently mis-accumulating them (mirrors klein's honest scope).
    var accum_steps = train_cfg.grad_accum_steps
    if accum_steps < 1:
        accum_steps = 1
    var use_grad_accum = accum_steps > 1
    if use_grad_accum and (direct_active or carrier_active):
        raise Error("ERNIE: grad_accum_steps>1 not wired for LyCORIS (lokr/loha/dora/oft) this wave")

    # ── TRUE batch-2 (row-stacked; default-off when batch_size==1) ────────────
    # batch_size==2 processes two samples per optimizer step through the b2
    # resident-device stack (joint 2N-mean loss → batch gradient), fed to the SAME
    # host-list plain-LoRA fused-AdamW arm. Wired ONLY for the standard plain-LoRA
    # loop this wave; the LyCORIS (lokr/loha/dora/oft) arms and grad accumulation
    # are NOT b2-wired (fail loud, same fence style as grad-accum). batch_size==1
    # stays byte-identical (the whole b2 branch is guarded behind use_b2).
    var use_b2 = train_cfg.batch_size == 2
    if train_cfg.batch_size > 2:
        raise Error(
            String("ERNIE: batch_size=") + String(train_cfg.batch_size)
            + " unsupported — only 1 or 2 (TRUE batch-2 is the first vertical)"
        )
    if use_b2:
        if direct_active or carrier_active:
            raise Error(
                "ERNIE: batch_size=2 is not wired for the LyCORIS (lokr/loha/dora/oft)"
                " arms — use network_algorithm=lora on the host plain-LoRA path"
            )
        if use_grad_accum:
            raise Error(
                "ERNIE: batch_size=2 + grad_accum_steps>1 not wired together this"
                " wave — batch_size=2 IS a 2-sample batch; set grad_accum_steps=1"
            )
        print("  TRUE batch-2: two samples row-stacked per optimizer step")

    var direct_targets = ERNIE_LYCORIS_TGT_ATTN if train_cfg.lokr_targets == ERNIE_LYCORIS_TGT_ATTN else 2
    var lokr_masters = empty_ernie_lokr_set()
    var loha_masters = empty_ernie_loha_set()
    var dora_masters = empty_ernie_dora_set()
    var oft_masters = empty_ernie_oft_set()
    var direct_dora = empty_ernie_direct_dora_set()
    var direct_oft = empty_ernie_direct_oft_set()
    if lokr_active:
        lokr_masters = build_ernie_lokr_set(
            NUM_LAYERS, D, F,
            train_cfg.lora_rank, train_cfg.lora_alpha,
            train_cfg.lokr_factor, train_cfg.lokr_factor_attn,
            train_cfg.lokr_factor_ff,
            train_cfg.lokr_decompose_both, train_cfg.lokr_full_matrix,
            train_cfg.lokr_targets, UInt64(700301),
        )
        var carrier_bytes = ernie_lokr_carrier_total_bytes(lokr_masters, D, F)
        print("[Ernie-lokr] carrier device bytes:", carrier_bytes, " budget:", LOKR_CARRIER_MAX_DEVICE_BYTES)
        if carrier_bytes > LOKR_CARRIER_MAX_DEVICE_BYTES:
            raise Error(
                String("ERNIE LoKr: carrier set needs ")
                + String(carrier_bytes)
                + String(" bytes (> budget). Use a smaller lokr_factor/rank or restrict lokr_targets.")
            )
        lora = ernie_lokr_carrier_set(lokr_masters, D, F)
        print("[Ernie-lokr] carrier set materialized:", len(lora.ad), "adapters")
    elif loha_active:
        loha_masters = build_ernie_loha_set(
            NUM_LAYERS, D, F,
            train_cfg.lora_rank, train_cfg.lora_alpha,
            train_cfg.lokr_targets, UInt64(800301),
        )
        var carrier_bytes = ernie_loha_carrier_total_bytes(loha_masters, D, F)
        print("[Ernie-loha] carrier device bytes:", carrier_bytes, " budget:", LOKR_CARRIER_MAX_DEVICE_BYTES)
        if carrier_bytes > LOKR_CARRIER_MAX_DEVICE_BYTES:
            raise Error(
                String("ERNIE LoHa: carrier set needs ")
                + String(carrier_bytes)
                + String(" bytes (> budget). Reduce lora_rank or restrict lokr_targets.")
            )
        lora = ernie_loha_carrier_set(loha_masters, D, F)
        print("[Ernie-loha] carrier set materialized:", len(lora.ad), "adapters")
    elif dora_active:
        var dense_bytes = ernie_direct_dense_carrier_bytes(
            NUM_LAYERS, D, F, direct_targets,
        )
        var direct_bytes = ernie_direct_dora_preflight(
            NUM_LAYERS, D, F, train_cfg.lora_rank, direct_targets,
            LOKR_CARRIER_MAX_DEVICE_BYTES,
        )
        print("[Ernie-dora-direct] dense carrier bytes:", dense_bytes,
              " direct trainable bytes:", direct_bytes,
              " budget:", LOKR_CARRIER_MAX_DEVICE_BYTES,
              " targets:", direct_targets)
        direct_dora = build_ernie_direct_dora_set_from_blocks(
            blocks, D, F, train_cfg.lora_rank, train_cfg.lora_alpha,
            direct_targets, UInt64(900301), ctx,
        )
        print("[Ernie-dora-direct] trainable bytes:",
              ernie_direct_dora_trainable_bytes(direct_dora),
              " slots:", len(direct_dora.ad))
    elif oft_active:
        var dense_bytes = ernie_direct_dense_carrier_bytes(
            NUM_LAYERS, D, F, direct_targets,
        )
        var direct_bytes = ernie_direct_oft_preflight(
            NUM_LAYERS, D, F, ERNIE_OFT_BLOCK_SIZE, direct_targets,
            LOKR_CARRIER_MAX_DEVICE_BYTES,
        )
        print("[Ernie-oft-direct] dense carrier bytes:", dense_bytes,
              " direct trainable bytes:", direct_bytes,
              " budget:", LOKR_CARRIER_MAX_DEVICE_BYTES,
              " targets:", direct_targets,
              " block_size:", ERNIE_OFT_BLOCK_SIZE)
        direct_oft = build_ernie_direct_oft_set(
            NUM_LAYERS, D, F, ERNIE_OFT_BLOCK_SIZE, direct_targets,
        )
        print("[Ernie-oft-direct] trainable bytes:",
              ernie_direct_oft_trainable_bytes(direct_oft),
              " slots:", len(direct_oft.ad))
    print("  LoRA adapters:", n_adapters, " (7 slots x", NUM_LAYERS, "layers)")
    if carrier_active:
        print("  carrier LoRA-B |.|_1 at init =", _lora_b_abs_sum(lora))
    elif direct_active:
        print("  direct LyCORIS path active; dense LoRA carrier is not materialized")
    else:
        print("  LoRA-B |.|_1 at init =", _lora_b_abs_sum(lora), " (expect 0.0)")
    var carrier_zero_init = Float64(0.0)
    if lokr_active:
        carrier_zero_init = ernie_lokr_zero_leg_l1(lokr_masters)
        print("[Ernie-lokr] zero-leg L1 at init =", carrier_zero_init)
    elif loha_active:
        carrier_zero_init = ernie_loha_zero_leg_l1(loha_masters)
        print("[Ernie-loha] zero-leg L1 at init =", carrier_zero_init)
    elif dora_active:
        carrier_zero_init = flat_direct_dora_zero_leg_l1(direct_dora)
        print("[Ernie-dora-direct] zero-leg L1 at init =", carrier_zero_init)
    elif oft_active:
        carrier_zero_init = flat_direct_oft_vec_l1(direct_oft)
        print("[Ernie-oft-direct] vec L1 at init =", carrier_zero_init)

    # ── RoPE tables (image-first/text-second 3-axis half-split) ──
    # SerenityTrainer's image RoPE axis-0 position == the per-sample TEXT real length
    # (transformer_ernie_image.py:388 image_ids axis-0 = text_lens). So the table
    # is rebuilt PER SAMPLE inside the loop with text_len_real = real_len read from
    # the cache (NOT the fixed N_TXT). build_ernie_rope_tables requires real in
    # (0, N_TXT]. (Was: built once with N_TXT — a divergence from SerenityTrainer.)
    print("  RoPE tables: per-sample, cos/sin [S*H, Dh] = [", S * H, ",", Dh, "]")

    var cache_files = list_sorted_safetensors(cache_dir)
    if len(cache_files) == 0:
        raise Error("no cache files found")
    print("  found", len(cache_files), "cached samples")

    var last_sample_step = -1
    if sample_enabled and (should_sample_completed_step(sample_cadence, 0) or mode == String("resume_smoke")):
        _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, 0, ctx)
        last_sample_step = 0

    var rng_state = SEED
    var t_start = perf_counter()

    # window buffers + micro counter live in the shared trainer_core struct (wraps
    # the grad_accum.mojo SUM/MEAN primitives). accum_steps==1 => every step is a
    # boundary => byte-identical to the per-step path.
    var accum_window = GradAccumWindow(accum_steps)
    if use_grad_accum:
        print("  grad accumulation: accum_steps=", accum_steps, " (mean over micro-steps)")

    # ── resident fused-AdamW state (MJ-1070/MJ-1085 crash-class fix). Persistent
    # device P/M/V + ONE-TIME pinned staging; lazily initialized on first
    # optimizer use (after any resume load) inside the plain-LoRA GPU arm. ──────
    var adamw_dev_state = Optional[LoraAdamWPlainDeviceState](None)
    var adamw_state_ready = False

    # ── T1.B EMA (default-off; SimpleTuner EMAModel — training/lora_ema.mojo).
    # F32 shadows over the plain-LoRA adapters (lora.ad), tracked AFTER
    # build/resume. ema_enabled False => no shadows; the per-step update + *_ema
    # save below are no-ops (baseline byte-identical). Plain-LoRA arm only:
    # LyCORIS/DoRA/OFT trains carriers, not lora.ad. ──────────────────────────
    var ema = LoraEmaState(
        train_cfg.ema_decay, train_cfg.ema_min_decay,
        train_cfg.ema_update_after_step, train_cfg.ema_update_step_interval,
    )
    if train_cfg.ema_enabled and not direct_active and not carrier_active:
        var ema_base = lora_ema_track(ema, lora.ad, 0, len(lora.ad))
        if ema_base != 0:
            raise Error("train_ernie_real: ema shadow base must be 0")
        print("[ema] tracking", len(lora.ad), "adapters decay=", train_cfg.ema_decay,
              " min_decay=", train_cfg.ema_min_decay,
              " update_after_step=", train_cfg.ema_update_after_step,
              " interval=", train_cfg.ema_update_step_interval)

    for step in range(run_steps):
        var step_t0 = perf_counter()
        # TRUE batch-2: each optimizer step consumes a NON-OVERLAPPING pair
        # (order[2k], order[2k+1]); odd tail wraps via %len = self-dup. b1:
        # pair_lead == step (byte-identical sample/sigma/noise stream to the pre-b2
        # loop). See krea2 train_krea2.mojo:3765.
        var pair_lead = (2 * step) if use_b2 else step
        var cache_idx = pair_lead % len(cache_files)
        var cs = SafeTensors.open(cache_files[cache_idx])

        var latent_cache = load_cache_tensor(cs, String("latent"), ctx)
        var latent = latent_cache.to_host_bf16(ctx)                        # [128*32*32]
        var text_cache = load_cache_tensor(cs, String("text_embedding"), ctx)
        var text = text_cache.to_host_bf16(ctx)                            # [512*3072]
        var tdims = cache_tensor_dims(cs, String("text_embedding"))
        var t_cache = tdims[1]

        var img_tokens = _latent_to_img_tokens(latent)                     # [N_IMG, IN_CH]
        var txt_tokens = _text_to_txt_tokens(text, t_cache)                # [N_TXT, TEXT_IN]

        # ── per-sample real TEXT length (pre-pad token count). SerenityTrainer trims
        # text to text_lengths.max() and MASKS padded text in attention; the cache
        # stores this real_len. Rows [real_len, N_TXT) are nonzero Mistral PAD
        # embeddings that must NOT attend. Drives both the attention text-pad mask
        # AND the image RoPE axis-0 position (transformer_ernie_image.py:388-401).
        var real_len = N_TXT
        if cache_has_key(cs, String("text_real_len")):
            var rl_t = load_cache_tensor(cs, String("text_real_len"), ctx)
            var rl_h = rl_t.to_host(ctx)
            real_len = Int(rl_h[0])
        if real_len < 1:
            real_len = 1
        if real_len > N_TXT:
            real_len = N_TXT

        # ── RoPE tables for THIS sample (image axis-0 position = real_len) ──
        # The ERNIE training stack still stages block activations through the
        # established host-list F32 path. RoPE tables are compute constants, so
        # keep them F32 here instead of forcing an activation/storage dtype cast.
        var rope = build_ernie_rope_tables[N_IMG, N_TXT, H, Dh](
            IMG_H, IMG_W, real_len, ctx, STDtype.F32
        )

        # ── sigma + flow-match noise/target (F32; train_ernie.rs:904-949) ──
        var sigma_draw = _sample_sigma_idx(rng_state)
        var sigma_idx = sigma_draw[0]
        rng_state = sigma_draw[1]
        var sigma = Float32(sigma_idx + 1) / Float32(NUM_TRAIN_TIMESTEPS)
        var n_lat = N_IMG * IN_CH
        var noise = _host_noise(n_lat, SEED ^ (UInt64(pair_lead) + 1))
        # noisy = noise*sigma + latent*(1-sigma)  (image-token space; same packing)
        var target = List[Float32]()
        for i in range(n_lat):
            target.append(noise[i] - img_tokens[i])      # target = noise - latent
        # the DiT input is the NOISY latent tokens (not the clean ones)
        var noisy_tokens = List[Float32]()
        for i in range(n_lat):
            noisy_tokens.append(noise[i] * sigma + img_tokens[i] * (Float32(1.0) - sigma))

        # ── shared-AdaLN source from the resident base + sigma_idx ──
        var src = _shared_adaln_source(base, sigma_idx, ctx)
        var mv = src[0].copy()
        var f_scale = src[1].copy()
        var f_shift = src[2].copy()

        var done_step = step + 1
        # Wave 2A scheduled lr keys on OPTIMIZER steps, not micro-steps; with
        # accum_steps=1 this is (step//1)+1 == done_step => baseline unchanged.
        var optimizer_step = (step // accum_steps) + 1
        var step_lr = serenity_lr_for_optimizer_step(train_cfg, optimizer_step)
        var loss = Float32(0.0)
        var gn = Float64(0.0)
        var nonfinite_grads = 0
        var progress_label = String("Ernie-lora")

        if dora_active:
            progress_label = String("Ernie-dora")
            var fwd_dora = ernie_stack_direct_dora_forward_resident_device[H, Dh, N_IMG, N_TXT, S](
                noisy_tokens.copy(), txt_tokens.copy(), base, blocks,
                direct_dora, direct_targets, mv,
                f_scale.copy(), f_shift.copy(), rope[0], rope[1],
                D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                real_len,
            )
            var lg = _mse_loss_grad(fwd_dora.out, target)
            loss = lg.loss
            var dg = ernie_stack_direct_dora_backward_resident_device[H, Dh, N_IMG, N_TXT, S](
                lg.d_out, noisy_tokens.copy(), txt_tokens.copy(), base, blocks,
                direct_dora, direct_targets, mv,
                f_scale.copy(), f_shift.copy(), rope[0], rope[1], fwd_dora,
                D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                real_len,
            )
            gn = flat_direct_dora_grad_norm(dg.grads)
            if gn > Float64(train_cfg.max_grad_norm):
                flat_direct_dora_clip_grads(dg.grads, train_cfg.max_grad_norm / Float32(gn))
            flat_direct_dora_adamw_step(
                direct_dora, dg.grads, done_step, step_lr,
                train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
            )
            nonfinite_grads = dg.nonfinite_grads
            print("[Ernie-dora-direct] step=", done_step, " master_grad_norm=", Float32(gn),
                  " zero_leg_l1=", flat_direct_dora_zero_leg_l1(direct_dora))
        elif oft_active:
            progress_label = String("Ernie-oft")
            var fwd_oft = ernie_stack_direct_oft_forward_resident_device[H, Dh, N_IMG, N_TXT, S](
                noisy_tokens.copy(), txt_tokens.copy(), base, blocks,
                direct_oft, direct_targets, mv,
                f_scale.copy(), f_shift.copy(), rope[0], rope[1],
                D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                real_len,
            )
            var lg = _mse_loss_grad(fwd_oft.out, target)
            loss = lg.loss
            var og = ernie_stack_direct_oft_backward_resident_device[H, Dh, N_IMG, N_TXT, S](
                lg.d_out, noisy_tokens.copy(), txt_tokens.copy(), base, blocks,
                direct_oft, direct_targets, mv,
                f_scale.copy(), f_shift.copy(), rope[0], rope[1], fwd_oft,
                D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                real_len,
            )
            gn = flat_direct_oft_grad_norm(og.grads)
            if gn > Float64(train_cfg.max_grad_norm):
                flat_direct_oft_clip_grads(og.grads, train_cfg.max_grad_norm / Float32(gn))
            flat_direct_oft_adamw_step(
                direct_oft, og.grads, done_step, step_lr,
                train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
            )
            nonfinite_grads = og.nonfinite_grads
            print("[Ernie-oft-direct] step=", done_step, " master_grad_norm=", Float32(gn),
                  " vec_l1=", flat_direct_oft_vec_l1(direct_oft))
        else:
            # ── device-resident LoRA/carrier forward (BF16 base blocks resident) ──
            # NOTE (speed audit 2026-07-01): this per-step upload is NOT dead
            # weight — both optimizer paths (host loop and ERNIE_GPU_ADAMW
            # fused step) write updated params back into the HOST lora.ad
            # lists, and lokr/loha/resume paths reassign `lora` mid-loop, so
            # this rebuild is how updated weights reach the device. Hoisting
            # it requires the resident-param design (LoraAdamWPlainDeviceState
            # dev_p as the live weight buffer, zimage ZIMAGE_V2_ENGINE
            # pattern), not a simple move.
            var lora_dev = ernie_lora_set_to_device(lora, STDtype.BF16, ctx)
            var grads: ErnieLoraGrads
            if use_b2:
                # ── TRUE batch-2: fetch the pair partner order[2k+1] (own cache,
                # sigma, noise, rope, AdaLN source) and row-stack both samples ──
                var idx1 = (pair_lead + 1) % len(cache_files)
                var cs1 = SafeTensors.open(cache_files[idx1])
                var latent1 = load_cache_tensor(cs1, String("latent"), ctx).to_host_bf16(ctx)
                var text_cache1 = load_cache_tensor(cs1, String("text_embedding"), ctx)
                var text1 = text_cache1.to_host_bf16(ctx)
                var tdims1 = cache_tensor_dims(cs1, String("text_embedding"))
                var t_cache1 = tdims1[1]
                var img_tokens1 = _latent_to_img_tokens(latent1)
                var txt_tokens1 = _text_to_txt_tokens(text1, t_cache1)

                var real_len1 = N_TXT
                if cache_has_key(cs1, String("text_real_len")):
                    var rl_t1 = load_cache_tensor(cs1, String("text_real_len"), ctx)
                    var rl_h1 = rl_t1.to_host(ctx)
                    real_len1 = Int(rl_h1[0])
                if real_len1 < 1:
                    real_len1 = 1
                if real_len1 > N_TXT:
                    real_len1 = N_TXT

                var rope1 = build_ernie_rope_tables[N_IMG, N_TXT, H, Dh](
                    IMG_H, IMG_W, real_len1, ctx, STDtype.F32
                )

                var sigma_draw1 = _sample_sigma_idx(rng_state)
                var sigma_idx1 = sigma_draw1[0]
                rng_state = sigma_draw1[1]
                var sigma1 = Float32(sigma_idx1 + 1) / Float32(NUM_TRAIN_TIMESTEPS)
                var noise1 = _host_noise(n_lat, SEED ^ (UInt64(pair_lead + 1) + 1))
                var target1 = List[Float32]()
                for i in range(n_lat):
                    target1.append(noise1[i] - img_tokens1[i])
                var noisy_tokens1 = List[Float32]()
                for i in range(n_lat):
                    noisy_tokens1.append(noise1[i] * sigma1 + img_tokens1[i] * (Float32(1.0) - sigma1))

                var src1 = _shared_adaln_source(base, sigma_idx1, ctx)
                var mv1 = src1[0].copy()
                var f_scale1 = src1[1].copy()
                var f_shift1 = src1[2].copy()

                var fwd_b2 = ernie_stack_lora_forward_resident_device_b2[H, Dh, N_IMG, N_TXT, S](
                    noisy_tokens.copy(), txt_tokens.copy(),
                    noisy_tokens1.copy(), txt_tokens1.copy(),
                    base, blocks, lora_dev, mv, mv1,
                    f_scale.copy(), f_shift.copy(), f_scale1.copy(), f_shift1.copy(),
                    rope[0], rope[1], rope1[0], rope1[1],
                    D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                    real_len, real_len1,
                )
                # joint 2N-mean MSE: each per-sample loss/grad halved → summed.
                var lg0 = _mse_half_loss_grad(fwd_b2.out0, target)
                var lg1 = _mse_half_loss_grad(fwd_b2.out1, target1)
                loss = lg0.loss + lg1.loss
                grads = ernie_stack_lora_backward_resident_device_b2[H, Dh, N_IMG, N_TXT, S](
                    lg0.d_out, lg1.d_out,
                    noisy_tokens.copy(), txt_tokens.copy(),
                    noisy_tokens1.copy(), txt_tokens1.copy(),
                    base, blocks, lora_dev, mv, mv1,
                    f_scale.copy(), f_shift.copy(), f_scale1.copy(), f_shift1.copy(),
                    rope[0], rope[1], rope1[0], rope1[1], fwd_b2,
                    D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                    real_len, real_len1,
                )
            else:
                var fwd = ernie_stack_lora_forward_resident_device[H, Dh, N_IMG, N_TXT, S](
                    noisy_tokens.copy(), txt_tokens.copy(), base, blocks, lora_dev, mv,
                    f_scale.copy(), f_shift.copy(), rope[0], rope[1],
                    D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                    real_len,
                )
                var lg = _mse_loss_grad(fwd.out, target)
                loss = lg.loss
                grads = ernie_stack_lora_backward_resident_device[H, Dh, N_IMG, N_TXT, S](
                    lg.d_out, noisy_tokens.copy(), txt_tokens.copy(), base, blocks, lora_dev, mv,
                    f_scale.copy(), f_shift.copy(), rope[0], rope[1], fwd,
                    D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
                    real_len,
                )

            # ── gradient accumulation (item 2h; default-off when N==1) ────────
            # SUM this micro-step's grads into the shared trainer_core window; on a
            # non-boundary micro-step print progress and skip clip+AdamW; on the
            # boundary MEAN (÷N) back into grads.d_a/d_b so the UNCHANGED clip+AdamW
            # below run once. The window math lives in trainer_core.GradAccumWindow
            # (byte-op-identical to the prior inline block); the boundary control
            # flow (progress print + continue) stays here. step==run_steps-1
            # force-flushes the tail partial window. (LyCORIS algos are fenced above
            # when N>1.) The recomputed norm is discarded (the _clip_grads below
            # recomputes it from the meaned grads).
            if use_grad_accum:
                var is_boundary = accum_window.accumulate(grads.d_a, grads.d_b, step == run_steps - 1)
                if not is_boundary:
                    var now_m = perf_counter()
                    print_trainer_progress(
                        String("Ernie-lora"), done_step, run_steps, len(cache_files),
                        loss, 0.0, now_m - step_t0, 0.0, now_m - t_start,
                    )
                    continue
                _ = accum_window.finalize_mean(grads.d_a, grads.d_b)

            gn = _clip_grads(grads, train_cfg.max_grad_norm)
            nonfinite_grads = grads.nonfinite_lora_grads
            if lokr_active:
                var mg = ernie_lokr_chain_all(lokr_masters, grads.d_a, grads.d_b)
                var mnorm = ernie_lokr_grad_norm(mg)
                if mnorm > Float64(train_cfg.max_grad_norm):
                    ernie_lokr_clip_grads(mg, train_cfg.max_grad_norm / Float32(mnorm))
                ernie_lokr_adamw_step(
                    lokr_masters, mg, done_step, step_lr,
                    train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
                )
                lora = ernie_lokr_carrier_set(lokr_masters, D, F)
                print("[Ernie-lokr] step=", done_step, " master_grad_norm=", Float32(mnorm),
                      " zero_leg_l1=", ernie_lokr_zero_leg_l1(lokr_masters))
            elif loha_active:
                var mg = ernie_loha_chain_all(loha_masters, grads.d_a, grads.d_b)
                var mnorm = ernie_loha_grad_norm(mg)
                if mnorm > Float64(train_cfg.max_grad_norm):
                    ernie_loha_clip_grads(mg, train_cfg.max_grad_norm / Float32(mnorm))
                ernie_loha_adamw_step(
                    loha_masters, mg, done_step, step_lr,
                    train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
                )
                lora = ernie_loha_carrier_set(loha_masters, D, F)
                print("[Ernie-loha] step=", done_step, " master_grad_norm=", Float32(mnorm),
                      " zero_leg_l1=", ernie_loha_zero_leg_l1(loha_masters))
            else:
                comptime if ERNIE_GPU_ADAMW:
                    # MJ-1070/MJ-1085: RESIDENT fused plain-AdamW over the whole
                    # flat adapter list — persistent device P/M/V with ONE-TIME
                    # pinned staging (init lazily after resume load). The retired
                    # per-step fused arm allocated FRESH pinned staging every step
                    # and segfaulted on an unmapped buffer under pinned pressure.
                    # grads.d_a/d_b were already global-norm clipped on host by
                    # _clip_grads above. Updated params land back in the host
                    # lora.ad mirrors — the per-step ernie_lora_set_to_device
                    # upload (top of this branch) is still how the device sees
                    # the new weights.
                    if not adamw_state_ready:
                        adamw_dev_state = Optional[LoraAdamWPlainDeviceState](
                            ernie_lora_adamw_state_init(lora, ctx)
                        )
                        adamw_state_ready = True
                        print("[ernie-adamw] resident fused state initialized (",
                              len(lora.ad), "adapters )")
                    ernie_lora_adamw_step_resident(
                        adamw_dev_state.value(), lora, grads,
                        optimizer_step, step_lr, ctx,
                        train_cfg.beta1, train_cfg.beta2, train_cfg.eps,
                        train_cfg.weight_decay,
                    )
                else:
                    ernie_lora_adamw_step(
                        lora, grads, optimizer_step, step_lr, ctx,
                        train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
                    )
                # T1.B: EMA shadow update post-AdamW (plain arm; once per
                # OPTIMIZER step — this block runs only at grad-accum boundaries).
                if train_cfg.ema_enabled:
                    ema_update(ema, lora.ad, optimizer_step)

        var now = perf_counter()
        var step_secs = now - step_t0
        var elapsed = now - t_start
        print_trainer_progress(
            progress_label, done_step, run_steps, len(cache_files),
            loss, gn, step_secs, 0.0, elapsed,
        )
        if nonfinite_grads != 0:
            print(
                "[", progress_label, "] nonfinite adapter grads step=", done_step,
                " count=", nonfinite_grads,
            )

        var saved_this_step = False
        var saved_lora_path = String("")

        if mode == String("resume_smoke") and done_step == 10:
            var smoke_lora = _step_lora_path(save_path, done_step)
            _save_adapter_for_algo(
                lora, lokr_masters, loha_masters, dora_masters, oft_masters,
                direct_dora, direct_oft,
                lokr_active, loha_active, dora_active, oft_active,
                smoke_lora, done_step, ctx,
            )
            if train_cfg.ema_enabled and not direct_active and not carrier_active:
                _save_ernie_lora_ema(ema, lora, smoke_lora, ctx)  # T1.B EMA sibling
            saved_this_step = True
            saved_lora_path = smoke_lora.copy()
            if sample_enabled:
                _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, done_step, ctx)
                last_sample_step = done_step
            var smoke_state = _state_path_for_lora(smoke_lora)
            lora = load_ernie_lora_state(NUM_LAYERS, train_cfg.lora_rank, train_cfg.lora_alpha, smoke_state, ctx)
            print("[Ernie-lora] resume_state step=", done_step, " path=", smoke_state)

        if ernie_should_save_checkpoint(train_cfg, done_step) and not saved_this_step:
            var save_cadence_lora = _step_lora_path(save_path, done_step)
            _save_adapter_for_algo(
                lora, lokr_masters, loha_masters, dora_masters, oft_masters,
                direct_dora, direct_oft,
                lokr_active, loha_active, dora_active, oft_active,
                save_cadence_lora, done_step, ctx,
            )
            if train_cfg.ema_enabled and not direct_active and not carrier_active:
                _save_ernie_lora_ema(ema, lora, save_cadence_lora, ctx)  # T1.B EMA sibling
            saved_this_step = True
            saved_lora_path = save_cadence_lora.copy()
            _ernie_prune_old_checkpoints(train_cfg, save_path, done_step)

        if sample_enabled and should_sample_completed_step(sample_cadence, done_step):
            var cadence_lora = _step_lora_path(save_path, done_step)
            if ernie_should_save_before_sample(sample_cadence, done_step, saved_this_step):
                _save_adapter_for_algo(
                    lora, lokr_masters, loha_masters, dora_masters, oft_masters,
                    direct_dora, direct_oft,
                    lokr_active, loha_active, dora_active, oft_active,
                    cadence_lora, done_step, ctx,
                )
                if train_cfg.ema_enabled and not direct_active and not carrier_active:
                    _save_ernie_lora_ema(ema, lora, cadence_lora, ctx)  # T1.B EMA sibling
                saved_lora_path = cadence_lora.copy()
            _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, done_step, ctx)
            last_sample_step = done_step
            if (
                sample_cadence.save_before_sample
                and saved_lora_path == cadence_lora
                and not carrier_active
            ):
                var cadence_state = _state_path_for_lora(cadence_lora)
                lora = load_ernie_lora_state(NUM_LAYERS, train_cfg.lora_rank, train_cfg.lora_alpha, cadence_state, ctx)
                print("[Ernie-lora] resume_state step=", done_step, " path=", cadence_state)

    # ── final adapter growth report + save ──
    var b_sum = Float64(0.0)
    var b_nz = 0
    if not direct_active:
        b_sum = _lora_b_abs_sum(lora)
        b_nz = _lora_b_nonzero_slots(lora)
    print("")
    print("==== RESULT ====")
    if not direct_active:
        print("  LoRA-B |.|_1 after training =", b_sum, " (init 0.0)")
        print("  LoRA-B nonzero slots =", b_nz, "/", n_adapters,
              " ratio =", Float32(b_nz) / Float32(n_adapters))
    if lokr_active:
        print("[Ernie-lokr] zero-leg L1 after training =", ernie_lokr_zero_leg_l1(lokr_masters),
              " (init ", carrier_zero_init, ")")
    elif loha_active:
        print("[Ernie-loha] zero-leg L1 after training =", ernie_loha_zero_leg_l1(loha_masters),
              " (init ", carrier_zero_init, ")")
    elif dora_active:
        print("[Ernie-dora-direct] zero-leg L1 after training =", flat_direct_dora_zero_leg_l1(direct_dora),
              " (init ", carrier_zero_init, ")")
    elif oft_active:
        print("[Ernie-oft-direct] vec L1 after training =", flat_direct_oft_vec_l1(direct_oft),
              " (init ", carrier_zero_init, ")")
    _save_adapter_for_algo(
        lora, lokr_masters, loha_masters, dora_masters, oft_masters,
        direct_dora, direct_oft,
        lokr_active, loha_active, dora_active, oft_active,
        save_path, run_steps, ctx,
    )
    if train_cfg.ema_enabled and not direct_active and not carrier_active:
        _save_ernie_lora_ema(ema, lora, save_path, ctx)  # T1.B EMA sibling
    if sample_enabled and last_sample_step != run_steps:
        _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, run_steps, ctx)
