# ops/embed_smoke.mojo — GPU smoke + parity driver for ops/embeddings.mojo.
#
# Builds a DeviceContext, loads the SAME fixed-seed inputs + numpy references
# inlined in parity/embed_ref_data.mojo (generated by
# parity/gen_embed_reference.py, seed=4242), runs the three pieces on the GPU,
# copies back, and compares via ParityHarness. Prints cos + max_abs each. Gate:
# cos >= 0.999.
#
# Three checks:
#   1. timestep_embedding  — sinusoidal embed (COS then SIN), F32 + BF16 storage.
#   2. t_embedder          — timestep_embedding -> Linear -> SiLU -> Linear.
#   3. rope-tables-through-rope_halfsplit — build_rope_tables, feed cos/sin into
#      ops/rope.rope_halfsplit, compare to a full numpy RoPE reference. This is
#      the load-bearing check: it proves the tables are in the layout
#      rope_halfsplit expects (cos/sin = [rows, head_dim/2]).
#
# F32 parity isolates op math. BF16 branches prove tensor-boundary storage stays
# in the model dtype.
#
# Run: pixi run mojo run -I . serenitymojo/ops/embed_smoke.mojo

from std.gpu.host import DeviceContext
from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.parity import ParityHarness, ParityResult
from serenitymojo.ops.embeddings import (
    timestep_embedding,
    t_embedder,
    build_rope_tables,
)
from serenitymojo.ops.rope import rope_halfsplit
from serenitymojo.ops.parity.embed_ref_data import (
    EMB_N,
    EMB_DIM,
    EMB_HIDDEN,
    EMB_MAX_PERIOD,
    ROPE_HEAD_DIM,
    ROPE_THETA,
    ROPE_ROWS,
    t_vals,
    ts_emb_ref,
    mlp0_w,
    mlp0_b,
    mlp2_w,
    mlp2_b,
    t_embedder_ref,
    positions,
    cos_tab_ref,
    sin_tab_ref,
    rope_x,
    rope_out_ref,
)


def main() raises:
    var ctx = DeviceContext()
    var harness = ParityHarness()
    var all_pass = True

    # ── 1. timestep_embedding ─────────────────────────────────────────────────
    var t_t = Tensor.from_host(t_vals(), [EMB_N], STDtype.F32, ctx)
    var ts_emb = timestep_embedding(t_t, EMB_DIM, ctx, EMB_MAX_PERIOD, STDtype.F32)
    var r_ts = harness.compare(ts_emb, ts_emb_ref(), ctx)
    print("timestep_embedding ", r_ts)
    if not r_ts.passed:
        all_pass = False
    var t_t_bf16 = Tensor.from_host(t_vals(), [EMB_N], STDtype.F32, ctx)
    var ts_emb_bf16 = timestep_embedding(
        t_t_bf16, EMB_DIM, ctx, EMB_MAX_PERIOD, STDtype.BF16
    )
    if ts_emb_bf16.dtype() != STDtype.BF16:
        raise Error("timestep_embedding BF16 branch returned non-BF16 storage")
    var r_ts_bf16 = harness.compare(ts_emb_bf16, ts_emb_ref(), ctx)
    print("timestep_embedding BF16", r_ts_bf16)
    if not r_ts_bf16.passed:
        all_pass = False

    # ── 2. t_embedder (MLP) ───────────────────────────────────────────────────
    var t_t2 = Tensor.from_host(t_vals(), [EMB_N], STDtype.F32, ctx)
    var w0 = Tensor.from_host(mlp0_w(), [EMB_HIDDEN, EMB_DIM], STDtype.F32, ctx)
    var b0 = Tensor.from_host(mlp0_b(), [EMB_HIDDEN], STDtype.F32, ctx)
    var w2 = Tensor.from_host(mlp2_w(), [EMB_DIM, EMB_HIDDEN], STDtype.F32, ctx)
    var b2 = Tensor.from_host(mlp2_b(), [EMB_DIM], STDtype.F32, ctx)
    var te = t_embedder(
        t_t2,
        EMB_DIM,
        w0,
        Optional[Tensor](b0^),
        w2,
        Optional[Tensor](b2^),
        ctx,
        EMB_MAX_PERIOD,
    )
    var r_te = harness.compare(te, t_embedder_ref(), ctx)
    print("t_embedder         ", r_te)
    if not r_te.passed:
        all_pass = False
    var t_t3 = Tensor.from_host(t_vals(), [EMB_N], STDtype.F32, ctx)
    var w0_bf16 = Tensor.from_host(mlp0_w(), [EMB_HIDDEN, EMB_DIM], STDtype.BF16, ctx)
    var b0_bf16 = Tensor.from_host(mlp0_b(), [EMB_HIDDEN], STDtype.BF16, ctx)
    var w2_bf16 = Tensor.from_host(mlp2_w(), [EMB_DIM, EMB_HIDDEN], STDtype.BF16, ctx)
    var b2_bf16 = Tensor.from_host(mlp2_b(), [EMB_DIM], STDtype.BF16, ctx)
    var te_bf16 = t_embedder(
        t_t3,
        EMB_DIM,
        w0_bf16,
        Optional[Tensor](b0_bf16^),
        w2_bf16,
        Optional[Tensor](b2_bf16^),
        ctx,
        EMB_MAX_PERIOD,
    )
    if te_bf16.dtype() != STDtype.BF16:
        raise Error("t_embedder BF16 branch returned non-BF16 storage")
    var r_te_bf16 = harness.compare(te_bf16, t_embedder_ref(), ctx)
    print("t_embedder BF16    ", r_te_bf16)
    if not r_te_bf16.passed:
        all_pass = False

    # ── 3a. rope tables vs numpy tables (direct) ──────────────────────────────
    var pos_t = Tensor.from_host(positions(), [ROPE_ROWS], STDtype.F32, ctx)
    var tables = build_rope_tables(pos_t, ROPE_HEAD_DIM, ROPE_THETA, ctx, STDtype.F32)
    var r_cos = harness.compare(tables[0], cos_tab_ref(), ctx)
    var r_sin = harness.compare(tables[1], sin_tab_ref(), ctx)
    print("rope cos table     ", r_cos)
    print("rope sin table     ", r_sin)
    if not r_cos.passed:
        all_pass = False
    if not r_sin.passed:
        all_pass = False
    var pos_bf16_t = Tensor.from_host(positions(), [ROPE_ROWS], STDtype.F32, ctx)
    var tables_bf16 = build_rope_tables(
        pos_bf16_t, ROPE_HEAD_DIM, ROPE_THETA, ctx, STDtype.BF16
    )
    if tables_bf16[0].dtype() != STDtype.BF16:
        raise Error("build_rope_tables BF16 cos returned non-BF16 storage")
    if tables_bf16[1].dtype() != STDtype.BF16:
        raise Error("build_rope_tables BF16 sin returned non-BF16 storage")
    var r_cos_bf16 = harness.compare(tables_bf16[0], cos_tab_ref(), ctx)
    var r_sin_bf16 = harness.compare(tables_bf16[1], sin_tab_ref(), ctx)
    print("rope cos table BF16", r_cos_bf16)
    print("rope sin table BF16", r_sin_bf16)
    if not r_cos_bf16.passed:
        all_pass = False
    if not r_sin_bf16.passed:
        all_pass = False

    # ── 3b. rope tables THROUGH rope_halfsplit vs full numpy RoPE ─────────────
    # The load-bearing check: tables must be in the layout rope_halfsplit eats.
    var x_t = Tensor.from_host(
        rope_x(), [ROPE_ROWS, ROPE_HEAD_DIM], STDtype.F32, ctx
    )
    var roped = rope_halfsplit(x_t, tables[0], tables[1], ctx)
    var r_rope = harness.compare(roped, rope_out_ref(), ctx)
    print("rope_halfsplit(out)", r_rope)
    if not r_rope.passed:
        all_pass = False
    var x_bf16_t = Tensor.from_host(
        rope_x(), [ROPE_ROWS, ROPE_HEAD_DIM], STDtype.BF16, ctx
    )
    var roped_bf16 = rope_halfsplit(
        x_bf16_t, tables_bf16[0], tables_bf16[1], ctx
    )
    if roped_bf16.dtype() != STDtype.BF16:
        raise Error("rope_halfsplit BF16 branch returned non-BF16 storage")
    var r_rope_bf16 = harness.compare(roped_bf16, rope_out_ref(), ctx)
    print("rope_halfsplit BF16", r_rope_bf16)
    if not r_rope_bf16.passed:
        all_pass = False

    print()
    if all_pass:
        print("ALL PASS (cos >= 0.999)")
    else:
        print("FAIL — at least one op below gate")
