# lens_gptoss_parity_smoke.mojo — Lens GPT-OSS text-encoder parity gate.
#
# Gates the ported pure-Mojo GPT-OSS text encoder (the microsoft/Lens GPT-OSS-20B
# decoder used as a frozen text encoder) against the Serenity oracle.
#
# Oracle (parity/lens/gptoss_ref.safetensors, generated by lens_gptoss_oracle.py
# running Serenity's OWN LensGptOssEncoder = GptOssForCausalLM, MXFP4->bf16):
#   input_ids       I32 [1,160]            fixed token ids (NOT re-tokenized here)
#   attention_mask  I32 [1,160]            all 1s (right-padded, 160 valid)
#   hidden_layer_05 F32 [1,160,2880]       selected-layer hidden state (pre-norm)
#   hidden_layer_11 F32 [1,160,2880]
#   hidden_layer_17 F32 [1,160,2880]
#   hidden_layer_23 F32 [1,160,2880]
#
# This smoke loads input_ids VERBATIM (isolating the encoder from the tokenizer),
# runs the streamed/OOM-aware Mojo GptOssEncoder requesting layers [5,11,17,23] at
# S=160 (>sliding_window 128, so the sliding/full causal alternation is exercised),
# and compares each layer's feature to the oracle by COSINE over all 1*160*2880
# elements. GATE: each layer cos >= 0.999.
#
# NOTE on magnitudes: GPT-OSS is a pre-norm residual stream; layer-23 std ~1208,
# absmax ~24832 (gptoss_meta.json). Cosine is scale-invariant, so the gate is on
# cosine, not abs error. Mean-abs-diff is reported for sanity only.
#
# Reference policy: Serenity ONLY (LensGptOssEncoder via the oracle). No Rust.

from max.gpu.host import DeviceContext
from std.math import isfinite

from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.io.sharded import ShardedSafeTensors

from serenitymojo.models.text_encoder.gpt_oss_encoder import (
    GptOssEncoder,
    GptOssConfig,
    lens_extract_layers,
)


comptime PARITY_DIR = "trainer/parity/lens"
comptime REF_PATH = "trainer/parity/lens/gptoss_ref.safetensors"
comptime TE_DIR = "/home/alex/.serenity/models/microsoft_lens/text_encoder"
comptime SEQ = 160
comptime HIDDEN = 2880
comptime COS_BAR = Float32(0.999)


# Read an integer tensor (I32/I64) from a safetensors view as a host List[Int],
# little-endian. input_ids / attention_mask are I32 on disk.
def _load_ints(st: ShardedSafeTensors, name: String) raises -> List[Int]:
    var info = st.tensor_info(name)
    var bsz = info.dtype.byte_size()
    var n = 1
    for i in range(len(info.shape)):
        n *= info.shape[i]
    var b = st.tensor_bytes(name)
    if len(b) != n * bsz:
        raise Error(
            String("_load_ints: ") + name + " byte count "
            + String(len(b)) + " != " + String(n * bsz)
        )
    var out = List[Int]()
    for i in range(n):
        var off = i * bsz
        var v = 0
        for k in range(bsz):
            v += Int(b[off + k]) << (8 * k)
        out.append(v)
    return out^


def _load_f32(st: ShardedSafeTensors, name: String, ctx: DeviceContext) raises -> List[Float32]:
    return Tensor.from_view_as_f32(st.tensor_view(name), ctx).to_host(ctx)


def _cosine(a: List[Float32], b: List[Float32]) raises -> Float32:
    if len(a) != len(b):
        raise Error(String("cosine: length mismatch ") + String(len(a))
                    + String(" vs ") + String(len(b)))
    var dot = Float64(0.0)
    var na = Float64(0.0)
    var nb = Float64(0.0)
    for i in range(len(a)):
        dot += Float64(a[i]) * Float64(b[i])
        na += Float64(a[i]) * Float64(a[i])
        nb += Float64(b[i]) * Float64(b[i])
    if na <= 0.0 or nb <= 0.0:
        raise Error("cosine: zero-norm vector")
    return Float32(dot / (na ** 0.5 * nb ** 0.5))


def _mean_abs_diff(a: List[Float32], b: List[Float32]) -> Float32:
    var s = Float64(0.0)
    for i in range(len(a)):
        var d = a[i] - b[i]
        if d < 0.0:
            d = -d
        s += Float64(d)
    return Float32(s / Float64(len(a)))


def _mean(a: List[Float32]) -> Float32:
    var s = Float64(0.0)
    for i in range(len(a)):
        s += Float64(a[i])
    return Float32(s / Float64(len(a)))


def _std(a: List[Float32], m: Float32) -> Float32:
    var s = Float64(0.0)
    for i in range(len(a)):
        var d = Float64(a[i]) - Float64(m)
        s += d * d
    return Float32((s / Float64(len(a))) ** 0.5)


def main() raises:
    var ctx = DeviceContext()
    print("=== Lens GPT-OSS text-encoder parity smoke (cos >=", COS_BAR, ") ===")

    # ── oracle fixtures ───────────────────────────────────────────────────────
    var st = ShardedSafeTensors.open(String(REF_PATH))
    var ids = _load_ints(st, String("input_ids"))
    var mask = _load_ints(st, String("attention_mask"))
    if len(ids) != SEQ:
        raise Error(String("input_ids len ") + String(len(ids)) + " != " + String(SEQ))
    if len(mask) != SEQ:
        raise Error(String("attention_mask len ") + String(len(mask)) + " != " + String(SEQ))

    # Mask sanity: the oracle ran all-ones (no padding); feed the full sequence
    # verbatim. (Right-padding would only shorten real_len; here real_len == SEQ.)
    var valid = 0
    var seen_pad = False
    for i in range(SEQ):
        if mask[i] != 0:
            if seen_pad:
                raise Error("attention_mask: interior/left padding not supported")
            valid += 1
        else:
            seen_pad = True
    print("[oracle] input_ids[160] loaded; attention_mask valid =", valid, "of", SEQ)
    print("  first ids:", ids[0], ids[1], ids[2], ids[3], "  last ids:",
          ids[SEQ - 4], ids[SEQ - 3], ids[SEQ - 2], ids[SEQ - 1])

    var sel = lens_extract_layers()  # [5, 11, 17, 23]
    print("  selected layers: [", sel[0], sel[1], sel[2], sel[3], "]")

    # ── Mojo GPT-OSS encoder (streamed, OOM-aware MXFP4) ──────────────────────
    print("[encoder] loading GPT-OSS text encoder:", String(TE_DIR))
    var cfg = GptOssConfig.lens_default()
    var enc = GptOssEncoder.load(String(TE_DIR), cfg, ctx)
    print("[encoder] encode(S=160, layers=[5,11,17,23]) — streaming 24 layers")
    var caps = enc.encode(ids, sel, ctx)   # ascending order: [5,11,17,23]
    if len(caps) != 4:
        raise Error(String("encode returned ") + String(len(caps)) + " features, expected 4")

    # ── per-layer cosine vs oracle ────────────────────────────────────────────
    var min_cos = Float32(2.0)
    var min_layer = -1
    var n_pass = 0
    for j in range(4):
        var li = sel[j]
        var mojo_feat = caps[j][].to_host(ctx)             # [1,160,2880] BF16 -> F32
        var ref_feat = _load_f32(st, String("hidden_layer_")
                                 + (String("0") + String(li) if li < 10 else String(li)),
                                 ctx)                       # [1,160,2880] F32
        if len(mojo_feat) != SEQ * HIDDEN:
            raise Error(String("mojo feat numel ") + String(len(mojo_feat))
                        + " != " + String(SEQ * HIDDEN) + " (layer " + String(li) + ")")
        for i in range(len(mojo_feat)):
            if not isfinite(mojo_feat[i]):
                raise Error(String("layer ") + String(li) + " feature non-finite at i=" + String(i))

        var cos = _cosine(mojo_feat, ref_feat)
        var mad = _mean_abs_diff(mojo_feat, ref_feat)
        var mm = _mean(mojo_feat)
        var ms = _std(mojo_feat, mm)
        var rm = _mean(ref_feat)
        var rs = _std(ref_feat, rm)

        var ok = cos >= COS_BAR
        if ok:
            n_pass += 1
        if cos < min_cos:
            min_cos = cos
            min_layer = li
        print("  layer", li, ": cos =", cos, ("PASS" if ok else "FAIL"))
        print("        mean-abs-diff =", mad,
              " | mojo mean/std =", mm, "/", ms,
              " | oracle mean/std =", rm, "/", rs)

    print("")
    print("=== RESULTS ===")
    print("  layers passing cos >=", COS_BAR, ":", n_pass, "of 4")
    print("  min cos =", min_cos, " (layer", min_layer, ")")
    if n_pass == 4:
        print("  GATE OK: all 4 selected layers match the Serenity oracle (cos >=", COS_BAR, ")")
        print("=== smoke complete ===")
    else:
        print("  GATE FAIL:", 4 - n_pass, "layer(s) below", COS_BAR,
              "— worst layer", min_layer, "cos", min_cos)
        raise Error(String("GPTOSS PARITY FAIL: worst layer ") + String(min_layer)
                    + " cos " + String(min_cos) + " < " + String(COS_BAR))
