# sampling/krea2_sampler_smoke.mojo — SCALAR step-parity gate for the krea2 sampler.
#
# Gates `krea2_timesteps` (the resolution-aware exponential-shift schedule) +
# `krea2_mu` against krea-ai/krea-2 `sampling.py::timesteps`, including the
# Turbo checkpoint's fixed mu=1.15 contract. The oracle values
# below are the byte-for-byte output of that reference function (regenerated by
# sampling/parity/gen_krea2_timesteps_oracle.py — see header), pinned here as the
# standard scalar-gate pattern (no file I/O in the gate).
#
# This is the SAFE CPU/scalar portion of the chunk-10 sampler gate: it does NOT
# run the offloaded DiT (the orchestrator runs the guarded e2e). The CFG combine
# and Euler step are thin tensor wrappers over already-gated tensor_algebra ops
# (sub/mul_scalar/add) and need no separate numeric oracle; their MATH is asserted
# here against the reference's algebra (v_cond + s*(v_cond - v_uncond) and
# latents + (t_prev - t_cur)*v) by construction.
#
# Run: cd /home/alex/mojodiffusion && \
#   pixi run mojo run -I . serenitymojo/sampling/krea2_sampler_smoke.mojo
#
# FAIL-LOUD: any |mojo - ref| > 1e-5 (F32 schedule tolerance) raises.
# Mojo 1.0.0b1.

from std.math import sqrt
from serenitymojo.sampling.krea2_sampler import (
    krea2_timesteps,
    krea2_mu,
    krea2_packed_seq_len,
)


comptime _TOL: Float32 = 1.0e-5


def _check_case(
    name: String,
    seq: Int,
    steps: Int,
    expect_mu: Float32,
    reference: List[Float32],
) raises:
    # mu check (krea2_mu vs the reference's linear interpolation).
    var mu = krea2_mu(Float32(seq))
    var dmu = mu - expect_mu
    if dmu < 0.0:
        dmu = -dmu
    print("  [", name, "] mu mojo =", mu, " ref =", expect_mu, " |d| =", dmu)
    if dmu > _TOL:
        raise Error(String("krea2 mu mismatch for ") + name + ": |d|=" + String(dmu))

    var ts = krea2_timesteps(seq, steps)
    if len(ts) != len(reference):
        raise Error(
            String("krea2_timesteps length mismatch for ") + name + ": got "
            + String(len(ts)) + " expected " + String(len(reference))
        )
    var max_abs: Float32 = 0.0
    for i in range(len(ts)):
        var d = ts[i] - reference[i]
        if d < 0.0:
            d = -d
        if d > max_abs:
            max_abs = d
    print("  [", name, "] ts steps =", len(ts), " max_abs =", max_abs)
    if max_abs > _TOL:
        # Print the offending pair for debugging.
        for i in range(len(ts)):
            print("     i=", i, " mojo=", ts[i], " ref=", reference[i])
        raise Error(
            String("krea2_timesteps mismatch for ") + name + ": max_abs="
            + String(max_abs)
        )
    print("  [", name, "] PASS")


def main() raises:
    print("[krea2-sampler-smoke] schedule + mu vs creator sampling.py::timesteps")

    # ── Case A: 256x256, 4 steps. seq = (256/16)^2 = 256 -> mu = 0.5 exactly. ──
    # packed seq sanity-check from H,W.
    var seqA = krea2_packed_seq_len(256, 256)
    if seqA != 256:
        raise Error("packed seq 256x256 != 256")
    var refA: List[Float32] = [
        Float32(1.0), Float32(0.8318243), Float32(0.62245935),
        Float32(0.35466126), Float32(0.0),
    ]
    _check_case("256x256 s4", seqA, 4, Float32(0.5), refA)

    # ── Case B: 1024x1024, 28 steps. seq = (1024/16)^2 = 4096 -> mu = 0.906250. ──
    var seqB = krea2_packed_seq_len(1024, 1024)
    if seqB != 4096:
        raise Error("packed seq 1024x1024 != 4096")
    var refB: List[Float32] = [
        Float32(1.0), Float32(0.98525637), Float32(0.9698571), Float32(0.9537577),
        Float32(0.93690914), Float32(0.91925782), Float32(0.90074533),
        Float32(0.88130659), Float32(0.86087066), Float32(0.83935869),
        Float32(0.81668335), Float32(0.79274762), Float32(0.76744354),
        Float32(0.74065024), Float32(0.71223223), Float32(0.68203706),
        Float32(0.64989281), Float32(0.61560428), Float32(0.57894975),
        Float32(0.5396753), Float32(0.4974899), Float32(0.45205718),
        Float32(0.40298739), Float32(0.3498255), Float32(0.2920374),
        Float32(0.22899166), Float32(0.15993667), Float32(0.0839702),
        Float32(0.0),
    ]
    _check_case("1024x1024 s28", seqB, 28, Float32(0.90625), refB)

    # ── Case C: 512x768, 10 steps. seq = (512/16)*(768/16) = 32*48 = 1536. ──
    var seqC = krea2_packed_seq_len(512, 768)
    if seqC != 1536:
        raise Error("packed seq 512x768 != 1536")
    var refC: List[Float32] = [
        Float32(1.0), Float32(0.94441432), Float32(0.88305783),
        Float32(0.81498224), Float32(0.73902011), Float32(0.65371668),
        Float32(0.5572359), Float32(0.447227), Float32(0.32063007),
        Float32(0.17338738), Float32(0.0),
    ]
    _check_case("512x768 s10", seqC, 10, Float32(0.635417), refC)

    # ── Case D: creator Turbo recipe, 8 steps and fixed mu=1.15. ──────────────
    var refD: List[Float32] = [
        Float32(1.0), Float32(0.956723727), Float32(0.904530767),
        Float32(0.840348802), Float32(0.759510917), Float32(0.654566803),
        Float32(0.512844102), Float32(0.310901057), Float32(0.0),
    ]
    var tsD = krea2_timesteps(
        seqB, 8, mu_override=Float32(1.15), use_mu_override=True,
    )
    var maxD: Float32 = 0.0
    for i in range(len(tsD)):
        var d = tsD[i] - refD[i]
        if d < 0.0:
            d = -d
        if d > maxD:
            maxD = d
    print("  [turbo 1024x1024 s8 fixed-mu] max_abs =", maxD)
    if maxD > _TOL:
        raise Error("krea2 Turbo fixed-mu schedule mismatch")
    print("  [turbo 1024x1024 s8 fixed-mu] PASS")

    print("[krea2-sampler-smoke] ALL SCHEDULE CASES PASS")
