from serenitymojo.sampling.swarmui_schedules import (
    build_swarm_beta_flux_schedule,
    build_swarm_ddim_flux_schedule,
    build_swarm_exponential_flux_schedule,
    build_swarm_karras_flux_schedule,
    build_swarm_kl_optimal_flux_schedule,
    build_swarm_linear_quadratic_flux_schedule,
    build_swarm_normal_flux_schedule,
    build_swarm_simple_flux_schedule,
)


def _close(actual: Float32, expected: Float32, tol: Float32 = 2.0e-6) raises:
    var diff = actual - expected
    if diff < 0.0:
        diff = -diff
    if diff > tol:
        raise Error(
            String("swarmui schedule mismatch: actual=")
            + String(actual)
            + String(" expected=")
            + String(expected)
        )


def main() raises:
    # Values generated by the bundled creator implementation:
    # scipy.stats.beta.ppf + Comfy ModelSamplingFlux(shift=1.15).
    var s8 = build_swarm_beta_flux_schedule(8)
    if len(s8) != 9:
        raise Error("Swarm beta 8-step schedule must contain 9 sigmas")
    _close(s8[0], 1.0)
    _close(s8[1], 0.981151624)
    _close(s8[2], 0.936775783)
    _close(s8[4], 0.759583971)
    _close(s8[6], 0.402498305)
    _close(s8[7], 0.161048481)
    _close(s8[8], 0.0)

    var s40 = build_swarm_beta_flux_schedule(40)
    if len(s40) != 41:
        raise Error("Swarm beta 40-step schedule must contain 41 sigmas")
    _close(s40[1], 0.998729981)
    _close(s40[10], 0.936775783)
    _close(s40[20], 0.759583971)
    _close(s40[30], 0.402498305)
    _close(s40[39], 0.012835019)
    _close(s40[40], 0.0)

    var simple = build_swarm_simple_flux_schedule(8)
    _close(simple[1], 0.956723727)
    _close(simple[7], 0.310901057)

    var normal = build_swarm_normal_flux_schedule(8)
    _close(normal[1], 0.949890109)
    _close(normal[7], 0.000996524)

    var sgm = build_swarm_normal_flux_schedule(8, sgm=True)
    _close(sgm[1], 0.956738667)
    _close(sgm[7], 0.311441979)

    var ddim = build_swarm_ddim_flux_schedule(8)
    _close(ddim[0], 0.956799425)
    _close(ddim[7], 0.000631366)
    # This non-divisor case is deliberate Comfy behavior: range(1, 10000,
    # 10000//7) yields eight denoise intervals, followed by terminal zero.
    var ddim7 = build_swarm_ddim_flux_schedule(7)
    if len(ddim7) != 9:
        raise Error("Swarm DDIM 7-step request must preserve 8 creator intervals")

    var karras = build_swarm_karras_flux_schedule(8)
    _close(karras[1], 0.486951159)
    _close(karras[7], 0.000315751)

    var exponential = build_swarm_exponential_flux_schedule(8)
    _close(exponential[1], 0.316159633)
    _close(exponential[7], 0.000315751)

    var linear_quadratic = build_swarm_linear_quadratic_flux_schedule(8)
    _close(linear_quadratic[1], 0.99375)
    _close(linear_quadratic[7], 0.421875)

    var kl = build_swarm_kl_optimal_flux_schedule(8)
    _close(kl[1], 0.797547185)
    _close(kl[7], 0.000315751)
    print("swarmui_schedules_smoke ok")
