# ops/tests/loss_fns_parity.mojo — torch parity gate for ops/loss_fns.mojo
# (Tier-1 parity campaign phase T1.A, 2026-06-11). Oracle:
# /tmp/loss_fns_oracle.safetensors, generated by
#   /home/alex/EriDiffusion/.venv_cache/bin/python \
#       serenitymojo/ops/tests/gen_loss_fns_oracle.py
# (n=4096 randn pred/target; torch F32 autograd reference for mse / huber
# δ∈{1.0,0.1} / smooth_l1 β∈{1.0,0.5}; min-SNR-γ=5 weights over 4096 sigmas).
#
# PASS iff |loss diff| <= 1e-6 rel and grad cos >= 0.999999 per fn
# (min-SNR: weights vector cos >= 0.999999 AND max rel diff <= 1e-6).
#
# Build/run (standard test build, see sdpa_masked_backward_parity.mojo):
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/ops/tests/loss_fns_parity.mojo -o /tmp/loss_fns_parity && \
#   /tmp/loss_fns_parity
from std.gpu.host import DeviceContext
from std.math import sqrt
from serenitymojo.tensor import Tensor
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.ops.loss_fns import (
    LossGrad, mse_loss_grad, huber_loss_grad, smooth_l1_loss_grad,
    min_snr_gamma_weight,
)


def _cos(a: List[Float32], b: List[Float32]) -> Float64:
    var dot = 0.0; var na = 0.0; var nb = 0.0
    for i in range(len(a)):
        dot += Float64(a[i])*Float64(b[i]); na += Float64(a[i])**2; nb += Float64(b[i])**2
    return dot/(sqrt(na)*sqrt(nb))


def _rel(got: Float32, exp: Float32) -> Float64:
    var d = Float64(got) - Float64(exp)
    if d < 0.0:
        d = -d
    var m = Float64(exp)
    if m < 0.0:
        m = -m
    if m < 1.0e-30:
        m = 1.0e-30
    return d / m


def _gate_loss_fn(
    name: String, lg: LossGrad, exp_loss: Float32, exp_grad: List[Float32],
    mut ok: Bool,
) raises:
    var lrel = _rel(lg.loss, exp_loss)
    var c = _cos(lg.d_pred, exp_grad)
    var pass_ = lrel <= 1.0e-6 and c >= 0.999999
    print("GATE loss_fns", name, "loss=", lg.loss, "exp=", exp_loss,
          "rel=", lrel, "grad_cos=", c, "PASS" if pass_ else "FAIL")
    ok = ok and pass_


def main() raises:
    var ctx = DeviceContext()
    var fx = ShardedSafeTensors.open("/tmp/loss_fns_oracle.safetensors")
    var pred = Tensor.from_view(fx.tensor_view("pred"), ctx).to_host(ctx)
    var target = Tensor.from_view(fx.tensor_view("target"), ctx).to_host(ctx)
    var ok = True

    # ── mse ──
    var exp_l = Tensor.from_view(fx.tensor_view("mse_loss"), ctx).to_host(ctx)
    var exp_g = Tensor.from_view(fx.tensor_view("mse_grad"), ctx).to_host(ctx)
    _gate_loss_fn("mse", mse_loss_grad(pred, target), exp_l[0], exp_g, ok)

    # ── huber δ=1.0 / δ=0.1 ──
    exp_l = Tensor.from_view(fx.tensor_view("huber_d1_loss"), ctx).to_host(ctx)
    exp_g = Tensor.from_view(fx.tensor_view("huber_d1_grad"), ctx).to_host(ctx)
    _gate_loss_fn("huber_d1", huber_loss_grad(pred, target, Float32(1.0)),
                  exp_l[0], exp_g, ok)
    exp_l = Tensor.from_view(fx.tensor_view("huber_d01_loss"), ctx).to_host(ctx)
    exp_g = Tensor.from_view(fx.tensor_view("huber_d01_grad"), ctx).to_host(ctx)
    _gate_loss_fn("huber_d01", huber_loss_grad(pred, target, Float32(0.1)),
                  exp_l[0], exp_g, ok)

    # ── smooth_l1 β=1.0 / β=0.5 ──
    exp_l = Tensor.from_view(fx.tensor_view("sl1_b1_loss"), ctx).to_host(ctx)
    exp_g = Tensor.from_view(fx.tensor_view("sl1_b1_grad"), ctx).to_host(ctx)
    _gate_loss_fn("smooth_l1_b1", smooth_l1_loss_grad(pred, target, Float32(1.0)),
                  exp_l[0], exp_g, ok)
    exp_l = Tensor.from_view(fx.tensor_view("sl1_b05_loss"), ctx).to_host(ctx)
    exp_g = Tensor.from_view(fx.tensor_view("sl1_b05_grad"), ctx).to_host(ctx)
    _gate_loss_fn("smooth_l1_b05", smooth_l1_loss_grad(pred, target, Float32(0.5)),
                  exp_l[0], exp_g, ok)

    # ── min-SNR-γ weights ──
    var sigmas = Tensor.from_view(fx.tensor_view("minsnr_sigmas"), ctx).to_host(ctx)
    var gamma = Tensor.from_view(fx.tensor_view("minsnr_gamma"), ctx).to_host(ctx)[0]
    var exp_w = Tensor.from_view(fx.tensor_view("minsnr_weights"), ctx).to_host(ctx)
    var got_w = List[Float32]()
    var max_rel = 0.0
    for i in range(len(sigmas)):
        var w = min_snr_gamma_weight(sigmas[i], gamma)
        got_w.append(w)
        var r = _rel(w, exp_w[i])
        if r > max_rel:
            max_rel = r
    var wc = _cos(got_w, exp_w)
    var wpass = wc >= 0.999999 and max_rel <= 1.0e-6
    print("GATE loss_fns min_snr_gamma cos=", wc, "max_rel=", max_rel,
          "PASS" if wpass else "FAIL")
    ok = ok and wpass

    if not ok:
        raise Error("loss_fns parity FAILED")
    print("ALL PASS")
