# ops/tests/masked_loss_parity.mojo — torch parity gate for the T1.E masked
# loss fns (ops/loss_fns.mojo mask_weights / masked_{mse,huber,smooth_l1}_
# loss_grad) + the levers_masked_loss_grad dispatch (training/levers.mojo).
# Oracle: /tmp/masked_loss_oracle.safetensors, generated by
#   /home/alex/EriDiffusion/.venv_cache/bin/python \
#       serenitymojo/ops/tests/gen_masked_loss_oracle.py
# (n=4096 randn pred/target; soft + binary masks; torch-autograd reference
# implementing SimpleTuner common.py:4564/:4694/:4704-4707 loss*mask-before-
# mean and OneTrainer masked_loss.py:11-18 clamp(mask,uw,1) + normalize).
#
# PASS iff |loss diff| <= 1e-6 rel and grad cos >= 0.999999 per case
# (mask_weights: max rel <= 1e-6 vs torch.clamp).
#
# Build/run (standard test build, see loss_fns_parity.mojo):
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/ops/tests/masked_loss_parity.mojo -o /tmp/masked_loss_parity && \
#   /tmp/masked_loss_parity
from std.gpu.host import DeviceContext
from std.math import sqrt
from serenitymojo.tensor import Tensor
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.ops.loss_fns import (
    LossGrad, mask_weights, masked_mse_loss_grad, masked_huber_loss_grad,
    masked_smooth_l1_loss_grad,
)
from serenitymojo.training.levers import levers_masked_loss_grad
from serenitymojo.training.train_config import (
    TrainConfig, LOSS_FN_HUBER,
)


def _cos(a: List[Float32], b: List[Float32]) -> Float64:
    var dot = 0.0; var na = 0.0; var nb = 0.0
    for i in range(len(a)):
        dot += Float64(a[i])*Float64(b[i]); na += Float64(a[i])**2; nb += Float64(b[i])**2
    return dot/(sqrt(na)*sqrt(nb))


def _rel(got: Float32, exp: Float32) -> Float64:
    var d = Float64(got) - Float64(exp)
    if d < 0.0:
        d = -d
    var m = Float64(exp)
    if m < 0.0:
        m = -m
    if m < 1.0e-30:
        m = 1.0e-30
    return d / m


def _gate_case(
    name: String, lg: LossGrad, exp_loss: Float32, exp_grad: List[Float32],
    mut ok: Bool,
) raises:
    var lrel = _rel(lg.loss, exp_loss)
    var c = _cos(lg.d_pred, exp_grad)
    var pass_ = lrel <= 1.0e-6 and c >= 0.999999
    print("GATE masked_loss", name, "loss=", lg.loss, "exp=", exp_loss,
          "rel=", lrel, "grad_cos=", c, "PASS" if pass_ else "FAIL")
    ok = ok and pass_


def main() raises:
    var ctx = DeviceContext()
    var fx = ShardedSafeTensors.open("/tmp/masked_loss_oracle.safetensors")
    var pred = Tensor.from_view(fx.tensor_view("pred"), ctx).to_host(ctx)
    var target = Tensor.from_view(fx.tensor_view("target"), ctx).to_host(ctx)
    var m_soft = Tensor.from_view(fx.tensor_view("mask_soft"), ctx).to_host(ctx)
    var m_bin = Tensor.from_view(fx.tensor_view("mask_bin"), ctx).to_host(ctx)
    var ok = True

    # ── mask_weights vs torch.clamp(mask_soft, 0.2, 1) ──
    var exp_w = Tensor.from_view(
        fx.tensor_view("clamp_soft_uw02"), ctx
    ).to_host(ctx)
    var got_w = mask_weights(m_soft, Float32(0.2))
    var w_max_rel = 0.0
    for i in range(len(got_w)):
        var r = _rel(got_w[i], exp_w[i])
        if r > w_max_rel:
            w_max_rel = r
    var wpass = w_max_rel <= 1.0e-6
    print("GATE masked_loss mask_weights max_rel=", w_max_rel,
          "PASS" if wpass else "FAIL")
    ok = ok and wpass

    # ── pure SimpleTuner semantics: weights == mask (uw=0), no normalize ──
    _gate_case(
        "st_mse_soft",
        masked_mse_loss_grad(pred, target, mask_weights(m_soft, 0.0), False),
        Tensor.from_view(fx.tensor_view("st_mse_soft_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("st_mse_soft_grad"), ctx).to_host(ctx), ok,
    )

    # ── OneTrainer lever cases (uw / normalize) ──
    _gate_case(
        "ot_mse_bin",
        masked_mse_loss_grad(pred, target, mask_weights(m_bin, 0.1), False),
        Tensor.from_view(fx.tensor_view("ot_mse_bin_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_mse_bin_grad"), ctx).to_host(ctx), ok,
    )
    _gate_case(
        "ot_mse_bin_norm",
        masked_mse_loss_grad(pred, target, mask_weights(m_bin, 0.1), True),
        Tensor.from_view(fx.tensor_view("ot_mse_bin_norm_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_mse_bin_norm_grad"), ctx).to_host(ctx), ok,
    )
    _gate_case(
        "ot_huber_d01_bin_norm",
        masked_huber_loss_grad(
            pred, target, mask_weights(m_bin, 0.1), Float32(0.1), True
        ),
        Tensor.from_view(fx.tensor_view("ot_huber_d01_bin_norm_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_huber_d01_bin_norm_grad"), ctx).to_host(ctx), ok,
    )
    _gate_case(
        "ot_huber_d1_soft",
        masked_huber_loss_grad(
            pred, target, mask_weights(m_soft, 0.2), Float32(1.0), False
        ),
        Tensor.from_view(fx.tensor_view("ot_huber_d1_soft_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_huber_d1_soft_grad"), ctx).to_host(ctx), ok,
    )
    _gate_case(
        "ot_sl1_b05_bin_norm",
        masked_smooth_l1_loss_grad(
            pred, target, mask_weights(m_bin, 0.1), Float32(0.5), True
        ),
        Tensor.from_view(fx.tensor_view("ot_sl1_b05_bin_norm_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_sl1_b05_bin_norm_grad"), ctx).to_host(ctx), ok,
    )

    # ── levers dispatch: huber + uw + normalize through TrainConfig ──
    var cfg = TrainConfig.default()
    cfg.masked_training = True
    cfg.loss_fn = LOSS_FN_HUBER
    cfg.huber_delta = Float32(0.1)
    cfg.unmasked_weight = Float32(0.1)
    cfg.normalize_masked_area_loss = True
    cfg.min_snr_gamma_flow = Float32(0.0)
    _gate_case(
        "levers_huber",
        levers_masked_loss_grad(pred, target, m_bin, Float32(0.5), cfg),
        Tensor.from_view(fx.tensor_view("ot_huber_d01_bin_norm_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("ot_huber_d01_bin_norm_grad"), ctx).to_host(ctx), ok,
    )

    # ── levers dispatch + min-SNR-γ flow scaling composed (σ=0.2, γ=5) ──
    var sig = Tensor.from_view(
        fx.tensor_view("levers_snr_sigma"), ctx
    ).to_host(ctx)[0]
    cfg.min_snr_gamma_flow = Tensor.from_view(
        fx.tensor_view("levers_snr_gamma"), ctx
    ).to_host(ctx)[0]
    _gate_case(
        "levers_huber_snr",
        levers_masked_loss_grad(pred, target, m_bin, sig, cfg),
        Tensor.from_view(fx.tensor_view("levers_huber_snr_loss"), ctx).to_host(ctx)[0], Tensor.from_view(fx.tensor_view("levers_huber_snr_grad"), ctx).to_host(ctx), ok,
    )

    if not ok:
        raise Error("masked_loss parity FAILED")
    print("ALL PASS")
