# ops/tests/sdpa_masked_backward_parity.mojo — torch-autograd parity gate for
# sdpa_backward_masked (the HiDream-O1 prefix-causal training primitive,
# 2026-06-11). Oracle: /tmp/sdpa_masked_oracle.safetensors, generated by the
# torch snippet below ([1,96,4,32], ar_len=32 prefix-causal additive mask,
# F32 autograd reference). VERIFIED 2026-06-11: cos >= 1-4e-14 on d_q/d_k/d_v.
#
# Regenerate oracle (any torch venv):
#   B,S,H,Dh=1,96,4,32; ar_len=32; mask[i,j]=-inf/2 where i>=ar_len and j>i
#   and j>=ar_len; scores=q@k^T*scale+mask; autograd through softmax@v;
#   save q/k/v/d_out/mask[H*S,S]/d_q/d_k/d_v (see git log for the script).
#
# Build/run: standard test build + LD_LIBRARY_PATH (see klein_block_parity).
from std.gpu.host import DeviceContext
from serenitymojo.tensor import Tensor
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.ops.attention_backward import sdpa_backward_masked
from std.math import sqrt

def _cos(a: List[Float32], b: List[Float32]) -> Float64:
    var dot = 0.0; var na = 0.0; var nb = 0.0
    for i in range(len(a)):
        dot += Float64(a[i])*Float64(b[i]); na += Float64(a[i])**2; nb += Float64(b[i])**2
    return dot/(sqrt(na)*sqrt(nb))

def main() raises:
    var ctx = DeviceContext()
    var fx = ShardedSafeTensors.open("/tmp/sdpa_masked_oracle.safetensors")
    var q = Tensor.from_view(fx.tensor_view("q"), ctx)
    var k = Tensor.from_view(fx.tensor_view("k"), ctx)
    var v = Tensor.from_view(fx.tensor_view("v"), ctx)
    var mask = Tensor.from_view(fx.tensor_view("mask"), ctx)
    var d_out = Tensor.from_view(fx.tensor_view("d_out"), ctx)
    var g = sdpa_backward_masked[1, 96, 4, 32](q, k, v, mask, d_out, Float32(1.0)/sqrt(Float32(32)), ctx)
    ctx.synchronize()
    var names: List[String] = [String("d_q"), String("d_k"), String("d_v")]
    var ok = True
    for which in range(3):
        var got: List[Float32]
        if which == 0: got = g.d_q.to_host(ctx)
        elif which == 1: got = g.d_k.to_host(ctx)
        else: got = g.d_v.to_host(ctx)
        var exp = Tensor.from_view(fx.tensor_view(names[which]), ctx).to_host(ctx)
        var c = _cos(got, exp)
        var pass_ = c >= 0.99999
        print("GATE sdpa_masked", names[which], "cos=", c, "PASS" if pass_ else "FAIL")
        ok = ok and pass_
    if not ok:
        raise Error("sdpa_backward_masked parity FAILED")
    print("ALL PASS")
