# pipeline/zimage_stage_alina.mojo — local Mojo raw-image stage for Z-Image.
#
# This is the first leg of the production LoRA pipeline:
#
#   raw Alina PNG/JPEG + txt captions
#     -> output/alina_zimage_stage/alina_NNN.safetensors + alina_NNN.txt
#
# The stage tensor contract matches zimage_prepare.mojo:
#
#   image: [1,3,H,W] BF16, RGB, values in [-1,1]
#
# OneTrainer's Alina "512" baseline uses aspect buckets, not square 512 crops.
# The main portrait bucket is 576x448 -> latent [16,72,56]; the video-frame
# sample lands in 704x384 -> latent [16,88,48].
#
# No Python. No Rust. No EriDiffusion cache. The compressed image formats are
# decoded by Mojo FFI into local system image libraries, then resize/crop,
# normalize, tensor creation, and safetensor writing all happen here.
#
# Build/run:
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#     pixi run mojo build -I . \
#       -Xlinker -lpng16 -Xlinker /lib/x86_64-linux-gnu/libturbojpeg.so.0 \
#       serenitymojo/pipeline/zimage_stage_alina.mojo -o /tmp/zimage_stage_alina && \
#     /tmp/zimage_stage_alina

from std.collections import List
from std.gpu.host import DeviceContext
from std.memory import ArcPointer, alloc
from std.os import listdir
from std.sys import argv

from serenitymojo.image.decode import decode_image
from serenitymojo.training.aspect_buckets import (
    AspectBucket, AspectBucketAssignment, default_aspect_ladder,
    generate_aspect_buckets, assign_aspect_bucket,
)
from serenitymojo.io.dtype import STDtype
from serenitymojo.io.ffi import (
    BytePtr,
    O_CREAT,
    O_RDONLY,
    O_TRUNC,
    O_WRONLY,
    sys_close,
    sys_open,
    sys_pread,
    sys_pwrite,
    sys_system,
)
from serenitymojo.io.safetensors_writer import save_safetensors
from serenitymojo.tensor import Tensor


comptime DATA_DIR = "/home/alex/datasets/AlinaAignatova"
comptime STAGE_DIR = "/home/alex/mojodiffusion/output/alina_zimage_stage"
comptime SCALE = 1024
comptime SHIFT = 10

# ── T2.D dynamic aspect bucketing (opt-in `t2d` argv mode; default run is the
# fixed OneTrainer-ladder path above, byte-identical — C13). The bucket SET is
# GENERATED by training/aspect_buckets.mojo (SimpleTuner semantics: closest
# ladder aspect -> resize to an intermediary that keeps the ORIGINAL aspect ->
# center-crop to the bucket canvas) instead of the hardcoded `_bucket_for`
# table. Separate stage dir so the production alina stage is never touched.
comptime STAGE_DIR_T2D = "/home/alex/mojodiffusion/output/alina_zimage_stage_t2d"
comptime T2D_MEGAPIXELS = Float64(0.262144)  # 512x512 budget
comptime T2D_ALIGN = 64  # SimpleTuner aspect_bucket_alignment default; 64 % 16 == 0
                         # satisfies the Z-Image VAE stride(8) x patch(2) constraint

# ── T2.E ControlNet staging (opt-in `cn` argv mode; default run untouched —
# C13). Stages a CONTROL image alongside each training image:
#   <stem>.safetensors          image  [1,3,H,W] BF16 (same contract as default)
#   <stem>.control.safetensors  control image, SAME bucket canvas
#   <stem>.txt                  caption
# Control source = the SAME-NAME image in an optional control dir (a "provided
# second folder", e.g. canny/depth maps rendered offline). When no control dir
# is given the control image IS the training image (identity control — the
# simplest faithful conditioning for training-mechanics gates; documented in
# TIER2_PARITY_CAMPAIGN T2.E). Both images get the SAME OneTrainer-ladder
# bucket (chosen from the TRAINING image) so they align spatially.
comptime STAGE_DIR_CN = "/home/alex/mojodiffusion/output/alina_zimage_stage_cn"


def _sort_strings(mut xs: List[String]):
    for i in range(1, len(xs)):
        var key = xs[i]
        var j = i - 1
        while j >= 0 and xs[j] > key:
            xs[j + 1] = xs[j]
            j -= 1
        xs[j + 1] = key


def _is_image_name(s: String) -> Bool:
    return (
        s.endswith(".png")
        or s.endswith(".PNG")
        or s.endswith(".jpg")
        or s.endswith(".JPG")
        or s.endswith(".jpeg")
        or s.endswith(".JPEG")
    )


def _drop_suffix(s: String, suffix_len: Int) raises -> String:
    var n = s.byte_length() - suffix_len
    if n < 0:
        raise Error("_drop_suffix: suffix longer than string")
    var src = s.as_bytes()
    var out = List[UInt8]()
    for i in range(n):
        out.append(src[i])
    return String(unsafe_from_utf8=out)


def _stem_for_image(name: String) raises -> String:
    if name.endswith(".jpeg") or name.endswith(".JPEG"):
        return _drop_suffix(name, 5)
    return _drop_suffix(name, 4)


def _image_names_in(data_dir: String) raises -> List[String]:
    var raw = listdir(data_dir)
    var xs = List[String]()
    for i in range(len(raw)):
        if _is_image_name(raw[i]):
            xs.append(raw[i])
    _sort_strings(xs)
    return xs^


def _image_names() raises -> List[String]:
    return _image_names_in(String(DATA_DIR))


def _read_text(path: String) raises -> List[UInt8]:
    var fd = sys_open(path, O_RDONLY, Int32(0))
    if fd < 0:
        raise Error(String("caption missing: ") + path)
    var out = List[UInt8]()
    comptime CHUNK = 65536
    var buf = alloc[UInt8](CHUNK)
    var offset = 0
    while True:
        var n = sys_pread(fd, BytePtr(unsafe_from_address=Int(buf)), CHUNK, offset)
        if n < 0:
            buf.free()
            _ = sys_close(fd)
            raise Error(String("caption read failed: ") + path)
        if n == 0:
            break
        for i in range(n):
            out.append(buf[i])
        offset += n
        if n < CHUNK:
            break
    buf.free()
    _ = sys_close(fd)
    return out^


def _write_all(fd: Int, buf: BytePtr, count: Int, offset: Int) raises:
    var done = 0
    while done < count:
        var n = sys_pwrite(fd, buf + done, count - done, offset + done)
        if n < 0:
            raise Error("pwrite failed")
        if n == 0:
            raise Error("pwrite wrote 0 bytes")
        done += n


def _write_text(path: String, bytes: List[UInt8]) raises:
    var fd = sys_open(path, O_WRONLY | O_CREAT | O_TRUNC, Int32(0o644))
    if fd < 0:
        raise Error(String("open caption for write failed: ") + path)
    if len(bytes) > 0:
        var buf = alloc[UInt8](len(bytes))
        for i in range(len(bytes)):
            buf[i] = bytes[i]
        try:
            _write_all(fd, BytePtr(unsafe_from_address=Int(buf)), len(bytes), 0)
        except e:
            buf.free()
            _ = sys_close(fd)
            raise Error(String("caption write failed: ") + String(e))
        buf.free()
    _ = sys_close(fd)


def _stage_name(idx: Int) -> String:
    if idx < 10:
        return String("alina_00") + String(idx)
    if idx < 100:
        return String("alina_0") + String(idx)
    return String("alina_") + String(idx)


def _min_int(a: Int, b: Int) -> Int:
    if a < b:
        return a
    return b


def _max_int(a: Int, b: Int) -> Int:
    if a > b:
        return a
    return b


def _round_div(numer: Int, denom: Int) -> Int:
    return (numer + denom // 2) // denom


def _abs64(x: Float64) -> Float64:
    return x if x >= 0.0 else -x


def _bucket_for(height: Int, width: Int) -> Tuple[Int, Int]:
    # OneTrainer 512 target, quantization=64 automatic buckets.
    var hs = List[Int]()
    var ws = List[Int]()
    hs.append(256); ws.append(1024)
    hs.append(256); ws.append(960)
    hs.append(320); ws.append(896)
    hs.append(320); ws.append(832)
    hs.append(384); ws.append(704)
    hs.append(448); ws.append(640)
    hs.append(448); ws.append(576)
    hs.append(512); ws.append(512)
    hs.append(576); ws.append(448)
    hs.append(640); ws.append(448)
    hs.append(704); ws.append(384)
    hs.append(832); ws.append(320)
    hs.append(896); ws.append(320)
    hs.append(960); ws.append(256)
    hs.append(1024); ws.append(256)

    var aspect = Float64(height) / Float64(width)
    var best = 0
    var best_diff = _abs64(Float64(hs[0]) / Float64(ws[0]) - aspect)
    for i in range(1, len(hs)):
        var d = _abs64(Float64(hs[i]) / Float64(ws[i]) - aspect)
        if d < best_diff:
            best = i
            best_diff = d
    return (hs[best], ws[best])


def _bilinear_u8(
    rgb: List[UInt8],
    width: Int,
    sx0: Int,
    sy0: Int,
    sx1: Int,
    sy1: Int,
    fx: Int,
    fy: Int,
    c: Int,
) -> UInt8:
    var invx = SCALE - fx
    var invy = SCALE - fy
    var p00 = Int(rgb[(sy0 * width + sx0) * 3 + c])
    var p01 = Int(rgb[(sy0 * width + sx1) * 3 + c])
    var p10 = Int(rgb[(sy1 * width + sx0) * 3 + c])
    var p11 = Int(rgb[(sy1 * width + sx1) * 3 + c])
    var top = p00 * invx + p01 * fx
    var bot = p10 * invx + p11 * fx
    var v = (top * invy + bot * fy + (SCALE * SCALE // 2)) // (SCALE * SCALE)
    if v < 0:
        v = 0
    if v > 255:
        v = 255
    return UInt8(v)


def _resize_center_crop_to_tensor_values(
    rgb: List[UInt8],
    width: Int,
    height: Int,
    out_h: Int,
    out_w: Int,
) raises -> List[Float32]:
    if width <= 0 or height <= 0:
        raise Error("decoded image has invalid dimensions")
    if len(rgb) != width * height * 3:
        raise Error("decoded image byte count does not match dimensions")

    # Match OneTrainer's ScaleCropImage behavior without importing MGDS:
    #   1. resize the full source so the selected bucket fits
    #   2. center-crop from that resized image
    # For a 1080x1350 portrait this gives scale_resolution 576x461 and
    # crop_offset (y=0, x=6), matching the OneTrainer cache metadata.
    var scale_h: Int
    var scale_w: Int
    if height * out_w > width * out_h:
        scale_h = _round_div(height * out_w, width)
        scale_w = out_w
    else:
        scale_h = out_h
        scale_w = _round_div(width * out_h, height)
    if scale_h < out_h or scale_w < out_w:
        raise Error("decoded image scale resolution smaller than target bucket")
    var y_offset = (scale_h - out_h) // 2
    var x_offset = (scale_w - out_w) // 2
    var values = List[Float32](capacity=3 * out_h * out_w)

    # NCHW order. Use fixed-point bilinear; this avoids depending on a runtime
    # floating floor implementation and keeps staging deterministic.
    for c in range(3):
        for oy in range(out_h):
            var iy = oy + y_offset
            var src_y_fp = (((2 * iy + 1) * height * SCALE) // (2 * scale_h)) - (SCALE // 2)
            if src_y_fp < 0:
                src_y_fp = 0
            var max_y_fp = (height - 1) * SCALE
            if src_y_fp > max_y_fp:
                src_y_fp = max_y_fp
            var y0 = src_y_fp >> SHIFT
            var fy = src_y_fp - y0 * SCALE
            var y1 = _min_int(y0 + 1, height - 1)
            for ox in range(out_w):
                var ix = ox + x_offset
                var src_x_fp = (((2 * ix + 1) * width * SCALE) // (2 * scale_w)) - (SCALE // 2)
                if src_x_fp < 0:
                    src_x_fp = 0
                var max_x_fp = (width - 1) * SCALE
                if src_x_fp > max_x_fp:
                    src_x_fp = max_x_fp
                var x0 = src_x_fp >> SHIFT
                var fx = src_x_fp - x0 * SCALE
                var x1 = _min_int(x0 + 1, width - 1)
                var px = _bilinear_u8(
                    rgb,
                    width,
                    x0,
                    y0,
                    x1,
                    y1,
                    fx,
                    fy,
                    c,
                )
                values.append(Float32(px) * Float32(2.0 / 255.0) - Float32(1.0))
    return values^


def _resize_crop_explicit_to_tensor_values(
    rgb: List[UInt8],
    width: Int,
    height: Int,
    scale_w: Int,
    scale_h: Int,
    crop_x: Int,
    crop_y: Int,
    out_w: Int,
    out_h: Int,
) raises -> List[Float32]:
    """T2.D bucketed staging: resize the source to an EXPLICIT intermediary
    (scale_w x scale_h, SimpleTuner's original-aspect intermediary) and crop
    the (out_w x out_h) bucket canvas at the given offsets (SimpleTuner
    crop_style="center" offsets, computed by assign_aspect_bucket).

    Same deterministic fixed-point bilinear as
    _resize_center_crop_to_tensor_values; only the scale dims and the crop
    offsets are caller-provided instead of derived."""
    if width <= 0 or height <= 0:
        raise Error("decoded image has invalid dimensions")
    if len(rgb) != width * height * 3:
        raise Error("decoded image byte count does not match dimensions")
    if scale_w < out_w or scale_h < out_h:
        raise Error("t2d stage: intermediary smaller than bucket canvas")
    if crop_x < 0 or crop_y < 0 or crop_x + out_w > scale_w or crop_y + out_h > scale_h:
        raise Error("t2d stage: crop window outside the intermediary")

    var values = List[Float32](capacity=3 * out_h * out_w)
    for c in range(3):
        for oy in range(out_h):
            var iy = oy + crop_y
            var src_y_fp = (((2 * iy + 1) * height * SCALE) // (2 * scale_h)) - (SCALE // 2)
            if src_y_fp < 0:
                src_y_fp = 0
            var max_y_fp = (height - 1) * SCALE
            if src_y_fp > max_y_fp:
                src_y_fp = max_y_fp
            var y0 = src_y_fp >> SHIFT
            var fy = src_y_fp - y0 * SCALE
            var y1 = _min_int(y0 + 1, height - 1)
            for ox in range(out_w):
                var ix = ox + crop_x
                var src_x_fp = (((2 * ix + 1) * width * SCALE) // (2 * scale_w)) - (SCALE // 2)
                if src_x_fp < 0:
                    src_x_fp = 0
                var max_x_fp = (width - 1) * SCALE
                if src_x_fp > max_x_fp:
                    src_x_fp = max_x_fp
                var x0 = src_x_fp >> SHIFT
                var fx = src_x_fp - x0 * SCALE
                var x1 = _min_int(x0 + 1, width - 1)
                var px = _bilinear_u8(rgb, width, x0, y0, x1, y1, fx, fy, c)
                values.append(Float32(px) * Float32(2.0 / 255.0) - Float32(1.0))
    return values^


def _save_stage_tensor(values: List[Float32], out_path: String, out_h: Int, out_w: Int, ctx: DeviceContext) raises:
    var image = Tensor.from_host(values, [1, 3, out_h, out_w], STDtype.BF16, ctx)
    var names = List[String]()
    names.append(String("image"))
    var tensors = List[ArcPointer[Tensor]]()
    tensors.append(ArcPointer(image^))
    save_safetensors(names, tensors, out_path, ctx)


def _stage_t2d_buckets(max_images: Int, data_dir: String, ctx: DeviceContext) raises:
    """T2.D aspect-bucketed staging: GENERATED ladder + SimpleTuner-parity
    assignment (training/aspect_buckets.mojo, gated exact vs SimpleTuner in
    training/tests/aspect_buckets_parity.mojo). Writes to STAGE_DIR_T2D plus
    an aspect_buckets.json manifest documenting the ladder and the per-file
    assignment. Cache tensor schema is UNCHANGED (per-sample keyed tensors;
    bucket membership stays shape-derived at the trainer's peek_key).
    `data_dir` defaults to the Alina set; the optional t2d argv override
    exists for bucket-coverage smokes (e.g. landscape sources)."""
    print("=== Z-Image T2.D stage: GENERATED aspect buckets (SimpleTuner semantics) ===")
    print("  data: ", data_dir)
    print("  stage:", STAGE_DIR_T2D)
    var ladder = default_aspect_ladder()
    var buckets = generate_aspect_buckets(T2D_MEGAPIXELS, T2D_ALIGN, ladder)
    print("  ladder buckets (area=262144 px, align=", T2D_ALIGN, "):")
    for i in range(len(buckets)):
        print(
            "    [", i, "] aspect_x100=", Int(buckets[i].aspect * 100.0 + 0.5),
            " canvas=", buckets[i].width, "x", buckets[i].height,
            " latent=", buckets[i].height // 8, "x", buckets[i].width // 8,
        )
    _ = sys_system(String("mkdir -p ") + String(STAGE_DIR_T2D))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR_T2D) + String("/*.safetensors"))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR_T2D) + String("/*.txt"))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR_T2D) + String("/aspect_buckets.json"))

    var names = _image_names_in(data_dir)
    if len(names) == 0:
        raise Error(String("no PNG/JPEG images found in ") + data_dir)
    var n = len(names)
    if max_images > 0 and max_images < n:
        n = max_images

    var manifest = String("{\n")
    manifest += String('  "schema":"serenity.aspect_buckets.v1",\n')
    manifest += String('  "semantics":"simpletuner closest-aspect + pixel-area + center-crop",\n')
    manifest += String('  "pixel_area":262144,\n')
    manifest += String('  "alignment":') + String(T2D_ALIGN) + String(",\n")
    manifest += String('  "buckets":[')
    for i in range(len(buckets)):
        if i > 0:
            manifest += String(",")
        manifest += (
            String('{"aspect_x100":') + String(Int(buckets[i].aspect * 100.0 + 0.5))
            + String(',"width":') + String(buckets[i].width)
            + String(',"height":') + String(buckets[i].height) + String("}")
        )
    manifest += String("],\n")
    manifest += String('  "samples":[\n')

    for i in range(n):
        var src_name = names[i]
        var stem = _stem_for_image(src_name)
        var src_path = data_dir + String("/") + src_name
        var cap_path = data_dir + String("/") + stem + String(".txt")
        var out_stem = _stage_name(i)
        var out_img = String(STAGE_DIR_T2D) + String("/") + out_stem + String(".safetensors")
        var out_txt = String(STAGE_DIR_T2D) + String("/") + out_stem + String(".txt")

        print("-- stage", i + 1, "/", n, src_name)
        var decoded = decode_image(src_path)
        var asn = assign_aspect_bucket(
            decoded.width, decoded.height, ladder, T2D_MEGAPIXELS, T2D_ALIGN,
        )
        print(
            "   decoded:", decoded.width, "x", decoded.height,
            " -> bucket", asn.bucket_index,
            " canvas:", asn.target_w, "x", asn.target_h,
            " inter:", asn.inter_w, "x", asn.inter_h,
            " crop:(", asn.crop_x, ",", asn.crop_y, ")",
        )
        var values = _resize_crop_explicit_to_tensor_values(
            decoded.rgb, decoded.width, decoded.height,
            asn.inter_w, asn.inter_h, asn.crop_x, asn.crop_y,
            asn.target_w, asn.target_h,
        )
        _save_stage_tensor(values, out_img, asn.target_h, asn.target_w, ctx)
        var caption = _read_text(cap_path)
        _write_text(out_txt, caption)

        if i > 0:
            manifest += String(",\n")
        manifest += (
            String('    {"file":"') + out_stem + String('.safetensors"')
            + String(',"source":"') + src_name + String('"')
            + String(',"source_w":') + String(decoded.width)
            + String(',"source_h":') + String(decoded.height)
            + String(',"bucket":') + String(asn.bucket_index)
            + String(',"target_w":') + String(asn.target_w)
            + String(',"target_h":') + String(asn.target_h)
            + String(',"inter_w":') + String(asn.inter_w)
            + String(',"inter_h":') + String(asn.inter_h)
            + String(',"crop_x":') + String(asn.crop_x)
            + String(',"crop_y":') + String(asn.crop_y) + String("}")
        )

    manifest += String("\n  ]\n}\n")
    var manifest_bytes = List[UInt8]()
    var mb = manifest.as_bytes()
    for i in range(manifest.byte_length()):
        manifest_bytes.append(mb[i])
    _write_text(String(STAGE_DIR_T2D) + String("/aspect_buckets.json"), manifest_bytes)
    print("PASS: wrote", n, "T2.D bucketed stage samples to", STAGE_DIR_T2D)


def _stage_cn(max_images: Int, data_dir: String, control_dir: String, ctx: DeviceContext) raises:
    """T2.E control-conditioned staging (see STAGE_DIR_CN comment above)."""
    print("=== Z-Image T2.E cn stage: image + control image -> stage tensors ===")
    print("  data:   ", data_dir)
    print("  control:", control_dir, " (identity control when == data dir)")
    print("  stage:  ", STAGE_DIR_CN)
    _ = sys_system(String("mkdir -p ") + String(STAGE_DIR_CN))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR_CN) + String("/*.safetensors"))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR_CN) + String("/*.txt"))

    var names = _image_names_in(data_dir)
    if len(names) == 0:
        raise Error(String("no PNG/JPEG images found in ") + data_dir)
    var n = len(names)
    if max_images > 0 and max_images < n:
        n = max_images

    for i in range(n):
        var src_name = names[i]
        var stem = _stem_for_image(src_name)
        var src_path = data_dir + String("/") + src_name
        var ctl_path = control_dir + String("/") + src_name
        var cap_path = data_dir + String("/") + stem + String(".txt")
        var out_stem = _stage_name(i)
        var out_img = String(STAGE_DIR_CN) + String("/") + out_stem + String(".safetensors")
        var out_ctl = String(STAGE_DIR_CN) + String("/") + out_stem + String(".control.safetensors")
        var out_txt = String(STAGE_DIR_CN) + String("/") + out_stem + String(".txt")

        print("-- stage", i + 1, "/", n, src_name)
        var decoded = decode_image(src_path)
        # bucket chosen from the TRAINING image; the control image is staged to
        # the SAME canvas (spatial alignment is the ControlNet contract).
        var bucket = _bucket_for(decoded.height, decoded.width)
        var out_h = bucket[0]
        var out_w = bucket[1]
        print("   decoded:", decoded.width, "x", decoded.height, " bucket:", out_h, "x", out_w)
        var values = _resize_center_crop_to_tensor_values(
            decoded.rgb, decoded.width, decoded.height, out_h, out_w,
        )
        _save_stage_tensor(values, out_img, out_h, out_w, ctx)
        var ctl_decoded = decode_image(ctl_path)
        var ctl_values = _resize_center_crop_to_tensor_values(
            ctl_decoded.rgb, ctl_decoded.width, ctl_decoded.height, out_h, out_w,
        )
        _save_stage_tensor(ctl_values, out_ctl, out_h, out_w, ctx)
        var caption = _read_text(cap_path)
        _write_text(out_txt, caption)
        print("   wrote:", out_img, " + control sibling")

    print("PASS: wrote", n, "Z-Image cn stage samples to", STAGE_DIR_CN)


def main() raises:
    var ctx = DeviceContext()
    var a = argv()
    if len(a) >= 2 and String(a[1]) == String("cn"):
        # cn [max_images] [data_dir] [control_dir] — T2.E control staging.
        var max_images_cn = 0
        if len(a) >= 3:
            var s = String(a[2])
            var bs = s.as_bytes()
            for i in range(s.byte_length()):
                if bs[i] < 0x30 or bs[i] > 0x39:
                    raise Error("cn max_images must be a non-negative integer")
                max_images_cn = max_images_cn * 10 + Int(bs[i] - 0x30)
        var data_dir_cn = String(DATA_DIR)
        if len(a) >= 4:
            data_dir_cn = String(a[3])
        var control_dir_cn = data_dir_cn.copy()
        if len(a) >= 5:
            control_dir_cn = String(a[4])
        _stage_cn(max_images_cn, data_dir_cn, control_dir_cn, ctx)
        return
    if len(a) >= 2 and String(a[1]) == String("t2d"):
        # t2d [max_images] [data_dir] — data_dir override for bucket-coverage
        # smokes (landscape sources); default = the Alina set.
        var max_images = 0
        if len(a) >= 3:
            var s = String(a[2])
            var bs = s.as_bytes()
            for i in range(s.byte_length()):
                if bs[i] < 0x30 or bs[i] > 0x39:
                    raise Error("t2d max_images must be a non-negative integer")
                max_images = max_images * 10 + Int(bs[i] - 0x30)
        var data_dir = String(DATA_DIR)
        if len(a) >= 4:
            data_dir = String(a[3])
        _stage_t2d_buckets(max_images, data_dir, ctx)
        return
    print("=== Z-Image Alina stage: raw PNG/JPEG -> image safetensors ===")
    print("  data: ", DATA_DIR)
    print("  stage:", STAGE_DIR)
    _ = sys_system(String("mkdir -p ") + String(STAGE_DIR))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR) + String("/*.safetensors"))
    _ = sys_system(String("rm -f ") + String(STAGE_DIR) + String("/*.txt"))

    var names = _image_names()
    if len(names) == 0:
        raise Error(String("no PNG/JPEG images found in ") + String(DATA_DIR))

    for i in range(len(names)):
        var src_name = names[i]
        var stem = _stem_for_image(src_name)
        var src_path = String(DATA_DIR) + String("/") + src_name
        var cap_path = String(DATA_DIR) + String("/") + stem + String(".txt")
        var out_stem = _stage_name(i)
        var out_img = String(STAGE_DIR) + String("/") + out_stem + String(".safetensors")
        var out_txt = String(STAGE_DIR) + String("/") + out_stem + String(".txt")

        print("-- stage", i + 1, "/", len(names), src_name)
        var decoded = decode_image(src_path)
        var bucket = _bucket_for(decoded.height, decoded.width)
        var out_h = bucket[0]
        var out_w = bucket[1]
        print("   decoded:", decoded.width, "x", decoded.height, " bucket:", out_h, "x", out_w)
        var values = _resize_center_crop_to_tensor_values(decoded.rgb, decoded.width, decoded.height, out_h, out_w)
        _save_stage_tensor(values, out_img, out_h, out_w, ctx)
        var caption = _read_text(cap_path)
        _write_text(out_txt, caption)
        print("   wrote:", out_img)

    print("PASS: wrote", len(names), "Z-Image stage samples to", STAGE_DIR)
