# serenitymojo/training/train_ernie_real.mojo
#
# ERNIE-Image REAL LoRA training loop (pure Mojo). TRANSLATION of the working
# Rust trainer:
#   EriDiffusion-v2/crates/eridiffusion-cli/src/bin/train_ernie.rs
#
# Pipeline per step (mirrors train_ernie.rs:853-1130 + BaseErnieSetup.py predict):
#   1. Load a cached sample produced by prepare_ernie.rs:
#        latent          [1,128,32,32]  (read back as BF16 runtime carrier)
#        text_embedding  [1,512,3072]   (read back as BF16 runtime carrier)
#        text_real_len   [1]                (real token count, pre-pad)
#   2. latent -> img_tokens [N_IMG,128]  (NCHW->NHWC pack; N_IMG = 32*32 = 1024)
#      text   -> txt_tokens [N_TXT,3072] (fixed comptime trim to N_TXT rows of the cache)
#   3. Sample sigma per LOGIT_NORMAL(bias=0,scale=1); shift=1 -> identity (train_ernie.rs:904).
#        sigma_idx = floor(logit_normal * 1000) in [0,999];  sigma = (idx+1)/1000.
#        noisy  = noise*sigma + latent*(1-sigma)             (flow-match; rectified flow)
#        target = noise - latent                             (train_ernie.rs:949)
#   4. timestep fed to the DiT = sigma_idx (INTEGER-valued; train_ernie.rs:956 — NOT /1000).
#   5. Build the shared-AdaLN source ONCE from the resident base weights + the timestep
#        (the deferred E2/E5 link): c = time_embed(sigma_idx);
#        mv = chunk6(silu(c)@adaLN_modulation.1 + bias);
#        [f_scale,f_shift] = chunk2(c@final_norm.linear + bias).
#   6. ernie_stack_lora_forward_resident_device -> pred [N_IMG,128]  (BF16 block-resident path).
#   7. loss = mean MSE(pred, target) in F32;  d_loss = (2/N)*(pred - target).
#   8. ernie_stack_lora_backward_resident_device -> LoRA d_A/d_B for all 7*36 adapters.
#   9. host global-L2-norm clip (max_norm = 1.0; train_ernie.rs:1072) -> ernie_lora_adamw_step.
#  10. save_ernie_lora at the end (PEFT/ai-toolkit keys, inference-loadable).
#
# Per-step line (stdout):
#   [Ernie-lora] step k/total | epoch e/E | loss ... | grad_norm ... | ...s/step | elapsed ... | ETA ...
#
# WHY BF16-RESIDENT: 36 F32 blocks ~= 31 GB > 24 GB 3090, but ERNIE's released
# block matrices are BF16 on disk. Keeping large block matrices BF16 and only
# norm vectors F32 fits the local 3090 target and removes per-step block reloads.
#
# The train loop consumes the existing BoxJana ERNIE cache, but validation prompt
# sidecars are generated by the pure-Mojo Mistral3B encoder:
#   pipeline/ernie_precache_sample_prompts.mojo
#
# Run (SEPARATE command, after build):
#   cd /home/alex/mojodiffusion
#   rm -f serenitymojo.mojopkg
#   pixi run mojo build -I . -Xlinker -lm \
#       serenitymojo/training/train_ernie_real.mojo -o /tmp/train_ernie_real
#   /tmp/train_ernie_real

from std.sys import argv
from std.gpu.host import DeviceContext
from std.collections import List, Optional
from std.math import sqrt, log as flog, exp as fexp, isfinite, sin as fsin, cos as fcos
from std.memory import ArcPointer
from std.time import perf_counter

from serenitymojo.tensor import Tensor
from serenitymojo.io.dtype import STDtype
from serenitymojo.io.safetensors import SafeTensors
from serenitymojo.io.ffi import sys_system
from serenitymojo.io.tensor_view import from_parts
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.ops.linear import linear
from serenitymojo.ops.activations import silu
from serenitymojo.ops.embeddings import timestep_embedding_sin_first

from serenitymojo.models.dit.ernie_image import build_ernie_rope_tables
from serenitymojo.models.ernie.weights import (
    ErnieBlockWeights, ErnieStackBase,
    load_ernie_stack_base, load_ernie_all_blocks_bf16_normf32,
)
from serenitymojo.models.ernie.block import ErnieModVecs
from serenitymojo.models.ernie.lora_block import ERNIE_SLOTS
from serenitymojo.models.ernie.ernie_stack_lora import (
    ErnieLoraSet, ErnieLoraGrads, build_ernie_lora_set,
    ernie_lora_set_to_device,
    ernie_stack_lora_forward_resident_device, ernie_stack_lora_backward_resident_device,
    ernie_lora_adamw_step, save_ernie_lora,
    save_ernie_lora_state, load_ernie_lora_state,
)
from serenitymojo.io.train_config_reader import read_model_config
from serenitymojo.training.train_config import TrainConfig
from serenitymojo.training.onetrainer_cache_preflight import (
    create_onetrainer_cache_preflight_plan,
    validate_onetrainer_cache_preflight_plan,
)
from serenitymojo.training.sample_prompt_config import (
    SamplePrompt, SamplePromptConfig, SampleCadence,
    read_sample_prompt_config, read_sample_cadence_config,
    validate_step_sample_cadence, should_sample_completed_step,
    sample_time_unit_name,
    SAMPLE_UNIT_STEP, SAMPLE_UNIT_NEVER,
)
from serenitymojo.training.onetrainer_train_loop_policy import (
    OT_GRAD_POLICY_ON_OR_OFF,
    ot_cache_dir_from_train_config,
    ot_fixed_output_lora_path_from_train_config,
    ot_lr_for_optimizer_step,
    ot_sample_cadence_from_train_config,
    ot_sampling_enabled_checked,
    ot_should_save_before_sample,
    ot_should_save_checkpoint,
    ot_state_path_for_lora,
    ot_step_lora_path,
    validate_ot_gradient_checkpointing_policy,
    validate_ot_train_math_policy,
)
from serenitymojo.training.progress_display import print_trainer_progress
from serenitymojo.training.ernie_validation_sampler import (
    generate_ernie_lora_shift_pair, load_ernie_sample_text_tokens,
)

comptime TArc = ArcPointer[Tensor]

# ── REAL ERNIE dims (TRAINING_PLAN_ernie.md / ernie_contract.mojo) ────────────
comptime H = 32
comptime Dh = 128
comptime D = H * Dh            # 4096
comptime F = 12288             # REAL FFN hidden
comptime IN_CH = 128           # REAL latent channels
comptime TEXT_IN = 3072        # REAL Mistral hidden (text_in_dim)
comptime OUT_CH = 128          # REAL out channels
comptime NUM_LAYERS = 36       # REAL depth
comptime EPS = Float32(1e-06)

# ── cache geometry: latent [1,128,32,32] -> 32x32 = 1024 image tokens ─────────
comptime IMG_H = 32
comptime IMG_W = 32
comptime N_IMG = IMG_H * IMG_W     # 1024
# Fixed comptime text trim. The cache pads text to 512 with PAD-embedding rows
# (the model was trained to see real-tokens + the trim). The observed real_len
# in this cache is <= ~256, so a 256-row trim keeps every real token plus a
# little pad — and bounds the per-block SDPA scores [H, S, S] on the 3090.
comptime N_TXT = 256
comptime S = N_IMG + N_TXT         # 1280

# ── runtime paths; recipe/cadence scalars come from CONFIG_PATH ───────────────
comptime CACHE_DIR = "/home/alex/EriDiffusion/EriDiffusion-v2/cache/boxjana_ernie_512_FIXED"
comptime NUM_TRAIN_TIMESTEPS = 1000
comptime SEED = UInt64(42)         # train_ernie.rs SEED
comptime SAVE_PATH = "/home/alex/mojodiffusion/serenitymojo/output/ernie_lora_real.safetensors"
comptime CONFIG_PATH = "/home/alex/mojodiffusion/serenitymojo/configs/ernie_image.json"
comptime SAMPLE_OUT_DIR = "/home/alex/mojodiffusion/serenitymojo/output"


# ─────────────────────────────────────────────────────────────────────────────
# cache reading: a single safetensors tensor -> device Tensor in stored dtype.
# Cache readback stays BF16; existing token math casts locally to F32 compute lists.
# ─────────────────────────────────────────────────────────────────────────────
def _read_cache_tensor(st: SafeTensors, name: String, ctx: DeviceContext) raises -> Tensor:
    var info = st.tensor_info(name)
    var bytes = st.tensor_bytes(name)
    var tv = from_parts(info.dtype, info.shape.copy(), bytes)
    return Tensor.from_view(tv, ctx)


def _cache_dims(st: SafeTensors, name: String) raises -> List[Int]:
    var info = st.tensor_info(name)
    var out = List[Int]()
    for i in range(len(info.shape)):
        out.append(Int(info.shape[i]))
    return out^


def _cache_has(st: SafeTensors, name: String) -> Bool:
    var ns = st.names()
    for i in range(len(ns)):
        if ns[i] == name:
            return True
    return False


# ── list cache files (sorted, like the Rust trainer cache_files.sort()) ───────
from std.os import listdir
def _list_cache(dir: String) raises -> List[String]:
    var raw = listdir(dir)
    var out = List[String]()
    for i in range(len(raw)):
        if raw[i].endswith(".safetensors"):
            out.append(dir + String("/") + raw[i])
    # insertion sort (deterministic order, mirrors cache_files.sort())
    for i in range(1, len(out)):
        var key = out[i]
        var j = i - 1
        while j >= 0 and out[j] > key:
            out[j + 1] = out[j]
            j -= 1
        out[j + 1] = key
    return out^


# ─────────────────────────────────────────────────────────────────────────────
# latent [1,128,H,W] (NCHW) -> img_tokens [N_IMG, IN_CH] (NHWC, row=token, col=channel)
# Mirrors the Rust patch_embed reshape: [B,C,H,W] -> reshape [B,C,H*W] -> permute
# [B,H*W,C]. With B=1: token t (= r*W + c), channel ch -> latent[ch*H*W + t].
# ─────────────────────────────────────────────────────────────────────────────
def _latent_to_img_tokens(latent: List[BFloat16]) -> List[Float32]:
    var out = List[Float32]()
    var hw = IMG_H * IMG_W
    for t in range(hw):
        for ch in range(IN_CH):
            out.append(latent[ch * hw + t].cast[DType.float32]())
    return out^


# ── trim/pad cached text [1, T, 3072] -> [N_TXT, 3072] rows ───────────────────
def _text_to_txt_tokens(text: List[BFloat16], t_cache: Int) -> List[Float32]:
    var out = List[Float32]()
    for r in range(N_TXT):
        if r < t_cache:
            for c in range(TEXT_IN):
                out.append(text[r * TEXT_IN + c].cast[DType.float32]())
        else:
            for _c in range(TEXT_IN):
                out.append(Float32(0.0))   # beyond cache rows (unreachable; cache T=512)
    return out^


# ─────────────────────────────────────────────────────────────────────────────
# host helpers
# ─────────────────────────────────────────────────────────────────────────────
def _zeros(n: Int) -> List[Float32]:
    var o = List[Float32]()
    for _ in range(n):
        o.append(0.0)
    return o^


def _l2(h: List[Float32]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = Float64(h[i])
        s += x * x
    return s


def _abs_sum(h: List[Float32]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = h[i]
        s += Float64(x) if x >= 0.0 else Float64(-x)
    return s


def _abs_sum(h: List[BFloat16]) -> Float64:
    var s = Float64(0.0)
    for i in range(len(h)):
        var x = h[i].cast[DType.float32]()
        s += Float64(x) if x >= 0.0 else Float64(-x)
    return s


def _scale_inplace(mut h: List[Float32], s: Float32):
    for i in range(len(h)):
        h[i] = h[i] * s


def _count_nonfinite(v: List[Float32]) -> Int:
    var bad = 0
    for i in range(len(v)):
        if not isfinite(v[i]):
            bad += 1
    return bad


# ── deterministic gaussian noise (Box-Muller on a PCG stream), F32 ────────────
def _host_noise(n: Int, seed: UInt64) -> List[Float32]:
    var out = List[Float32]()
    var state = seed
    var have = False
    var spare = Float32(0.0)
    for _ in range(n):
        if have:
            out.append(spare)
            have = False
            continue
        # two uniforms in (0,1]
        state = state * 6364136223846793005 + 1442695040888963407
        var u1 = (Float32(Int(state >> 40)) + 1.0) * Float32(1.0 / 16777217.0)
        state = state * 6364136223846793005 + 1442695040888963407
        var u2 = Float32(Int(state >> 40)) * Float32(1.0 / 16777216.0)
        var r = sqrt(Float32(-2.0) * flog(u1))
        var theta = Float32(6.283185307179586) * u2
        out.append(r * fcos(theta))
        spare = r * fsin(theta)
        have = True
    return out^


# ── logit-normal timestep sample (train_ernie.rs sample_timestep_logit_normal) ─
# z ~ Normal(0,1); ln = sigmoid(z); t = ln * 1000; shift=1 -> identity.
# Returns sigma_idx in [0, 999] plus the advanced RNG state.
def _sample_sigma_idx(state0: UInt64) -> Tuple[Int, UInt64]:
    # one Box-Muller normal sample
    var state = state0
    state = state * 6364136223846793005 + 1442695040888963407
    var u1 = (Float32(Int(state >> 40)) + 1.0) * Float32(1.0 / 16777217.0)
    state = state * 6364136223846793005 + 1442695040888963407
    var u2 = Float32(Int(state >> 40)) * Float32(1.0 / 16777216.0)
    var z = sqrt(Float32(-2.0) * flog(u1)) * fcos(Float32(6.283185307179586) * u2)
    var ln = Float32(1.0) / (Float32(1.0) + fexp(-z))
    var t = ln * Float32(NUM_TRAIN_TIMESTEPS)   # shift=1 -> identity
    var idx = Int(t)                            # floor
    if idx < 0:
        idx = 0
    if idx > NUM_TRAIN_TIMESTEPS - 1:
        idx = NUM_TRAIN_TIMESTEPS - 1
    return (idx, state)


# ─────────────────────────────────────────────────────────────────────────────
# shared-AdaLN SOURCE (the deferred E2/E5 link). Built from the RESIDENT base
# weights + sigma_idx. Mirrors ernie_image.mojo time_embed/shared_adaln + the
# final-norm chunk, and ernie_image.rs:519-552. Sinusoid math is F32, then
# cast to the resident time-weight dtype before the MLP.
#   c   = linear2(silu(linear1(timestep_embedding_sin_first(idx))))
#   mv  = chunk6(silu(c) @ adaln_w + adaln_b)
#   fs  = chunk2(c @ final_norm_w + final_norm_b)  -> [f_scale, f_shift]
# Returns (mv, f_scale, f_shift). NOTE the timestep fed = sigma_idx (integer),
# matching train_ernie.rs:956 (NOT sigma*1000).
# ─────────────────────────────────────────────────────────────────────────────
def _chunk(src: List[Float32], idx: Int, width: Int) -> List[Float32]:
    var o = List[Float32]()
    var off = idx * width
    for i in range(width):
        o.append(src[off + i])
    return o^


def _shared_adaln_source(
    base: ErnieStackBase, sigma_idx: Int, ctx: DeviceContext
) raises -> Tuple[ErnieModVecs, List[Float32], List[Float32]]:
    var ts = List[Float32]()
    ts.append(Float32(sigma_idx))
    var ts_t = Tensor.from_host(ts, [1], STDtype.F32, ctx)
    var emb_in = timestep_embedding_sin_first(
        ts_t, D, ctx, 10000.0, base.te_w1[].dtype()
    )
    var h1 = linear(emb_in, base.te_w1[], Optional[Tensor](base.te_b1[].clone(ctx)), ctx)
    h1 = silu(h1, ctx)
    var c = linear(h1, base.te_w2[], Optional[Tensor](base.te_b2[].clone(ctx)), ctx)  # [1,D]

    # shared adaLN: silu(c) @ adaln_w + adaln_b -> [1, 6D]
    var sc = silu(c, ctx)
    var adaln = linear(sc, base.adaln_w[], Optional[Tensor](base.adaln_b[].clone(ctx)), ctx)
    var adaln_h = adaln.to_host(ctx)   # [6D]

    # final-norm source: c @ final_norm_w + final_norm_b -> [1, 2D]
    var fmod = linear(c, base.final_norm_w[], Optional[Tensor](base.final_norm_b[].clone(ctx)), ctx)
    var fmod_h = fmod.to_host(ctx)     # [2D]

    # chunk6 the 6D modulation in order: shift_msa,scale_msa,gate_msa,shift_mlp,scale_mlp,gate_mlp
    var mv = ErnieModVecs(
        _chunk(adaln_h, 0, D), _chunk(adaln_h, 1, D), _chunk(adaln_h, 2, D),
        _chunk(adaln_h, 3, D), _chunk(adaln_h, 4, D), _chunk(adaln_h, 5, D),
    )
    var f_scale = _chunk(fmod_h, 0, D)
    var f_shift = _chunk(fmod_h, 1, D)
    return (mv^, f_scale^, f_shift^)


# ── global L2 norm over the flat LoRA grads (clip basis) ──────────────────────
def _grad_global_norm(grads: ErnieLoraGrads) -> Float64:
    var ss = Float64(0.0)
    for i in range(len(grads.d_a)):
        ss += _l2(grads.d_a[i])
        ss += _l2(grads.d_b[i])
    return sqrt(ss)


def _clip_grads(mut grads: ErnieLoraGrads, max_norm: Float32) -> Float64:
    var gn = _grad_global_norm(grads)
    if gn <= Float64(max_norm) or gn == 0.0:
        return gn
    var s = Float32(Float64(max_norm) / gn)
    for i in range(len(grads.d_a)):
        _scale_inplace(grads.d_a[i], s)
        _scale_inplace(grads.d_b[i], s)
    return gn


# ── LoRA-B absolute-sum (across all adapters): the "is it learning?" probe ────
def _lora_b_abs_sum(set: ErnieLoraSet) -> Float64:
    var s = Float64(0.0)
    for i in range(len(set.ad)):
        s += _abs_sum(set.ad[i].b)
    return s


def _lora_b_nonzero_slots(set: ErnieLoraSet) -> Int:
    var n = 0
    for i in range(len(set.ad)):
        if _abs_sum(set.ad[i].b) > 0.0:
            n += 1
    return n


def _parse_int(s: String) -> Int:
    var out = 0
    var bytes = s.as_bytes()
    for i in range(s.byte_length()):
        out = out * 10 + Int(bytes[i] - 0x30)
    return out


def _state_path_for_lora(lora_path: String) -> String:
    return ot_state_path_for_lora(lora_path)


def _substr(s: String, start: Int, end: Int) -> String:
    var out = String("")
    var i = 0
    for ch in s.codepoint_slices():
        if i >= start and i < end:
            out += String(ch)
        i += 1
    return out^


def _dirname(path: String) -> String:
    var last = -1
    var i = 0
    for ch in path.codepoint_slices():
        if String(ch) == String("/"):
            last = i
        i += 1
    if last <= 0:
        return String(".")
    return _substr(path, 0, last)


def _mkdir_parent(path: String):
    _ = sys_system(String("mkdir -p ") + _dirname(path))


def _step_lora_path(save_path: String, step: Int) -> String:
    return ot_step_lora_path(save_path, step)


def validate_ernie_train_config(cfg: TrainConfig) raises:
    if cfg.name != String("ernie_image"):
        raise Error(String("ERNIE trainer config requires model_type=ernie_image, got ") + cfg.name)
    if cfg.checkpoint == String(""):
        raise Error("ERNIE trainer config must set checkpoint")
    if cfg.n_heads != H:
        raise Error(String("ERNIE config num_heads ") + String(cfg.n_heads) + String(" != H ") + String(H))
    if cfg.head_dim != Dh:
        raise Error(String("ERNIE config head_dim ") + String(cfg.head_dim) + String(" != Dh ") + String(Dh))
    if cfg.d_model != D:
        raise Error(String("ERNIE config inner_dim ") + String(cfg.d_model) + String(" != D ") + String(D))
    if cfg.in_channels != IN_CH:
        raise Error(String("ERNIE config in_channels ") + String(cfg.in_channels) + String(" != IN_CH ") + String(IN_CH))
    if cfg.joint_attention_dim != TEXT_IN:
        raise Error(
            String("ERNIE config joint_attention_dim ")
            + String(cfg.joint_attention_dim) + String(" != TEXT_IN ") + String(TEXT_IN)
        )
    if cfg.out_channels != OUT_CH:
        raise Error(String("ERNIE config out_channels ") + String(cfg.out_channels) + String(" != OUT_CH ") + String(OUT_CH))
    if cfg.num_double != 0 or cfg.num_single != NUM_LAYERS:
        raise Error(
            String("ERNIE trainer requires 0 double-stream blocks and ")
            + String(NUM_LAYERS) + String(" single blocks; got double=")
            + String(cfg.num_double) + String(" single=") + String(cfg.num_single)
        )
    if cfg.mlp_hidden != F:
        raise Error(String("ERNIE config mlp_hidden ") + String(cfg.mlp_hidden) + String(" != F ") + String(F))
    if cfg.timestep_dim != D:
        raise Error(String("ERNIE config timestep_dim ") + String(cfg.timestep_dim) + String(" != D ") + String(D))
    if cfg.timestep_shift != Float32(1.0):
        raise Error("ERNIE trainer currently implements timestep_shift=1.0 only")
    if cfg.lora_rank <= 0:
        raise Error("ERNIE trainer config requires lora_rank > 0")
    if cfg.lora_alpha <= Float32(0.0):
        raise Error("ERNIE trainer config requires lora_alpha > 0")
    if cfg.lr <= Float32(0.0):
        raise Error("ERNIE trainer config requires learning_rate > 0")
    if cfg.max_grad_norm <= Float32(0.0):
        raise Error("ERNIE trainer config requires max_grad_norm > 0")
    validate_ot_train_math_policy(cfg, String("ERNIE trainer"))
    if cfg.max_steps <= 0:
        raise Error("ERNIE trainer config requires max_steps > 0")
    if cfg.save_every < 0:
        raise Error("ERNIE trainer config requires save_every >= 0")
    validate_ot_gradient_checkpointing_policy(
        cfg, String("ERNIE trainer"), OT_GRAD_POLICY_ON_OR_OFF
    )


def ernie_sample_cadence_from_train_config(
    cfg_path: String, cfg: TrainConfig,
) raises -> SampleCadence:
    return ot_sample_cadence_from_train_config(cfg_path, cfg)


def ernie_sampling_enabled(cadence: SampleCadence) raises -> Bool:
    return ot_sampling_enabled_checked(cadence)


def ernie_should_save_checkpoint(cfg: TrainConfig, completed_step: Int) -> Bool:
    return ot_should_save_checkpoint(cfg, completed_step)


def ernie_should_save_before_sample(
    cadence: SampleCadence, completed_step: Int, saved_this_step: Bool,
) raises -> Bool:
    return ot_should_save_before_sample(cadence, completed_step, saved_this_step)


def _sample_png_path(step: Int, label: String) -> String:
    return (
        String(SAMPLE_OUT_DIR) + String("/ernie_sample_step") + String(step)
        + String("_") + label + String(".png")
    )


def _validate_image_sample_prompt(p: SamplePrompt) raises:
    if p.frames != 1:
        raise Error(String("ERNIE image sampler expects frames=1 for ") + p.label)
    if p.width < 1024 or p.height < 1024:
        raise Error(
            String("ERNIE sample prompt ") + p.label
            + String(" is ") + String(p.width) + String("x") + String(p.height)
            + String("; image validation samples must be 1024x1024 or larger")
        )


def _save_lora_and_state(
    lora: ErnieLoraSet, lora_path: String, step: Int, ctx: DeviceContext
) raises:
    _mkdir_parent(lora_path)
    var npairs = save_ernie_lora(lora, lora_path, ctx)
    print("[Ernie-lora] save step=", step, " path=", lora_path, " pairs=", npairs)
    var state_path = _state_path_for_lora(lora_path)
    var nstate = save_ernie_lora_state(lora, state_path, ctx)
    print("[Ernie-lora] save_state step=", step, " path=", state_path, " pairs=", nstate)


def _sample_ernie_prompt(
    base: ErnieStackBase,
    blocks: List[ErnieBlockWeights],
    baseline_lora: ErnieLoraSet,
    live_lora: ErnieLoraSet,
    p: SamplePrompt,
    step: Int,
    ctx: DeviceContext,
) raises -> Float32:
    _validate_image_sample_prompt(p)
    var txt = load_ernie_sample_text_tokens(p.caps_pos, ctx)
    var out_png = _sample_png_path(step, p.label)
    var diff = generate_ernie_lora_shift_pair(
        base, blocks, baseline_lora, live_lora, txt^, out_png,
        p.width, p.height, p.steps, p.seed, ctx,
    )
    print(
        "[Ernie-lora] sample step=", step, " label=", p.label,
        " size=", p.width, "x", p.height, " path=", out_png,
        " pixel_l1=", diff,
    )
    return diff


def _sample_ernie_prompts(
    base: ErnieStackBase,
    blocks: List[ErnieBlockWeights],
    baseline_lora: ErnieLoraSet,
    live_lora: ErnieLoraSet,
    cfg: SamplePromptConfig,
    step: Int,
    ctx: DeviceContext,
) raises:
    for i in range(len(cfg.prompts)):
        _ = _sample_ernie_prompt(
            base, blocks, baseline_lora, live_lora, cfg.prompts[i].copy(), step, ctx
        )


def main() raises:
    var args = argv()
    var cfg_path = String(CONFIG_PATH)
    var arg_base = 1
    if len(args) >= 2:
        var first = String(args[1])
        if first.endswith(String(".json")):
            cfg_path = first.copy()
            arg_base = 2

    var run_steps = -1
    var mode = String("train")
    if len(args) > arg_base:
        var a1 = String(args[arg_base])
        if a1 == String("resume_smoke") or a1 == String("smoke_resume"):
            mode = String("resume_smoke")
            run_steps = 25
        else:
            run_steps = _parse_int(a1)

    var train_cfg = read_model_config(cfg_path)
    var save_path = ot_fixed_output_lora_path_from_train_config(
        train_cfg, String(SAVE_PATH)
    )
    if len(args) > arg_base + 1:
        save_path = String(args[arg_base + 1])

    var cache_dir = ot_cache_dir_from_train_config(train_cfg, String(CACHE_DIR))
    if len(args) > arg_base + 2:
        cache_dir = String(args[arg_base + 2])

    if len(args) > arg_base + 3:
        mode = String(args[arg_base + 3])

    validate_ernie_train_config(train_cfg)
    var cache_preflight = create_onetrainer_cache_preflight_plan(train_cfg)
    validate_onetrainer_cache_preflight_plan(cache_preflight)
    if run_steps < 0:
        run_steps = train_cfg.max_steps
    if mode == String("resume_smoke") and run_steps < 25:
        run_steps = 25
    if run_steps < 1:
        raise Error("run_steps must be >= 1")

    var sample_cadence = ernie_sample_cadence_from_train_config(cfg_path, train_cfg)
    var sample_enabled = ernie_sampling_enabled(sample_cadence)
    var sample_cfg = SamplePromptConfig()
    if train_cfg.only_cache:
        print("[Ernie-lora] only_cache requested; no train steps will run in this trainer")
        return
    if sample_enabled:
        if sample_cadence.sample_definition_file_name == String(""):
            raise Error("ERNIE trainer sampling requires validation_prompts_file or sample_definition_file_name")
        sample_cfg = read_sample_prompt_config(sample_cadence.sample_definition_file_name)
        if len(sample_cfg.prompts) == 0:
            raise Error("ERNIE trainer requires at least one validation prompt when sampling is enabled")
        _ = sys_system(String("mkdir -p ") + String(SAMPLE_OUT_DIR))

    var ctx = DeviceContext()

    print("==== ERNIE REAL LoRA training loop (pure Mojo) ====")
    print("  D=", D, " H=", H, " Dh=", Dh, " F=", F, " NUM_LAYERS=", NUM_LAYERS)
    print("  N_IMG=", N_IMG, " N_TXT=", N_TXT, " S=", S, " IN_CH=", IN_CH,
          " TEXT_IN=", TEXT_IN, " OUT_CH=", OUT_CH)
    print("  cache=", cache_dir)
    print("  max_steps=", run_steps, " rank=", train_cfg.lora_rank,
          " alpha=", train_cfg.lora_alpha, " lr=", train_cfg.lr)
    print("  mode=", mode)
    print("  save_path=", save_path)
    print("  checkpoint=", train_cfg.checkpoint)
    print(
        "  cadence: save_every=", train_cfg.save_every,
        " sample_after=", sample_cadence.sample_after,
        " unit=", sample_time_unit_name(sample_cadence.sample_after_unit),
        " skip_first=", sample_cadence.sample_skip_first,
        " sample_file=", sample_cadence.sample_definition_file_name,
        " enabled=", sample_enabled,
    )
    if sample_enabled:
        print("  sample_prompts=", sample_cadence.sample_definition_file_name,
              " count=", len(sample_cfg.prompts))

    var mem0 = ctx.get_memory_info()
    print("  free VRAM at start (bytes):", mem0[0], " total:", mem0[1])

    # ── open the real sharded transformer checkpoint (streamed block source) ──
    var st = ShardedSafeTensors.open(train_cfg.checkpoint)
    print("  opened transformer: num_shards =", st.num_shards())
    var base = load_ernie_stack_base(st, D, IN_CH, ctx)
    print("  base weights resident (patch/text/time/adaLN/final).")
    var blocks = load_ernie_all_blocks_bf16_normf32(st, NUM_LAYERS, ctx)
    var mem_blocks = ctx.get_memory_info()
    print("  block weights resident BF16/norm-F32:", len(blocks),
          " free VRAM after block load (bytes):", mem_blocks[0])

    # ── build the LoRA set (B=0 init -> adapter identity at step 0) ──
    var lora = build_ernie_lora_set(NUM_LAYERS, D, F, train_cfg.lora_rank, train_cfg.lora_alpha)
    var baseline_lora = build_ernie_lora_set(NUM_LAYERS, D, F, train_cfg.lora_rank, train_cfg.lora_alpha)
    var n_adapters = NUM_LAYERS * ERNIE_SLOTS
    print("  LoRA adapters:", n_adapters, " (7 slots x", NUM_LAYERS, "layers)")
    print("  LoRA-B |.|_1 at init =", _lora_b_abs_sum(lora), " (expect 0.0)")

    # ── RoPE tables (image-first/text-second 3-axis half-split) ──
    # OneTrainer's image RoPE axis-0 position == the per-sample TEXT real length
    # (transformer_ernie_image.py:388 image_ids axis-0 = text_lens). So the table
    # is rebuilt PER SAMPLE inside the loop with text_len_real = real_len read from
    # the cache (NOT the fixed N_TXT). build_ernie_rope_tables requires real in
    # (0, N_TXT]. (Was: built once with N_TXT — a divergence from OneTrainer.)
    print("  RoPE tables: per-sample, cos/sin [S*H, Dh] = [", S * H, ",", Dh, "]")

    var cache_files = _list_cache(cache_dir)
    if len(cache_files) == 0:
        raise Error("no cache files found")
    print("  found", len(cache_files), "cached samples")

    var last_sample_step = -1
    if sample_enabled and (should_sample_completed_step(sample_cadence, 0) or mode == String("resume_smoke")):
        _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, 0, ctx)
        last_sample_step = 0

    var rng_state = SEED
    var t_start = perf_counter()

    for step in range(run_steps):
        var step_t0 = perf_counter()
        var cache_idx = step % len(cache_files)
        var cs = SafeTensors.open(cache_files[cache_idx])

        var latent_cache = _read_cache_tensor(cs, String("latent"), ctx)
        var latent = latent_cache.to_host_bf16(ctx)                        # [128*32*32]
        var text_cache = _read_cache_tensor(cs, String("text_embedding"), ctx)
        var text = text_cache.to_host_bf16(ctx)                            # [512*3072]
        var tdims = _cache_dims(cs, String("text_embedding"))
        var t_cache = tdims[1]

        var img_tokens = _latent_to_img_tokens(latent)                     # [N_IMG, IN_CH]
        var txt_tokens = _text_to_txt_tokens(text, t_cache)                # [N_TXT, TEXT_IN]

        # ── per-sample real TEXT length (pre-pad token count). OneTrainer trims
        # text to text_lengths.max() and MASKS padded text in attention; the cache
        # stores this real_len. Rows [real_len, N_TXT) are nonzero Mistral PAD
        # embeddings that must NOT attend. Drives both the attention text-pad mask
        # AND the image RoPE axis-0 position (transformer_ernie_image.py:388-401).
        var real_len = N_TXT
        if _cache_has(cs, String("text_real_len")):
            var rl_t = _read_cache_tensor(cs, String("text_real_len"), ctx)
            var rl_h = rl_t.to_host(ctx)
            real_len = Int(rl_h[0])
        if real_len < 1:
            real_len = 1
        if real_len > N_TXT:
            real_len = N_TXT

        # ── RoPE tables for THIS sample (image axis-0 position = real_len) ──
        var rope = build_ernie_rope_tables[N_IMG, N_TXT, H, Dh](
            IMG_H, IMG_W, real_len, ctx, STDtype.BF16
        )

        # ── sigma + flow-match noise/target (F32; train_ernie.rs:904-949) ──
        var sigma_draw = _sample_sigma_idx(rng_state)
        var sigma_idx = sigma_draw[0]
        rng_state = sigma_draw[1]
        var sigma = Float32(sigma_idx + 1) / Float32(NUM_TRAIN_TIMESTEPS)
        var n_lat = N_IMG * IN_CH
        var noise = _host_noise(n_lat, SEED ^ (UInt64(step) + 1))
        # noisy = noise*sigma + latent*(1-sigma)  (image-token space; same packing)
        var target = List[Float32]()
        for i in range(n_lat):
            target.append(noise[i] - img_tokens[i])      # target = noise - latent
        # the DiT input is the NOISY latent tokens (not the clean ones)
        var noisy_tokens = List[Float32]()
        for i in range(n_lat):
            noisy_tokens.append(noise[i] * sigma + img_tokens[i] * (Float32(1.0) - sigma))

        # ── shared-AdaLN source from the resident base + sigma_idx ──
        var src = _shared_adaln_source(base, sigma_idx, ctx)
        var mv = src[0].copy()
        var f_scale = src[1].copy()
        var f_shift = src[2].copy()

        # ── device-resident LoRA forward (BF16 base blocks loaded once) ──
        var lora_dev = ernie_lora_set_to_device(lora, STDtype.BF16, ctx)
        var fwd = ernie_stack_lora_forward_resident_device[H, Dh, N_IMG, N_TXT, S](
            noisy_tokens.copy(), txt_tokens.copy(), base, blocks, lora_dev, mv,
            f_scale.copy(), f_shift.copy(), rope[0], rope[1],
            D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
            real_len,
        )
        var pred = fwd.out.copy()                          # [N_IMG, OUT_CH]

        # ── MSE loss + upstream grad d_loss = (2/N)*(pred - target) ──
        var n_out = N_IMG * OUT_CH
        var sse = Float64(0.0)
        var d_out = List[Float32]()
        var inv_n = Float32(2.0) / Float32(n_out)
        for i in range(n_out):
            var diff = pred[i] - target[i]
            sse += Float64(diff) * Float64(diff)
            d_out.append(diff * inv_n)
        var loss = Float32(sse / Float64(n_out))

        # ── resident LoRA backward -> all 7*36 adapter grads ──
        var grads = ernie_stack_lora_backward_resident_device[H, Dh, N_IMG, N_TXT, S](
            d_out, noisy_tokens.copy(), txt_tokens.copy(), base, blocks, lora_dev, mv,
            f_scale.copy(), f_shift.copy(), rope[0], rope[1], fwd,
            D, F, IN_CH, TEXT_IN, OUT_CH, EPS, ctx,
            real_len,
        )

        # ── global-norm clip then AdamW on every adapter ──
        var gn = _clip_grads(grads, train_cfg.max_grad_norm)
        var done_step = step + 1
        var step_lr = ot_lr_for_optimizer_step(train_cfg, done_step)
        ernie_lora_adamw_step(
            lora, grads, done_step, step_lr, ctx,
            train_cfg.beta1, train_cfg.beta2, train_cfg.eps, train_cfg.weight_decay,
        )

        var now = perf_counter()
        var step_secs = now - step_t0
        var elapsed = now - t_start
        print_trainer_progress(
            String("Ernie-lora"), done_step, run_steps, len(cache_files),
            loss, gn, step_secs, 0.0, elapsed,
        )
        if grads.nonfinite_lora_grads != 0:
            print(
                "[Ernie-lora] nonfinite_lora_grads step=", done_step,
                " count=", grads.nonfinite_lora_grads,
            )

        var saved_this_step = False
        var saved_lora_path = String("")

        if mode == String("resume_smoke") and done_step == 10:
            var smoke_lora = _step_lora_path(save_path, done_step)
            _save_lora_and_state(lora, smoke_lora, done_step, ctx)
            saved_this_step = True
            saved_lora_path = smoke_lora.copy()
            if sample_enabled:
                _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, done_step, ctx)
                last_sample_step = done_step
            var smoke_state = _state_path_for_lora(smoke_lora)
            lora = load_ernie_lora_state(NUM_LAYERS, train_cfg.lora_rank, train_cfg.lora_alpha, smoke_state, ctx)
            print("[Ernie-lora] resume_state step=", done_step, " path=", smoke_state)

        if ernie_should_save_checkpoint(train_cfg, done_step) and not saved_this_step:
            var save_cadence_lora = _step_lora_path(save_path, done_step)
            _save_lora_and_state(lora, save_cadence_lora, done_step, ctx)
            saved_this_step = True
            saved_lora_path = save_cadence_lora.copy()

        if sample_enabled and should_sample_completed_step(sample_cadence, done_step):
            var cadence_lora = _step_lora_path(save_path, done_step)
            if ernie_should_save_before_sample(sample_cadence, done_step, saved_this_step):
                _save_lora_and_state(lora, cadence_lora, done_step, ctx)
                saved_lora_path = cadence_lora.copy()
            _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, done_step, ctx)
            last_sample_step = done_step
            if sample_cadence.save_before_sample and saved_lora_path == cadence_lora:
                var cadence_state = _state_path_for_lora(cadence_lora)
                lora = load_ernie_lora_state(NUM_LAYERS, train_cfg.lora_rank, train_cfg.lora_alpha, cadence_state, ctx)
                print("[Ernie-lora] resume_state step=", done_step, " path=", cadence_state)

    # ── final LoRA-B growth report + save ──
    var b_sum = _lora_b_abs_sum(lora)
    var b_nz = _lora_b_nonzero_slots(lora)
    print("")
    print("==== RESULT ====")
    print("  LoRA-B |.|_1 after training =", b_sum, " (init 0.0)")
    print("  LoRA-B nonzero slots =", b_nz, "/", n_adapters,
          " ratio =", Float32(b_nz) / Float32(n_adapters))
    _save_lora_and_state(lora, save_path, run_steps, ctx)
    if sample_enabled and last_sample_step != run_steps:
        _sample_ernie_prompts(base, blocks, baseline_lora, lora, sample_cfg, run_steps, ctx)
