# training/tests/adamw8bit_parity.mojo — T2.A bnb-oracle parity gate for
# training/adamw8bit.mojo (host math).
#
# Oracle: the bnb 0.49.2 before/after dumps the PROVEN Rust parity suite uses
# (crates/eridiffusion-cli/src/bin/parity_adam8bit_bnb{,_wd,_tail,_bf16grad,
# _multistep}.rs), at
#   /home/alex/EriDiffusion/EriDiffusion-v2/tests/parity/adam8bit_data/
# generated by tests/parity/adam8bit_bnb_python_ref*.py driving the REAL
# bnb.functional.optimizer_update_8bit_blockwise("adam", ...) (bnb 0.49.2,
# torch 2.10.0+cu128, CUDA). Scenarios: basic, weight-decay, tail
# (numel=2050, non-block-multiple), bf16 grads, multistep (10 steps, each
# step gated from bnb's own before-state — the _multistep.rs protocol).
#
# GATES — the EXACT tolerance discipline of the Rust reference bins:
#   LUT (both maps)   : max|Δ| < 1e-7 vs the dumped bnb qmaps   [measured 0.0]
#   basic / wd / tail : param max|Δ| < 1e-5, codes EXACT (0 mismatches both
#                       streams), absmax max|Δ| < 1e-6
#   bf16grad          : param < 1e-3, codes <= 5 per stream, absmax < 1e-4
#                       (parity_adam8bit_bnb_bf16grad.rs: LUT tiebreak drift
#                       near requant boundaries at bf16 grad precision)
#   multistep step 1  : strict (param 1e-5, codes EXACT, absmax 1e-6)
#   multistep 2..10   : param < 5e-5, codes <= 2 per stream, absmax < 1e-5
#                       (parity_adam8bit_bnb_multistep.rs:9-10)
# Hyperparams are the dumps' hyperparams.json: lr=1e-3, beta1=0.9,
# beta2=0.999, eps=1e-8; wd=0.01 for the wd scenario, else 0.
#
# Host-only (no GPU). Modeled on training/tests/optimizer_parity.mojo.
#
# Build/run:
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/training/tests/adamw8bit_parity.mojo \
#     -o /tmp/adamw8bit_parity && /tmp/adamw8bit_parity

from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.training.adamw8bit import (
    ADAMW8BIT_BLOCK_SIZE,
    Adam8bitState,
    adam8bit_create_dynamic_map,
    adam8bit_step_bnb,
)

comptime DATA_DIR = "/home/alex/EriDiffusion/EriDiffusion-v2/tests/parity/adam8bit_data"

# hyperparams.json of every scenario (bnb 0.49.2 dump generation)
comptime LR = Float32(1.0e-3)
comptime BETA1 = Float32(0.9)
comptime BETA2 = Float32(0.999)
comptime EPS = Float32(1.0e-8)

# Rust-bin tolerance constants (see header)
comptime LUT_TOL = Float32(1.0e-7)
comptime PARAM_TOL = Float32(1.0e-5)
comptime ABSMAX_TOL = Float32(1.0e-6)
comptime PARAM_TOL_BF16 = Float32(1.0e-3)
comptime CODE_TOL_BF16 = 5
comptime ABSMAX_TOL_BF16 = Float32(1.0e-4)
comptime PARAM_TOL_MULTI = Float32(5.0e-5)
comptime CODE_TOL_MULTI = 2
comptime ABSMAX_TOL_MULTI = Float32(1.0e-5)


def _load_f32(fx: ShardedSafeTensors, name: String) raises -> List[Float32]:
    var b = fx.tensor_bytes(name)
    var n = len(b) // 4
    var ptr = b.unsafe_ptr().bitcast[Float32]()
    var out = List[Float32](capacity=n)
    for i in range(n):
        out.append(ptr[i])
    return out^


def _load_u8(fx: ShardedSafeTensors, name: String) raises -> List[UInt8]:
    var b = fx.tensor_bytes(name)
    var out = List[UInt8](capacity=len(b))
    for i in range(len(b)):
        out.append(b[i])
    return out^


def _load_bf16_as_f32(
    fx: ShardedSafeTensors, name: String
) raises -> List[Float32]:
    # bf16 -> f32 upcast is exact; mirrors bnb's host g.float() dispatch
    # (and the Rust bf16grad bin's pre-kernel upcast).
    var b = fx.tensor_bytes(name)
    var n = len(b) // 2
    var ptr = b.unsafe_ptr().bitcast[BFloat16]()
    var out = List[Float32](capacity=n)
    for i in range(n):
        out.append(ptr[i].cast[DType.float32]())
    return out^


def _max_abs_diff(a: List[Float32], b: List[Float32]) raises -> Float32:
    if len(a) != len(b):
        raise Error("_max_abs_diff: length mismatch")
    var mx = Float32(0.0)
    for i in range(len(a)):
        var d = a[i] - b[i]
        if d < Float32(0.0):
            d = -d
        if d > mx:
            mx = d
    return mx


def _mismatch_count(a: List[UInt8], b: List[UInt8]) raises -> Int:
    if len(a) != len(b):
        raise Error("_mismatch_count: length mismatch")
    var c = 0
    for i in range(len(a)):
        if a[i] != b[i]:
            c += 1
    return c


def _gate_lut(
    label: String,
    got_s: List[Float32],
    got_u: List[Float32],
    exp_s: List[Float32],
    exp_u: List[Float32],
    mut ok: Bool,
) raises:
    var ds = _max_abs_diff(got_s, exp_s)
    var du = _max_abs_diff(got_u, exp_u)
    var pass_ = ds < LUT_TOL and du < LUT_TOL
    print(
        "GATE adamw8bit", label, "LUT signed_d=", ds, "unsigned_d=", du,
        "(tol 1e-7)", "PASS" if pass_ else "FAIL",
    )
    ok = ok and pass_


def _run_one_step(
    label: String,
    before_path: String,
    after_path: String,
    grad_key: String,
    grad_is_bf16: Bool,
    qmap_s: List[Float32],
    qmap_u: List[Float32],
    step: Int,
    wd: Float32,
    param_tol: Float32,
    code_tol: Int,
    absmax_tol: Float32,
    mut ok: Bool,
) raises:
    var bx = ShardedSafeTensors.open(before_path)
    var ax = ShardedSafeTensors.open(after_path)

    var p = _load_f32(bx, String("before.param"))
    var g: List[Float32]
    if grad_is_bf16:
        g = _load_bf16_as_f32(bx, grad_key)
    else:
        g = _load_f32(bx, grad_key)
    var n = len(p)
    var st = Adam8bitState(n)
    st.m_codes = _load_u8(bx, String("before.state1"))
    st.v_codes = _load_u8(bx, String("before.state2"))
    st.m_absmax = _load_f32(bx, String("before.absmax1"))
    st.v_absmax = _load_f32(bx, String("before.absmax2"))
    var n_blocks = (n + ADAMW8BIT_BLOCK_SIZE - 1) // ADAMW8BIT_BLOCK_SIZE
    if len(st.m_absmax) != n_blocks or len(st.v_absmax) != n_blocks:
        raise Error(label + ": dump absmax block count mismatch")

    adam8bit_step_bnb(
        p, g, st, qmap_s, qmap_u, step, LR, BETA1, BETA2, EPS, wd
    )

    var pd = _max_abs_diff(p, _load_f32(ax, String("after.param")))
    var s1 = _mismatch_count(st.m_codes, _load_u8(ax, String("after.state1")))
    var s2 = _mismatch_count(st.v_codes, _load_u8(ax, String("after.state2")))
    var a1 = _max_abs_diff(st.m_absmax, _load_f32(ax, String("after.absmax1")))
    var a2 = _max_abs_diff(st.v_absmax, _load_f32(ax, String("after.absmax2")))

    var pass_ = (
        pd < param_tol and s1 <= code_tol and s2 <= code_tol
        and a1 < absmax_tol and a2 < absmax_tol
    )
    print(
        "GATE adamw8bit", label, "n=", n,
        "param_d=", pd, "(tol", param_tol, ")",
        "s1_mism=", s1, "s2_mism=", s2, "(tol", code_tol, ")",
        "absmax_d=", a1, "/", a2, "(tol", absmax_tol, ")",
        "PASS" if pass_ else "FAIL",
    )
    ok = ok and pass_


def main() raises:
    var ok = True
    var qmap_s = adam8bit_create_dynamic_map(True)
    var qmap_u = adam8bit_create_dynamic_map(False)

    # ── LUT vs the dumped bnb qmaps (basic scenario carries both) ───────────
    var base = String(DATA_DIR)
    var bx0 = ShardedSafeTensors.open(base + "/before.safetensors")
    _gate_lut(
        String("lut/basic"),
        qmap_s, qmap_u,
        _load_f32(bx0, String("before.qmap1")),
        _load_f32(bx0, String("before.qmap2")),
        ok,
    )

    # ── single-step scenarios (the Rust baseline/_wd/_tail/_bf16grad bins) ──
    _run_one_step(
        String("basic"),
        base + "/before.safetensors", base + "/after.safetensors",
        String("before.grad"), False, qmap_s, qmap_u, 1, Float32(0.0),
        PARAM_TOL, 0, ABSMAX_TOL, ok,
    )
    _run_one_step(
        String("wd"),
        base + "/wd/before.safetensors", base + "/wd/after.safetensors",
        String("before.grad"), False, qmap_s, qmap_u, 1, Float32(0.01),
        PARAM_TOL, 0, ABSMAX_TOL, ok,
    )
    _run_one_step(
        String("tail"),
        base + "/tail/before.safetensors", base + "/tail/after.safetensors",
        String("before.grad"), False, qmap_s, qmap_u, 1, Float32(0.0),
        PARAM_TOL, 0, ABSMAX_TOL, ok,
    )
    _run_one_step(
        String("bf16grad"),
        base + "/bf16grad/before.safetensors",
        base + "/bf16grad/after.safetensors",
        String("before.grad_bf16"), True, qmap_s, qmap_u, 1, Float32(0.0),
        PARAM_TOL_BF16, CODE_TOL_BF16, ABSMAX_TOL_BF16, ok,
    )

    # ── multistep: 10 steps, each from bnb's OWN before-state (the
    # _multistep.rs protocol; the step index is the bias-correction t) ──────
    var qx = ShardedSafeTensors.open(base + "/multistep/qmaps.safetensors")
    _gate_lut(
        String("lut/multistep"),
        qmap_s, qmap_u,
        _load_f32(qx, String("qmap1")),
        _load_f32(qx, String("qmap2")),
        ok,
    )
    for stp in range(1, 11):
        var ptol = PARAM_TOL if stp == 1 else PARAM_TOL_MULTI
        var ctol = 0 if stp == 1 else CODE_TOL_MULTI
        var atol = ABSMAX_TOL if stp == 1 else ABSMAX_TOL_MULTI
        _run_one_step(
            String("multistep/") + String(stp),
            base + "/multistep/step_" + String(stp) + "_before.safetensors",
            base + "/multistep/step_" + String(stp) + "_after.safetensors",
            String("before.grad"), False, qmap_s, qmap_u, stp, Float32(0.0),
            ptol, ctol, atol, ok,
        )

    if not ok:
        raise Error("adamw8bit parity FAILED")
    print("ALL PASS")
