# training/tests/lora_ema_parity.mojo — torch parity gate for
# training/lora_ema.mojo (Tier-1 parity campaign phase T1.B, 2026-06-11).
# Oracle: /tmp/lora_ema_oracle.safetensors, generated by
#   /home/alex/EriDiffusion/.venv_cache/bin/python \
#       serenitymojo/training/tests/gen_lora_ema_oracle.py
# (SimpleTuner helpers/training/ema.py EMAModel semantics: 2 LoRA-shaped
# adapters, bf16 live params drifting 30 steps, F32 shadows; state1 =
# decay-cap 0.65 / update_after_step 2 / interval 1; state2 = decay 0.9 /
# min_decay 0.2 / interval 2).
#
# PASS iff per final shadow tensor max rel diff <= 1e-6 (loss-class exact),
# per-step decay rel <= 1e-9 vs oracle, and the bf16 export (copy_to cast,
# ema.py:454) is bit-exact. VERIFIED 2026-06-11: max_rel = 0.0 on ALL eight
# shadow tensors + decay (BIT-EXACT vs torch; torch's chain == strict-f32
# chain was numpy-verified, and lora_ema.mojo's _mul_f32 @no_inline barrier
# kills the FMA contraction that cost 6e-6 rel on the first run).
#
# Build/run (standard test build, see sdpa_masked_backward_parity.mojo):
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/training/tests/lora_ema_parity.mojo -o /tmp/lora_ema_parity \
#   && /tmp/lora_ema_parity
from std.gpu.host import DeviceContext
from serenitymojo.tensor import Tensor
from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.training.train_step import LoraAdapter
from serenitymojo.training.lora_ema import (
    LoraEmaState, lora_ema_track, lora_ema_decay_at, ema_begin_step,
    ema_apply, ema_update, ema_shadow_a_bf16, ema_shadow_b_bf16,
    lora_ema_adapters, ema_path_for_lora,
)

comptime N_STEPS = 30


def _rel(got: Float32, exp: Float32) -> Float64:
    var d = Float64(got) - Float64(exp)
    if d < 0.0:
        d = -d
    var m = Float64(exp)
    if m < 0.0:
        m = -m
    if m < 1.0e-30:
        m = 1.0e-30
    return d / m


def _max_rel(got: List[Float32], exp: List[Float32]) raises -> Float64:
    if len(got) != len(exp):
        raise Error("_max_rel: len mismatch")
    var worst = 0.0
    for i in range(len(got)):
        var r = _rel(got[i], exp[i])
        if r > worst:
            worst = r
    return worst


def _zeros(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for _ in range(n):
        out.append(Float32(0.0))
    return out^


# Build the 2 test adapters (a 8x64 / b 96x8, a 4x32 / b 48x4) from the
# oracle's f32-upcast bf16 param lists (idx0..3). Zero moments, scale 1.
def _mk_adapters(
    p0: List[Float32], p1: List[Float32], p2: List[Float32], p3: List[Float32]
) raises -> List[LoraAdapter]:
    var ads = List[LoraAdapter]()
    ads.append(LoraAdapter(
        p0.copy(), p1.copy(), 8, 64, 96, Float32(1.0),
        _zeros(8 * 64), _zeros(8 * 64), _zeros(96 * 8), _zeros(96 * 8),
    ))
    ads.append(LoraAdapter(
        p2.copy(), p3.copy(), 4, 32, 48, Float32(1.0),
        _zeros(4 * 32), _zeros(4 * 32), _zeros(48 * 4), _zeros(48 * 4),
    ))
    return ads^


def main() raises:
    var ctx = DeviceContext()
    var fx = ShardedSafeTensors.open("/tmp/lora_ema_oracle.safetensors")
    var ok = True

    # ── init from p_init (shadow = clone, ema.py:123) ────────────────────────
    var pi0 = Tensor.from_view(fx.tensor_view("p_init_0"), ctx).to_host(ctx)
    var pi1 = Tensor.from_view(fx.tensor_view("p_init_1"), ctx).to_host(ctx)
    var pi2 = Tensor.from_view(fx.tensor_view("p_init_2"), ctx).to_host(ctx)
    var pi3 = Tensor.from_view(fx.tensor_view("p_init_3"), ctx).to_host(ctx)
    var ads = _mk_adapters(pi0, pi1, pi2, pi3)

    var state1 = LoraEmaState(Float32(0.65), Float32(0.0), 2, 1)
    var state2 = LoraEmaState(Float32(0.9), Float32(0.2), 0, 2)
    var base1 = lora_ema_track(state1, ads, 0, len(ads))
    var base2 = lora_ema_track(state2, ads, 0, len(ads))
    if base1 != 0 or base2 != 0:
        raise Error("track base must be 0 on first segment")

    # ── 30 steps: rebuild live params per step, ema_update both states ──────
    var oracle_d1 = Tensor.from_view(fx.tensor_view("decays1"), ctx).to_host(ctx)
    var oracle_d2 = Tensor.from_view(fx.tensor_view("decays2"), ctx).to_host(ctx)
    var decay_worst = 0.0
    for t in range(1, N_STEPS + 1):
        var stem = String("p_s") + String(t) + String("_")
        var q0 = Tensor.from_view(fx.tensor_view(stem + String("0")), ctx).to_host(ctx)
        var q1 = Tensor.from_view(fx.tensor_view(stem + String("1")), ctx).to_host(ctx)
        var q2 = Tensor.from_view(fx.tensor_view(stem + String("2")), ctx).to_host(ctx)
        var q3 = Tensor.from_view(fx.tensor_view(stem + String("3")), ctx).to_host(ctx)
        ads = _mk_adapters(q0, q1, q2, q3)

        # state1: single-list convenience entrypoint (interval 1, never skips)
        ema_update(state1, ads, t)
        var r1 = _rel(Float32(state1.cur_decay), oracle_d1[t - 1])
        if r1 > decay_worst:
            decay_worst = r1

        # state2: explicit begin+apply (the multi-list/klein call shape) +
        # interval-gate check vs the oracle's -1 skip markers (ema.py:29-37)
        var did = ema_begin_step(state2, t)
        var oracle_skipped = oracle_d2[t - 1] < Float32(0.0)
        if did == oracle_skipped:
            print("GATE lora_ema interval t=", t, "did=", did, "FAIL")
            ok = False
        if did:
            ema_apply(state2, ads, 0, len(ads), 0)
            var r2 = _rel(Float32(state2.cur_decay), oracle_d2[t - 1])
            if r2 > decay_worst:
                decay_worst = r2
    var dpass = decay_worst <= 1.0e-9
    print("GATE lora_ema decay max_rel=", decay_worst, "PASS" if dpass else "FAIL")
    ok = ok and dpass

    # ── final shadows vs oracle (rel <= 1e-6 per tensor) ─────────────────────
    for which in range(8):
        var name = (
            String("shadow1_") + String(which) if which < 4
            else String("shadow2_") + String(which - 4)
        )
        var exp = Tensor.from_view(fx.tensor_view(name), ctx).to_host(ctx)
        var idx = which % 4
        var got: List[Float32]
        if which < 4:
            got = (
                state1.shadow_a[idx // 2].copy() if idx % 2 == 0
                else state1.shadow_b[idx // 2].copy()
            )
        else:
            got = (
                state2.shadow_a[idx // 2].copy() if idx % 2 == 0
                else state2.shadow_b[idx // 2].copy()
            )
        var worst = _max_rel(got, exp)
        var pass_ = worst <= 1.0e-6
        print("GATE lora_ema", name, "max_rel=", worst, "PASS" if pass_ else "FAIL")
        ok = ok and pass_

    # ── bf16 export (copy_to cast, ema.py:454): bit-exact vs torch .to(bf16) ─
    var ema_ads = lora_ema_adapters(state1, ads, 0, len(ads), 0)
    var bf_mism = 0
    for which in range(4):
        var name = String("shadow1_bf16_") + String(which)
        var exp = Tensor.from_view(fx.tensor_view(name), ctx).to_host(ctx)
        var k = which // 2
        var got_bf: List[BFloat16]
        if which % 2 == 0:
            got_bf = ema_shadow_a_bf16(state1, k)
        else:
            got_bf = ema_shadow_b_bf16(state1, k)
        # lora_ema_adapters must carry the SAME bf16 values (save path)
        var via_ad = ema_ads[k].a.copy() if which % 2 == 0 else ema_ads[k].b.copy()
        for j in range(len(exp)):
            if got_bf[j].cast[DType.float32]() != exp[j]:
                bf_mism += 1
            if via_ad[j].cast[DType.float32]() != exp[j]:
                bf_mism += 1
    var bpass = bf_mism == 0
    print("GATE lora_ema bf16_export mismatches=", bf_mism, "PASS" if bpass else "FAIL")
    ok = ok and bpass

    # ── save-path convention ──────────────────────────────────────────────────
    var p = ema_path_for_lora(String("/tmp/alina_lora_step100.safetensors"))
    var ppass = p == String("/tmp/alina_lora_step100_ema.safetensors")
    print("GATE lora_ema ema_path", p, "PASS" if ppass else "FAIL")
    ok = ok and ppass

    if not ok:
        raise Error("lora_ema parity FAILED")
    print("ALL PASS")
