# training/tests/lycoris_family_parity.mojo — torch-lycoris parity gate for the
# T2.F Lycoris family (LoCon / LoHa / Tucker / OFT), Tier-2 campaign 2026-06-11.
#
# Oracle: /tmp/lycoris_family_oracle.safetensors, generated by
#   python3 serenitymojo/training/tests/gen_lycoris_family_oracle.py
# (pip lycoris_lora 3.4.0 — LoConModule / LohaModule / DiagOFTModule with seeded
# bf16-quantized weights; outputs computed via the package's OWN get_diff_weight
# / make_weight + F.conv2d / F.linear).
#
# Per family this gate:
#   1. builds the in-tree Mojo adapter from the oracle's (layout-converted)
#      weights and runs the Mojo forward — PASS iff cos >= 0.99999 (F32 data,
#      F64 accumulate) vs the torch output;
#   2. saves the adapter through training/*_save.mojo to /tmp/mojo_<fam>.safetensors
#      and re-opens it — PASS iff the factor values round-trip byte-exact.
# The ECOSYSTEM side of the save loop (upstream lycoris loads the Mojo files and
# reproduces the same forward) is closed by
#   python3 serenitymojo/training/tests/lycoris_family_load_check.py
# which must be run AFTER this gate.
#
# Build/run (standard test build):
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/training/tests/lycoris_family_parity.mojo \
#     -o /tmp/lycoris_family_parity && /tmp/lycoris_family_parity
from std.collections import List
from std.math import sqrt
from std.gpu.host import DeviceContext
from serenitymojo.io.safetensors import SafeTensors
from serenitymojo.io.dtype import STDtype
from serenitymojo.training.locon_conv_adapter import LoConConvAdapter, locon_forward
from serenitymojo.training.tucker_conv_adapter import TuckerConvAdapter, tucker_forward
from serenitymojo.training.loha_adapter import LoHaAdapter, loha_forward
from serenitymojo.training.oft_adapter import OFTAdapter, oft_forward
from serenitymojo.training.locon_save import NamedLoCon, save_locon_peft, read_locon_module
from serenitymojo.training.tucker_save import NamedTucker, save_tucker_peft, read_tucker_module
from serenitymojo.training.loha_save import NamedLoHa, save_loha_peft, read_loha_module
from serenitymojo.training.oft_save import NamedOFT, save_oft_peft, read_oft_module

comptime ORACLE = "/tmp/lycoris_family_oracle.safetensors"
comptime COS_BAR = 0.99999


def _zeros(n: Int) -> List[Float32]:
    var out = List[Float32]()
    for _ in range(n):
        out.append(Float32(0.0))
    return out^


def _read_f32(st: SafeTensors, name: String) raises -> List[Float32]:
    var info = st.tensor_info(name)
    if info.dtype != STDtype.F32:
        raise Error(String("_read_f32: oracle tensor not F32: ") + name)
    var bytes = st.tensor_bytes(name)
    var fp = bytes.unsafe_ptr().bitcast[Float32]()
    var out = List[Float32]()
    for i in range(info.size // 4):
        out.append(fp[i])
    return out^


def _cos(a: List[Float32], b: List[Float32]) raises -> Float64:
    if len(a) != len(b):
        raise Error(String("_cos: len mismatch ") + String(len(a)) + " != " + String(len(b)))
    var num = 0.0
    var na = 0.0
    var nb = 0.0
    for i in range(len(a)):
        var x = Float64(a[i])
        var y = Float64(b[i])
        num += x * y
        na += x * x
        nb += y * y
    if na == 0.0 or nb == 0.0:
        raise Error("_cos: zero vector (degenerate gate)")
    return num / (sqrt(na) * sqrt(nb))


# Relative L2-norm mismatch — catches pure SCALE errors that cosine is blind to
# (measured 2026-06-11: upstream LoHa get_diff_weight double-applies scale; cos
# stayed 0.99999999 while the output was 2x off).
def _norm_rel(a: List[Float32], b: List[Float32]) raises -> Float64:
    if len(a) != len(b):
        raise Error("_norm_rel: len mismatch")
    var na = 0.0
    var nb = 0.0
    for i in range(len(a)):
        na += Float64(a[i]) * Float64(a[i])
        nb += Float64(b[i]) * Float64(b[i])
    na = sqrt(na)
    nb = sqrt(nb)
    if nb == 0.0:
        raise Error("_norm_rel: zero reference norm (degenerate gate)")
    var d = na - nb
    if d < 0.0:
        d = -d
    return d / nb


def _max_abs(a: List[Float32], b: List[Float32]) raises -> Float32:
    if len(a) != len(b):
        raise Error("_max_abs: len mismatch")
    var worst = Float32(0.0)
    for i in range(len(a)):
        var d = a[i] - b[i]
        if d < Float32(0.0):
            d = -d
        if d > worst:
            worst = d
    return worst


def _f32_eq(a: List[Float32], b: List[Float32]) raises -> Bool:
    return _max_abs(a, b) == Float32(0.0)


def _bf16_eq(a: List[BFloat16], b: List[BFloat16]) raises -> Bool:
    if len(a) != len(b):
        raise Error("_bf16_eq: len mismatch")
    for i in range(len(a)):
        if a[i].cast[DType.float32]() != b[i].cast[DType.float32]():
            return False
    return True


def _bf16_to_f32(v: List[BFloat16]) -> List[Float32]:
    var out = List[Float32]()
    for i in range(len(v)):
        out.append(v[i].cast[DType.float32]())
    return out^


def main() raises:
    var ctx = DeviceContext()
    var st = SafeTensors.open(ORACLE)
    var ok = True

    # ── LoCon: Cin=8 Cout=16 k3 s1 p1 R=4 alpha=2 ; x [2,6,6,8] ──────────────
    var lc_down = _read_f32(st, "locon.down_rscf")     # [3,3,8,4]
    var lc_up = _read_f32(st, "locon.up_rc")           # [4,16]
    var lc_x = _read_f32(st, "locon.x_nhwc")           # [2,6,6,8]
    var lc_y = _read_f32(st, "locon.y_nhwc")           # [2,6,6,16]
    var lc = LoConConvAdapter(
        lc_down.copy(), lc_up.copy(), 8, 16, 3, 3, 4, 1, 1, 1, 1, Float32(2.0),
        _zeros(3 * 3 * 8 * 4), _zeros(3 * 3 * 8 * 4), _zeros(4 * 16), _zeros(4 * 16),
    )
    var lc_got = locon_forward(lc_x, lc, 2, 6, 6)
    var c = _cos(lc_got, lc_y)
    var nr_locon = _norm_rel(lc_got, lc_y)
    if c >= COS_BAR and nr_locon <= 1.0e-5:
        print("PASS (locon fwd): cos=", c, " norm_rel=", nr_locon, " max|d|=", _max_abs(lc_got, lc_y))
    else:
        print("FAIL (locon fwd): cos=", c, " norm_rel=", nr_locon); ok = False

    var lc_named = List[NamedLoCon]()
    lc_named.append(NamedLoCon(String("lora_unet_locon_t"), lc.copy()))
    _ = save_locon_peft(lc_named, String("/tmp/mojo_locon.safetensors"), ctx)
    var lc_rb = read_locon_module(String("lora_unet_locon_t"), String("/tmp/mojo_locon.safetensors"), ctx)
    if _f32_eq(lc_rb.down, lc.down) and _f32_eq(lc_rb.up, lc.up) and lc_rb.alpha == Float32(2.0) and lc_rb.cin == 8 and lc_rb.cout == 16 and lc_rb.rank == 4:
        print("PASS (locon save): round-trip byte-exact, /tmp/mojo_locon.safetensors")
    else:
        print("FAIL (locon save): round-trip mismatch"); ok = False

    # ── Tucker: Cin=8 Cout=16 k3 s2 p1 R=4 alpha=2 ; x [2,7,7,8] → y [2,4,4,16]
    var tk_down = _read_f32(st, "tucker.down_cr")      # [8,4]
    var tk_core = _read_f32(st, "tucker.core_rscf")    # [3,3,4,4]
    var tk_up = _read_f32(st, "tucker.up_rc")          # [4,16]
    var tk_x = _read_f32(st, "tucker.x_nhwc")
    var tk_y = _read_f32(st, "tucker.y_nhwc")
    var tk = TuckerConvAdapter(
        tk_down.copy(), tk_core.copy(), tk_up.copy(), 8, 16, 3, 3, 4, 2, 2, 1, 1, Float32(2.0),
        _zeros(8 * 4), _zeros(8 * 4), _zeros(3 * 3 * 4 * 4), _zeros(3 * 3 * 4 * 4),
        _zeros(4 * 16), _zeros(4 * 16),
    )
    var tk_got = tucker_forward(tk_x, tk, 2, 7, 7)
    c = _cos(tk_got, tk_y)
    var nr_tucker = _norm_rel(tk_got, tk_y)
    if c >= COS_BAR and nr_tucker <= 1.0e-5:
        print("PASS (tucker fwd): cos=", c, " norm_rel=", nr_tucker, " max|d|=", _max_abs(tk_got, tk_y))
    else:
        print("FAIL (tucker fwd): cos=", c, " norm_rel=", nr_tucker); ok = False

    var tk_named = List[NamedTucker]()
    tk_named.append(NamedTucker(String("lora_unet_tucker_t"), tk.copy()))
    _ = save_tucker_peft(tk_named, String("/tmp/mojo_tucker.safetensors"), ctx)
    var tk_rb = read_tucker_module(String("lora_unet_tucker_t"), String("/tmp/mojo_tucker.safetensors"), ctx)
    if _f32_eq(tk_rb.down, tk.down) and _f32_eq(tk_rb.core, tk.core) and _f32_eq(tk_rb.up, tk.up) and tk_rb.alpha == Float32(2.0):
        print("PASS (tucker save): round-trip byte-exact, /tmp/mojo_tucker.safetensors")
    else:
        print("FAIL (tucker save): round-trip mismatch"); ok = False

    # ── LoHa: in=12 out=16 R=4 alpha=2 ; x [5,12] ────────────────────────────
    var lh_w1a = _read_f32(st, "loha.w1a_mojo")        # [12,4]
    var lh_w1b = _read_f32(st, "loha.w1b_mojo")        # [4,16]
    var lh_w2a = _read_f32(st, "loha.w2a_mojo")
    var lh_w2b = _read_f32(st, "loha.w2b_mojo")
    var lh_x = _read_f32(st, "loha.x")
    var lh_y = _read_f32(st, "loha.y")
    var lh = LoHaAdapter(
        lh_w1a.copy(), lh_w1b.copy(), lh_w2a.copy(), lh_w2b.copy(),
        4, 12, 16, Float32(2.0),
        _zeros(12 * 4), _zeros(12 * 4), _zeros(4 * 16), _zeros(4 * 16),
        _zeros(12 * 4), _zeros(12 * 4), _zeros(4 * 16), _zeros(4 * 16),
    )
    var lh_got = loha_forward(lh_x, lh, 5)
    c = _cos(lh_got, lh_y)
    var nr_loha = _norm_rel(lh_got, lh_y)
    if c >= COS_BAR and nr_loha <= 1.0e-5:
        print("PASS (loha fwd): cos=", c, " norm_rel=", nr_loha, " max|d|=", _max_abs(lh_got, lh_y))
    else:
        print("FAIL (loha fwd): cos=", c, " norm_rel=", nr_loha); ok = False

    var lh_named = List[NamedLoHa]()
    lh_named.append(NamedLoHa(String("lora_unet_loha_t"), lh.copy()))
    _ = save_loha_peft(lh_named, String("/tmp/mojo_loha.safetensors"), ctx)
    var lh_rb = read_loha_module(String("lora_unet_loha_t"), String("/tmp/mojo_loha.safetensors"), ctx)
    if (
        _bf16_eq(lh_rb.w1a, lh.w1a) and _bf16_eq(lh_rb.w1b, lh.w1b)
        and _bf16_eq(lh_rb.w2a, lh.w2a) and _bf16_eq(lh_rb.w2b, lh.w2b)
        and lh_rb.in_f == 12 and lh_rb.out_f == 16 and lh_rb.rank == 4
        and lh_rb.alpha == Float32(2.0)
    ):
        print("PASS (loha save): round-trip byte-exact (upstream-keyed), /tmp/mojo_loha.safetensors")
    else:
        print("FAIL (loha save): round-trip mismatch"); ok = False

    # ── Diag-OFT: in=12 out=16 nb=4 b=4 constraint(alpha)=0 ; x [5,12] ───────
    var of_s = _read_f32(st, "oft.s_mojo")             # [4,4,4] (Mojo S = 2*blocks)
    var of_w = _read_f32(st, "oft.w_base")             # [16,12]
    var of_x = _read_f32(st, "oft.x")
    var of_y = _read_f32(st, "oft.y")
    var of = OFTAdapter(
        of_s.copy(), of_w.copy(), 4, 4, 12, 16, Float32(0.0),
        _zeros(4 * 4 * 4), _zeros(4 * 4 * 4),
    )
    var of_got = oft_forward(of_x, of, 5)
    c = _cos(of_got, of_y)
    var nr_oft = _norm_rel(of_got, of_y)
    if c >= COS_BAR and nr_oft <= 1.0e-5:
        print("PASS (oft fwd): cos=", c, " norm_rel=", nr_oft, " max|d|=", _max_abs(of_got, of_y))
    else:
        print("FAIL (oft fwd): cos=", c, " norm_rel=", nr_oft); ok = False

    var of_named = List[NamedOFT]()
    of_named.append(NamedOFT(String("lora_unet_oft_t"), of.copy()))
    _ = save_oft_peft(of_named, String("/tmp/mojo_oft.safetensors"), ctx)
    var of_rb = read_oft_module(String("lora_unet_oft_t"), String("/tmp/mojo_oft.safetensors"), ctx)
    if _bf16_eq(of_rb.s, of.s) and of_rb.num_blocks == 4 and of_rb.block_size == 4 and of_rb.alpha == Float32(0.0):
        print("PASS (oft save): S round-trip byte-exact (0.5x on-disk blocks), /tmp/mojo_oft.safetensors")
    else:
        print("FAIL (oft save): round-trip mismatch"); ok = False

    if not ok:
        raise Error("lycoris_family_parity: FAIL (see lines above)")
    print("lycoris_family_parity ALL GATES PASS (locon/tucker/loha/oft fwd cos>=0.99999 + norm_rel<=1e-5 + save round-trips)")
    print("NEXT: python3 serenitymojo/training/tests/lycoris_family_load_check.py")
