# training/tests/optimizer_parity.mojo — T1.C torch-oracle parity gate for
# training/adafactor.mojo + training/adamw_schedulefree.mojo (host math).
#
# Oracle: /tmp/optimizer_oracle.safetensors, generated by
#   /home/alex/SimpleTuner/.venv/bin/python \
#     serenitymojo/training/tests/gen_optimizer_oracle.py
# which drives the EXACT reference implementations SimpleTuner uses:
#   torch.optim.Adafactor (torch 2.10, _adafactor.py:330-416) and
#   AdamWScheduleFreeKahan (SimpleTuner in-house,
#   helpers/training/optimizers/adamw_schedulefree/__init__.py:10-145),
# 20 steps, F32, seeded 2D params/grads (LoRA-A 16x64 + LoRA-B 64x16).
#
# GATE: final params per config rel(L2) <= 1e-5 AND cos >= 0.999999.
# Host-only (no GPU); modeled on ops/tests/sdpa_masked_backward_parity.mojo.
#
# Build/run:
#   cd /home/alex/mojodiffusion && rm -f serenitymojo.mojopkg && \
#   pixi run mojo build -I . -Xlinker -lm -Xlinker -lcuda \
#     -Xlinker -L.pixi/envs/default/lib -Xlinker -lsqlite3 \
#     serenitymojo/training/tests/optimizer_parity.mojo \
#     -o /tmp/optimizer_parity && /tmp/optimizer_parity

from std.math import sqrt

from serenitymojo.io.sharded import ShardedSafeTensors
from serenitymojo.training.adafactor import AdafactorState, adafactor_step_2d
from serenitymojo.training.adamw_schedulefree import (
    AdamWScheduleFreeCtl,
    AdamWScheduleFreeState,
    adamw_schedulefree_adjusted_lr,
    adamw_schedulefree_eval,
    adamw_schedulefree_step_param,
)

comptime STEPS = 20
comptime R_A = 16
comptime C_A = 64
comptime R_B = 64
comptime C_B = 16


def _load_f32(fx: ShardedSafeTensors, name: String) raises -> List[Float32]:
    var b = fx.tensor_bytes(name)
    var n = len(b) // 4
    var ptr = b.unsafe_ptr().bitcast[Float32]()
    var out = List[Float32](capacity=n)
    for i in range(n):
        out.append(ptr[i])
    return out^


def _slice(g: List[Float32], step: Int, n: Int) -> List[Float32]:
    var out = List[Float32](capacity=n)
    for i in range(n):
        out.append(g[step * n + i])
    return out^


def _rel_l2(a: List[Float32], b: List[Float32]) raises -> Float64:
    if len(a) != len(b):
        raise Error("_rel_l2: length mismatch")
    var diff = 0.0
    var nb = 0.0
    for i in range(len(a)):
        var d = Float64(a[i]) - Float64(b[i])
        diff += d * d
        nb += Float64(b[i]) ** 2
    return sqrt(diff) / sqrt(nb)


def _cos(a: List[Float32], b: List[Float32]) -> Float64:
    var dot = 0.0
    var na = 0.0
    var nb = 0.0
    for i in range(len(a)):
        dot += Float64(a[i]) * Float64(b[i])
        na += Float64(a[i]) ** 2
        nb += Float64(b[i]) ** 2
    return dot / (sqrt(na) * sqrt(nb))


def _gate(
    label: String, got: List[Float32], exp: List[Float32], mut ok: Bool
) raises:
    var rel = _rel_l2(got, exp)
    var c = _cos(got, exp)
    var pass_ = rel <= 1e-5 and c >= 0.999999
    print(
        "GATE optimizer", label, "rel=", rel, "cos=", c,
        "PASS" if pass_ else "FAIL",
    )
    ok = ok and pass_


def _gate_cos(
    label: String, got: List[Float32], exp: List[Float32], mut ok: Bool
) raises:
    """Cos-only gate for MOMENT buffers: their elements sit near F32 epsilon
    scale ((1-b2)*g^2 ~ 1e-7 increments), where host-FMA-contraction vs
    torch's mul_/addcmul_ two-rounding sequence leaves ulp-level relative
    noise (measured rel ~1.3e-5 on v with cos = 1 - 6e-15). The T1.C mandate
    gates PARAMS at rel<=1e-5; moments are direction-gated + rel reported."""
    var rel = _rel_l2(got, exp)
    var c = _cos(got, exp)
    var pass_ = c >= 0.999999
    print(
        "GATE optimizer", label, "(cos-gated, rel informational) rel=", rel,
        "cos=", c, "PASS" if pass_ else "FAIL",
    )
    ok = ok and pass_


def main() raises:
    var fx = ShardedSafeTensors.open("/tmp/optimizer_oracle.safetensors")
    var p0_a = _load_f32(fx, "p0_a")
    var p0_b = _load_f32(fx, "p0_b")
    var grads_a = _load_f32(fx, "grads_a")
    var grads_b = _load_f32(fx, "grads_b")
    var n_a = R_A * C_A
    var n_b = R_B * C_B
    var ok = True

    # ── adafactor, SimpleTuner "torch-adafactor" defaults, lr=1e-2 ──────────
    for variant in range(2):
        var wd = 0.0
        var tag = String("adafactor")
        if variant == 1:
            wd = 0.01
            tag = String("adafactor_wd")
        var pa = p0_a.copy()
        var pb = p0_b.copy()
        var st_a = AdafactorState(R_A, C_A)
        var st_b = AdafactorState(R_B, C_B)
        for t in range(STEPS):
            var ga = _slice(grads_a, t, n_a)
            var gb = _slice(grads_b, t, n_b)
            adafactor_step_2d(pa, ga, st_a, 1e-2, -0.8, -1.0, 1e-3, 1.0, wd)
            adafactor_step_2d(pb, gb, st_b, 1e-2, -0.8, -1.0, 1e-3, 1.0, wd)
        var key = String("ada_pa") if variant == 0 else String("ada_wd_pa")
        _gate(tag + "/A", pa, _load_f32(fx, key), ok)
        key = String("ada_pb") if variant == 0 else String("ada_wd_pb")
        _gate(tag + "/B", pb, _load_f32(fx, key), ok)

    # ── adamw_schedulefree (AdamWScheduleFreeKahan), warmup_steps=5 ─────────
    var pa = p0_a.copy()
    var pb = p0_b.copy()
    var sf_a = AdamWScheduleFreeState(n_a)
    var sf_b = AdamWScheduleFreeState(n_b)
    var ctl = AdamWScheduleFreeCtl()
    comptime LR = 1e-3
    comptime B1 = 0.9
    comptime B2 = 0.999
    comptime EPS = 1e-8
    comptime WD = 1e-2
    comptime WARMUP = 5
    for _ in range(STEPS):
        var t = ctl.k
        var alr = adamw_schedulefree_adjusted_lr(t, LR, B2, WARMUP)
        var ga = _slice(grads_a, t, n_a)
        var gb = _slice(grads_b, t, n_b)
        adamw_schedulefree_step_param(
            pa, ga, sf_a, t, LR, B1, B2, EPS, WD, WARMUP, True
        )
        adamw_schedulefree_step_param(
            pb, gb, sf_b, t, LR, B1, B2, EPS, WD, WARMUP, True
        )
        ctl.end_step(alr)
    _gate(String("schedulefree/A"), pa, _load_f32(fx, "sf_pa"), ok)
    _gate(String("schedulefree/B"), pb, _load_f32(fx, "sf_pb"), ok)
    # moments (debug visibility; cos-gated — see _gate_cos)
    _gate_cos(
        String("schedulefree/m_a"), sf_a.exp_avg, _load_f32(fx, "sf_m_a"), ok
    )
    _gate_cos(
        String("schedulefree/v_a"), sf_a.exp_avg_sq, _load_f32(fx, "sf_v_a"), ok
    )

    # eval() before save: must be a no-op in this reference (no z state) —
    # eval weights == train weights, and kahan_comp must be exactly 0.
    var params_for_eval = List[List[Float32]]()
    params_for_eval.append(pa.copy())
    params_for_eval.append(pb.copy())
    adamw_schedulefree_eval(ctl, params_for_eval)
    _gate(String("schedulefree/eval_A"), pa, _load_f32(fx, "sf_eval_pa"), ok)
    _gate(String("schedulefree/eval_B"), pb, _load_f32(fx, "sf_eval_pb"), ok)
    var kahan_max = Float32(0.0)
    for i in range(n_a):
        var av = sf_a.kahan_comp[i]
        if av < 0:
            av = -av
        if av > kahan_max:
            kahan_max = av
    var kahan_pass = kahan_max == Float32(0.0)
    print(
        "GATE optimizer schedulefree/kahan_zero max=", kahan_max,
        "PASS" if kahan_pass else "FAIL",
    )
    ok = ok and kahan_pass

    if not ok:
        raise Error("optimizer parity FAILED")
    print("ALL PASS")
